### ISSUE TITLE
0.114.1 `serverInstallPath` substituted into install script with single quotes

### ISSUE THREAD

**Issue by zhengyu-yang** [microsoft/vscode-remote-release#10230]
After updating to 0.114.0, VS Code Remote stuck on 
```
"Copy server to host" terminal command done
```

**Comment by joshspicer** [comment]
Thanks for sharing, you could please provide your [logs](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting)?

**Comment by justineakehurst** [comment]
I have the same repro. Attaching logs. usernames and hostnames are redacted.
[vscode-issue-10230.log.txt](https://github.com/user-attachments/files/16901269/vscode-issue-10230.log.txt)

**Comment by joshspicer** [comment]
Thank you for sharing @justineakehurst

**Comment by justineakehurst** [comment]
Additional details:
- server-side `/workspace/.vscode-server` has nothing in it, it's owned by me, chmod'ed 755. All completely working until the latest update of vscode.
- After attempting to start vscode and hitting this issue, this is the contents of the dir, with sha's:
```
-rw-r--r--  1 username usergroup 8964808 Sep  5 17:19 vscode-cli-4849ca9bdf9666755eb463db297b69e5385090e3.tar.gz
-rw-r--r--  1 username usergroup       9 Sep  5 17:19 vscode-cli-4849ca9bdf9666755eb463db297b69e5385090e3.tar.gz.done
server% sha256sum vscode-cli-4849ca9bdf9666755eb463db297b69e5385090e3.tar.gz
a75f8309f7062961badf7436daebd71f0199d28e1b6ab89160ee95c053983356  vscode-cli-4849ca9bdf9666755eb463db297b69e5385090e3.tar.gz
server% sha256sum vscode-cli-4849ca9bdf9666755eb463db297b69e5385090e3.tar.gz.done
161069badc0cc23058b13d7c068e45205f4333aa15fd78db9d68f5c9f1ae8983  vscode-cli-4849ca9bdf9666755eb463db297b69e5385090e3.tar.gz.done
```

**Comment by justineakehurst** [comment]
VSCode on the client side (windows 11 enterprise) just says "Setting up SSH Host <hostname>: Copying VS Code Server to host with scp", and a continuously-looping progress thingy at the bottom, and just sits there like this, forever.

**Comment by justineakehurst** [comment]
If there's a short term workaround for this, I'd appreciate it as I'd like to get back to work.

**Comment by joshspicer** [comment]
The quickest workaround will be downgrading to the previous build (0.113.1) while I work to get a pre-release fix out for testing. 

From looking at the logs I have an idea of the issue. The value for `vscodeAgentFolder` is being injected into the script with single quotes (`'/workspace'/.vscode-server`).  That's not happening on my test machines so I'll need to dig a bit deeper.

If you're not able to downgrade, I suspect temporarily disabling `useExecServer` may help as well (forcing a fallback to an older code path).

**Comment by justineakehurst** [comment]
OK, was able to work around it myself with that hint.
I did have a configuration for "remote.SSH.serverInstallPath" as this:
```
    "remote.SSH.serverInstallPath": {
        "username.server.local": "/workspace",
        "username-two.server.local": "/workspace"
    },
```
I've now symlinked `/workspace/.vscode-server` to `~/.vscode-server`, and removed the entire `remote.SSH.serverInstallPath` directive from the settings, and restarted vscode.

With that, everything works.

Seems like tracking down where the single quotes around the key-values for the install path entries is where you'll find the RCA.

**Comment by joshspicer** [comment]
Ah, that value is coming from the the `remote.SSH.serverInstallPath` (which I do not have set and therefore is defaulting to `$HOME` without the quoting).

You likely have that set for a reason so I still suggest downgrading, though another option is to temporarily remove that setting.

**Comment by justineakehurst** [comment]
My pleasure, thanks for the responsiveness.

**Comment by zhengyu-yang** [comment]
I did see the scp command becomes
```
scp -o ConnectTimeout=15 'vscode-cli-4849ca9bdf9666755eb463db297b69e5385090e3.tar.gz' 'vscode-cli-4849ca9bdf9666755eb463db297b69e5385090e3.tar.gz.done' dev:''{HOME}/.local/vscode'/.vscode-server'
```

**Comment by Tamas-hi** [comment]
I also had the same issue from today's morning, and the easiest solution as to downgrade to version 113 for now.

**Comment by joshspicer** [comment]
Yes @sirK84 I agree, looks to be the same issue. Working on a fix.

**Comment by joshspicer** [comment]
Pre-release `v0.115.2024090617 (pre-release)` build of the extension should have this fixed. If anyone is able to test, please let me know.

**Comment by dahjelle** [comment]
@joshspicer A quick test on my end seems to be working!

**Comment by sirK84** [comment]
@joshspicer I also confirm, on pre-release version issue is not visible anymore.

**Comment by joshspicer** [comment]
@sirK84 , would you mind sharing your logs when this happens?

**Comment by sirK84** [comment]
@joshspicer, my procedure was sth. like this:

1. kill vs code server on remote host
2. wait until all vs code processes are down on remote
3. update Remote SSH to pre-release
4. connect to remote host

I did not remove the .vscode-server directory though (I'd rather avoid that due to the settings and custom plugins I have there).

I think maybe setting is somehow respected partially?

Installer is finding the server binary in remote.SSH.serverInstallPath:

> [16:49:05.672] > Found existing installation at /var/fpwork/username//.vscode-server...

But it still creates the new .vscode-server directory in HOME with empty extensions dir. Unfortunatelly it means it cannot see the extensions kept in remote.SSH.serverInstallPath:/

Is there a way to update without cleaning whole .vscode-server dir? Maybe by just removing old server binary and cli dir?

Attaching full log:
[RemoteSSH_v0.115.2024090921.log](https://github.com/user-attachments/files/16947658/RemoteSSH_v0.115.2024090921.log)

**Comment by joshspicer** [comment]
Thank you for sharing your logs, @sirK84 

As you've shared it looks like `serverInstallPath` is being respected now for the server binary in the install script, but I do see at the end of the log references to the default $HOME directory for extensions.

```
[16:49:06.393] [server] [14:49:06] Started initializing default profile extensions in extensions installation folder. file:///home/<<username>>/.vscode-server/extensions
[16:49:06.435] [server] [14:49:06] Completed initializing default profile extensions in extensions installation folder. file:///home/<<username>>/.vscode-server/extensions
```

If this behaved differently on the previous release (do you know if that's true?) then I have a hunch of why this could be. To ensure the issue doesn't get lost i've opened: https://github.com/microsoft/vscode-remote-release/issues/10255

**Comment by sirK84** [comment]
@joshspicer, yes it behaved differently before 0.114 version. 

In v0.113.1 those logs are not present:

> [18:18:51.875] [server] [16:18:51] Extension host agent started.
[18:18:52.058] [server] [16:18:51] [\<unknown\>][7e4c6472][ExtensionHostConnection] New connection established.
[18:18:52.058] [server] [16:18:51] [\<unknown\>][f7a68617][ManagementConnection] New connection established.
[18:18:52.230] [server] [16:18:52] [\<unknown\>][7e4c6472][ExtensionHostConnection] <12870> Launched Extension Host Process.

**Comment by joshspicer** [comment]
Release version `0.114.2` fixes the single quoting issue with user-provided `serverInstallPath`s

If you're seeing continued issues related to what @sirK84 has reported, please provide your feedback on https://github.com/microsoft/vscode-remote-release/issues/10255

**Comment by leon-v** [comment]
I run an Ubuntu server where multiple VSCode users SSH remote into, and they all use the `ubutnu` user for development. Previously, we used this config to keep our settings and extension separate:

```
"remote.SSH.serverInstallPath": {
    "server-name":"~/.vscode-username"
}
```

However, we all also had VSCode stall on "*Downloading VSCode Server*". Around the same time, I also noticed that the `~` in the `remote.SSH.serverInstallPath` value was taken literally, and a directory named `~` was added to the home folder, so this was the new path: `/home/ubuntu/~/.vscode-username/.vscode-server`

We set `"remote.SSH.useExecServer": false` to fix this, however, I noticed that I could connect to other users' VSCode server instances / shells and read sensitive environment variables passed through from VSCode. Users also displayed odd behaviour as they inadvertently shared shells.

I hypothesized that the root cause was how VSCode managed the relative path, so I tried a few things.

Ultimately, I found that using `$HOME` instead of `~` fixed both my problems. I am now able to connect to the host with `"remote.SSH.useExecServer": true` or leave it omitted, and use:

```
"remote.SSH.serverInstallPath": {
    "server-name":"$HOME/.vscode-username"
}
```

VSCod server installed first try with no issues, and my install path is the expected:

`/home/ubuntu/.vscode-username/.vscode-server`

Everything seems to work correctly for me now.

**Comment by joshspicer** [comment]
Verification steps:
1. Have a remote linux or MacOS host available to SSH to (localhost is fine).  Add it to your SSH configuration by opening up config file with command palette (`Open SSH Configuration File`). Eg: 
```
Host my-ubuntu-vm
  HostName 172.99.113.159
  User josh
```
2. Set the `serverInstallPath` setting to a directory that isn't in your $HOME.  Maybe set up a folder with the following commands:
```
sudo mkdir /opt/my-dir
sudo chown $USER:$USER /opt/my-dir  # Make sure you won't run into any permissions issues
```
3. Change your `serverInstallPath` setting for this host. Eg:
```
"remote.SSH.serverInstallPath": {
    "my-ubuntu-vm":"/opt/my-dir"
}
```
4. Ensure that all your other Remote - SSH settings are default (or at least `useExecServer == true`)
5. Ensure that you can successfully connect.
6. Validate that your new serverInstallPath has files in it and is being used


Note: see https://github.com/microsoft/vscode-remote-release/issues/10230#issuecomment-2341264178 if you've connected recently to this host.  You may need to kill a running VS Code server (avoiding the reconnect fast path)
