### ISSUE TITLE
Latest Remote SSH is putting single quotes

### ISSUE THREAD

**Issue by DKGH** [microsoft/vscode-remote-release#10250]
Latest Remote SSH is putting single quotes around host server install path. Had to roll back the version to fix this problem.

**Comment by joshspicer** [comment]
Thanks for taking the time to open an issue.  This is fixed in the pre-release extension and will be in the release build shortly (please give the pre-release a try and let me know how it works, [making sure you kill any running servers first](https://github.com/microsoft/vscode-remote-release/issues/10230#issuecomment-2341264178)) 

Closing to track in https://github.com/microsoft/vscode-remote-release/issues/10230
