### ISSUE TITLE
[devcontainer]: install recommended extensions on container rebuild

### ISSUE THREAD

**Issue by ThePlenkov** [microsoft/vscode-remote-release#10420]
# Problem statement

When working in a devcontainer we used to preinstall some extensions using devcontainer.json file:

```json
{ 
  "customizations": {
    "vscode": {
      "extensions": ["nrwl.angular-console"]
    }
  } 
}
```

at same time we have another file  .vscode/extensions.json which has also extension recommdations:
```
{
  "recommendations": [
    "nrwl.angular-console", 
  ]
}
```

So now we have to maintain it in parallel, or we can just keep recommendations , but in this case, when container is rebuilt - they are not installed by default.

# Solution

I'd like to suggest to introduce a new feature in a devcontainer.json:
```
  "customizations": {
    "vscode": {
      "installRecommendedExtensions": true
    }
  }
```

If this flag is set I expect devcontainer to install extension recommendations in addition to extensions, directly mentioned in the devcontainer.json

# Other benefits

- Currently "add to devcontainer" action always suggest to rebuild the container which is a little bit annoying. With this feature if we'll just add extension to workspace recommendations, then it will be installed on next rebuild.

**Comment by ThePlenkov** [comment]
@chrmarti I'm not sure if it matters, but I noticed in the console when I start a container:
```
unning Dev Containers CLI:   up --container-session-data-folder /tmp/devcontainers-aca8bcf8-4f9a-49a1-abe5-a3dccf5bf7f51734715720359 --workspace-folder /mnt/wsl/workspace/ubuntu/payops-service-db --workspace-mount-consistency cached 
```

I honestly have no idea - but just thought - is there a way to switch this mount consistency somehow and not to produce this `--workspace-mount-consistency cached ` ? 

I would like to use it only as a test

Thanks

**Comment by tobi1220** [comment]
Dang, i guess i was too late to upvote 😦

**Comment by lkraav** [comment]
Yep, super annoying.

I'm currently testing in `postCreateCommand` or `postAttachCommand`

```
jq -r '.recommendations[]' .vscode/extensions.json | xargs -n1 code --install-extension
```

But running into `code` not on `PATH` to call 🤔 who was solution ideas?

Also: shim script checks for VSCODE_IPC_HOOK_CLI (and a couple of related vars) at runtime before doing anything — it's not a PATH-resolution problem, it's a guard baked into the remote-cli/code script. Since neither hook's env has VSCODE_IPC_HOOK_CLI set (confirmed by the dumps you just ran), calling it by absolute path hits the same guard and fails identically.
