### ISSUE TITLE
Windows / WSL / minikube: run without docker for windows?

### ISSUE THREAD

**Issue by remoe** [microsoft/vscode-remote-release#1043]
Why does this extension need docker for windows on windows to work? It should only need a docker client, DOCKER_HOST and DOCKER_CERT_PATH environment, right? Or is it already possible to work with  a minikube/WSL environment?

**Comment by Chuxel** [comment]
@remoe The extension uses the Docker CLto wire up and communicate with the container. To make things easy when you just want to open a local folder in a container, we also "bind" mount the local filesystem by default.  Docker doesn't allow binding remote filesystems (which would result in really poor performance if they did).  However, you can tweak devcontainer.json or your Docker Compose file to work with remote hosts.  Technically the Docker daemon / service does not need to be local - just the latest version of the CLI for docker and docker-compose (if you use it).

See here: https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host

For native Kubernetes support (using kubectl w/o docker), you can upvote here: #12. 

Docker's plans for Docker for Windows is to switch to WSL2, so that will cover WSL support over time. They're just not there yet.

**Comment by remoe** [comment]
Thanks for the detailed explanation.
