### ISSUE TITLE
Outline doesn't work

### ISSUE THREAD

**Issue by tdcwright** [microsoft/vscode-remote-release#1140]
Issue Type: <b>Bug</b>

When using WSL, the outline doesnt work. This means my variables aren't put into snippets correctly.

In the outline section it says:
"The active editor cannot provide outline information."

Extension version: 0.39.2
VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

**Comment by egamma** [comment]
What editor do you have open when this happens?
Does it work when you have the same editor open locally?
What extensions do you have installed?

**Comment by tdcwright** [comment]
Hi Erich,
My guess is that it would be because my extensions haven’t transferred properly to the WSL connection.

What do you mean by editor?
Yes, works normally when using the same editor locally
The extension is the C/C++ that doesn’t seem to work properly. Might just be me though, I might not have correctly transferred my setting across.

Thank you for your help.

________________________________

**Comment by egamma** [comment]
@tdcwright 

what do you mean by:

>My guess is that it would be because my extensions haven’t transferred properly to the WSL connection.

The C++ extension is what we call a workspace extension and this extenison is not transferred automatically for you. You have to install it. Please see Hi Erich,
My guess is that it would be because my extensions haven’t transferred properly to the WSL connection.

Please open the extensions viewlet and verify that the C++ extension is installed on the WSL side.
