### ISSUE TITLE
Manual reconnect

### ISSUE THREAD

**Issue by BernierCR** [microsoft/vscode-remote-release#1197]
Maybe this exists already, but if it does, it's non-obvious. 

I would like a way to manually reconnect a remote ssh session. The UI brings up a reconnect box automatically. But sometimes you are not ready to reconnect. And the UI seems to give up on reconnecting pretty quickly. Then you are stuck with a dead workspace and need to reload the whole window. 

I know, not a priority, but it would be fantastic if there was a one or two click way to trigger the reconnect logic. 

Thank you.

**Comment by xgdgsc** [comment]
Please fix this for daily suspenders.

**Comment by tanhakabir** [comment]
@BernierCR just curious if the command: `Developer: Reload Window` suffices for manual reconnect?

**Comment by tsiemens** [comment]
@tanhakabir I can't speak for BenierCR here, but in my experience `Developer: Reload Window` does not always work 100% of the time. Sometimes yes, but often I've found it will just hang (I'm not entirely sure how to reproduce it deterministically. It may be related to switching between networks or interfaces).

My solution to this is generally to use `Remote: Close Remote Connection` followed by `Remote-SSH: Connect Current Window to Host...`, but this requires that I go dig up the hostname of my remote container again, which is a bit circuitous. Since my container (and as a result, its hostname) changes every few days, I never save them in my ssh config, so they don't show up in the suggested hosts list in the connect dialog either.

**Comment by MarkKahn** [comment]
Adding to this, if you have unsaved files you *have to* abort the automatic reconnect otherwise you lose your files.  Then the only way to save them is to either open an entirely new window and reconnect there or copy-paste your files, reload, copy them back, save...

**Comment by roblourens** [comment]
Remote vscode windows are not designed to operate in a disconnected state, so yes we force reconnection. You should not lose unsaved files, please open a separate issue with more details if that's still an isseu
