### ISSUE TITLE
Open Folder in Container should default to current local path, not remote

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#1204]
If you run **Open Folder in Container...** while inside a container, you see the container's file tree by default.  We used to default to the current local folder instead.  We also are showing your home folder whenever you run this command locally.

The current behavior is confusing - I found it by accidentally selecting a different folder in the vscode-dev-containers repo and then wondering why the right CLIs weren't present.

Repro:
1. Run the **Open Folder in Container** command locally
2. Note that you end up in `~` regardless of the current working directory
3. Pick a folder to open in a container
4. Run the **Open Folder in Container** command again once in a container

**Expected:** You see the current local folder path no matter when you run the command
**Actual:** Local is always `~`, remote is the container path

//cc: @chrmarti

**Comment by chrmarti** [comment]
@alexr00 I have fixed the local case. The remote case somehow changed/broke: I pass in the local folder (file://...) as the defaultUri, but that is not used.

**Comment by alexr00** [comment]
@chrmarti, the uri that comes in in the remote case is file://, so the file picker throws it away because the current context is remote.

**Comment by alexr00** [comment]
Actually, I think we need to define the behavior here. The passed in default URI is currently only used if the scheme matches the current scheme. I did this deliberately because the file dialog should always start in the file system of the current context.

It sounds like in this case there is a desire to override this and instead start in a local file system even when in a remote context. Is that what is wanted here?

**Comment by chrmarti** [comment]
No, I think your previous observation is right. I need to pass in a remote URI.
