### ISSUE TITLE
Error Launching New Terminal

### ISSUE THREAD

**Issue by loganasherjones** [microsoft/vscode-remote-release#129]
- VSCode Version: 1.34.0-insider 473af338e1bd9ad4d9853933da1cd9d5d9e07dc9 x64
- Local OS Version: Ubuntu 18.04
- Remote OS Version: Debian 9.8
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Following the steps here: https://github.com/Azure-Samples/azure-python-labs/tree/master/2a-vscode-flask-dev-container
2. Step 3  causes the error in the image below.
![Screenshot from 2019-05-04 13-43-00](https://user-images.githubusercontent.com/3633332/57184470-1d710880-6e8a-11e9-86e9-115148a6b339.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by proelbtn** [comment]
I caught the same error on my environments, and I found this error occurs because of the settings of terminal in Visual Studio Code.

Visual Studio Code tries to execute the shell which is saved in the same path where your login shell is saved. Given that your login shell is saved in /usr/bin/zsh, Visual Studio Code tries to execute the shell which is saved in /usr/bin/zsh in Docker container. because any shell doesn't exist in this path, you caught an error.

In order to fix this problem, you can add settings for terminal into Docker container.

**

```
{
  "terminal.integrated.shell.linux": "/bin/bash"
}
```

https://code.visualstudio.com/docs/remote/containers#_container-specific-settings

**Comment by Tyriar** [comment]
Duplicate https://github.com/microsoft/vscode-remote-release/issues/38
