### ISSUE TITLE
VS Code Server for WSL failed to start. No messages received for 90s

### ISSUE THREAD

**Issue by satvikpendem** [microsoft/vscode-remote-release#133]
I tried to use the Remote Development extension for WSL but it does not start up, or at least does not connect to the remote server.

- VSCode Version: Code Insiders 1.34 Preview
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Install Remote Development Extension
2. Open `code-insiders .` in wsl.exe

Does this issue occur when all extensions are disabled?: Yes (with all other extensions uninstalled except Remote Development)

**Comment by tengshan2008** [comment]
I have same trouble.
When I use zsh as shell, it is happened, when I return bash, It is OK.
See https://github.com/Microsoft/vscode-remote-release/issues/27

**Comment by satvikpendem** [comment]
Interesting, seems related to zsh then as I also use it. Will it work if I switch to bash and then call zsh within the terminal? I'll try it out.

**Comment by kieferrm** [comment]
@kumrud what shell do you run in wsl?

**Comment by pihug12** [comment]
I had the same problem and I think it was caused by the proxy of my company.

1. I downloaded this file on Windows (can't do it from WSL on my company's devices) : https://update.code.visualstudio.com/commit:473af338e1bd9ad4d9853933da1cd9d5d9e07dc9/server-linux-x64/insider
2. Then in the folder: `python -m http.server 12345`
3. I edited *C:\Users\MyLogin\\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.32.0\scripts\wslDownload.sh*
Changed: 
```
DOWNLOAD_URL="https://update.code.visualstudio.com/commit:$COMMIT/server-linux-x64/$QUALITY"
```
By:
```
DOWNLOAD_URL="http://localhost:12345/vscode-server-linux-x64.tar.gz"
```
4. Then executed this line on WSL : `bash -x /mnt/c/Users/MyLogin/.vscode-insiders/extensions/ms-vscode-remote.remote-wsl-0.32.0/scripts/wslServer.sh 473af338e1bd9ad4d9853933da1cd9d5d9e07dc9 insider .vscode-remote --disable-telemetry`

It now works. 😄

**Comment by satvikpendem** [comment]
I tried it out by switching to bash and it works now. So it might be a zsh issue, or somehow bash isn't able to be called.

**Comment by aeschli** [comment]
Two different issues hit in this issue:
- Problems with zsh: See #27
- Problems downloading the server build from WSL: Issue #79

**Comment by shanehou** [comment]
Add `export http_proxy=http://your-proxy.com:1234` and `export https_proxy=http://your-proxy.com:1234` to your `.bashrc` or `.zshrc` rather than `.profile` will solve the downloading proxy problem.

**Comment by shroomsprite** [comment]
@pihug12 Works for me. Thanks!

**Comment by lucashtc** [comment]
Just in case someone else has a problem similar to mine.
I have set the proxy in /etc/wgetrc

**Comment by pellejacobs** [comment]
Setting proxy variables in /etc/wgetrc did it for me. Thanks @lucashtc!

**Comment by brainlulz** [comment]
In case someone had the problem of the timeout error using zsh, run ```chsh``` and choose zsh instead of adding something in your .bashrc file.
