### ISSUE TITLE
Remote-Containers: Provide view action to open a folder in a container

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#1341]
We should support to create a new container from the Remote Container section. Suggest to add it as a view action as hinted at below

![image](https://user-images.githubusercontent.com/172399/64101229-a8490d80-cd6d-11e9-9414-17faa1a9c6b1.png)

Something like
<img width="200" alt="image" src="https://user-images.githubusercontent.com/172399/68033872-e5277700-fcc0-11e9-813c-665c077f7399.png">

**Comment by alexr00** [comment]
Added the plus sign and picker. Here's what shows when you click the plus:
![image](https://user-images.githubusercontent.com/38270282/68119412-ef38b800-ff02-11e9-8e12-c8616b62539a.png)
I opted not to include a title because most of those commands show a quick pick without a title and it looked weird to go from title to no title

**Comment by chrmarti** [comment]
I suggest to:
- Rename `Reopen in Container` > `Open Current Folder in Container`
- Remove `Add Development Container Config Files...`

**Comment by chrmarti** [comment]
(Filed https://github.com/microsoft/vscode-remote-release/issues/1779 to simplify the flow for running samples.)

**Comment by alexr00** [comment]
Nice suggestion:
![image](https://user-images.githubusercontent.com/38270282/68123546-9a4e6f00-ff0d-11e9-96a5-9d97d27eeef8.png)
