### ISSUE TITLE
visual code does not connect correctlly to WSL 

### ISSUE THREAD

**Issue by FerKreps** [microsoft/vscode-remote-release#1358]
- VSCode Version:
Version: 1.37.0 (system setup)
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T02:33:50.993Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
- OS Version: Windows 10 

Steps to Reproduce:

1. Start Remote-WSL

The terminal logs

code: 'MODULE_NOT_FOUND',
phase: 'loading',
moduleId: 'iconv-lite',

code: 'MODULE_NOT_FOUND',
phase: 'loading',
moduleId: 'applicationinsights',

code: 'MODULE_NOT_FOUND',
phase: 'loading',
 moduleId: 'semver-umd',

code: 'MODULE_NOT_FOUND',
phase: 'loading',
moduleId: 'minimist',

**Comment by aeschli** [comment]
You can configure your proxy settings for wget as described here:
https://www.thegeekdiary.com/how-to-use-wget-to-download-file-via-proxy/

Note that because you are on a 'older' version of WSL (and Windows) we do the download on the WSL side. With Windows 10 1903 we do it on the Windows side. There we know more about proxies. So, updating also could solve your problem.
