### ISSUE TITLE
Problem parser path resolved incorrectly

### ISSUE THREAD

**Issue by anatolyburakov** [microsoft/vscode-remote-release#1623]
Issue Type: <b>Bug</b>

I have a source tree at `/home/anatoly/DPDK` and a build tree at `/home/anatoly/build/DPDK`. My build task looks like this:

```
                {
                        "label": "Build meson default",
                        "type": "shell",
                        "command": "ninja",
                        "problemMatcher": ["$gcc"],
                        "group": {
                                "kind": "build",
                                "isDefault": true,
                        },
                        "options": {
                                "cwd": "${workspaceFolder}/../build/${workspaceFolderBasename}/"
                        }
                }
```
So, the build's cwd is set to the build root.

Whenever compile issues happen with the build tree, the compiler will point to the source files, like this:

```
../../DPDK/lib/librte_eal/linux/eal/eal.c: In function ‘rte_eal_config_reattach’:
../../DPDK/lib/librte_eal/linux/eal/eal.c:435:9: warning: unused variable ‘b’ [-Wunused-variable]
  int a, b;
         ^
```
the above should resolve to `/home/anatoly/DPDK/<snip>/eal.c`. However, it actually resolves to `/home/DPDK/<snip>/eal.c`. This is because the problem matcher resolves the path from the source tree (`/home/anatoly/DPDK`) not the build tree (`/home/anatoly/build/DPDK`), which results in `/home/anatoly/DPDK/../../DPDK/<snip>/eal.c` rather than `/home/anatoly/build/DPDK/../../DPDK/<snip>/eal.c`.

This is the error given by VSCode:

```
Unable to open 'eal.c': Unable to read file (Error: File not found (vscode-remote://ssh-remote+7b22686f73744e616d65223a2242616c6c7a227d/home/DPDK/lib/librte_eal/linux/eal/eal.c)).
```

(see this for context: https://github.com/microsoft/vscode-cpptools/issues/407)

Extension version: 2019.10.5728
VS Code version: Code - Insiders 1.39.0-insider (695ee74864ef93d10f5de0861cb66af190e76211, 2019-10-02T08:56:48.092Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.15.0-65-generic

**Comment by egamma** [comment]
The C++ team suspects that this is a VS Code Remote bug. 

@anatolyburakov can you please provide a minimal github repository so that we can reproduce the issue.

**Comment by yeggles** [comment]
@egamma @anatolyburakov 
I am running into this same issue.  From what I can tell the whole issues is the fact that the problemMatcher is adding the "vscode-remote://ssh-remote+<some hash>" to the front of the file path which I would think is where the file lives that is relative to my Windows PC since it is the one running VS Code.  But after the Remote-SSH connection has been made the file path needs to be relative to the VM's directory and not have the "vscode-remote://ssh-remote+<hash>" on the front.  I don't know who creates the links whether it is the problemMatch (gcc for my case) or remote-ssh, but whomever it is, is the one responsible for the issue.

If I use the following, then "some" of my files will open correctly when I click on the errors because the prefix listed above is not present:

`
"problemMatcher":
{
	"base": "$gcc",
	"fileLocation": "relative"
}
`

I say "some" because I am also running into issues where the problem matcher is tracking where my make files lives in relativity to my workspaceFolder.  For instance if I had the following workspace structure:  workspaceFolder/A/B and inside B there was a Makefile.  If I call make on root/A/B/Makefile, then all of the errors that occur due to that call will link to root/B/* and forget that there was an A directory in the path.  I hope that all makes sense.

**Comment by yeggles** [comment]
I deleted my comment since this issue appeared to be most relevant to what I am seeing:
[https://github.com/Microsoft/vscode-cpptools/issues/2266](url)

**Comment by anatolyburakov** [comment]
This is not a bug, problem parser needs to use relative paths.
