### ISSUE TITLE
Remote - SSH : PATH in task different from terminal

### ISSUE THREAD

**Issue by psolyca** [Microsoft/vscode-remote-release#167]
- VSCode Version: 1.34.0-insider (user setup)
- Local OS Version: Windows 7 Pro (Windows_NT x64 6.1.7601)
- Remote OS Version: Linux 4.4.0-145-generic Ubuntu 16.04.6 LTS
- Remote Extension/Connection Type: SSH

After connecting to the server, in a bash terminal the PATH variable is correctly set but when I use a task to build my app, the PATH variable is different.  
The PATH variable is set in .bashrc and .profile files to add a specific path which does not appear when building.

All environnement variables are the same except the PATH and LS_COLOR.

**Comment by egamma** [comment]
@psolyca when you run tasks, then the command shell is not started as an interactive shell, therefore the path can differ. This is by design so that environment variables can be overridden, pls see https://github.com/Microsoft/vscode/issues/27185#issuecomment-343126048.

Also this is not vscode-remote specific. 

//fyi @dbaeumer

**Comment by psolyca** [comment]
Thanks.

I was focused on vscode-remote and not vscode.
