### ISSUE TITLE
Failure running devcontainer as non-root user

### ISSUE THREAD

**Issue by Rots** [microsoft/vscode-remote-release#1685]
- VSCode Version: 1.39.2
- Local OS Version: Linux Mint 19.2
- Name of Dev Container Definition with Issue:

Steps to Reproduce:

1. Run a devcontainer  based on local docker-compose.yml
* The Dockerfile has only `root` user
* in the `.devcontainer/docker-compose.yml` I added
`    user: 1000:1000`

Expected: dev environment opened in the container
Actual: startup fails with permission issues:

```
Run: docker-compose --project-name dwww -f /home/rots/Projects/OP/dwww/docker-compose.yml -f /home/rots/Projects/OP/dwww/.devcontainer/docker-compose.yml up -d
Starting dwww_web_1 ... done
Starting dwww_db_1    ... done
Starting dwww_proxy_1 ... done
Forking shutdown monitor: /home/rots/.vscode/extensions/ms-vscode-remote.remote-containers-0.81.0/dist/shutdownMonitorProcess /run/user/1000/vscode-remote-containers-f4df7852963304c55f87fab34d59739cd79798d9.sock dockerCompose no-trace
Run: docker exec 487119d1eb53e11ce7e211634226017eed5b7e65db280e44d90b719acc8f2997 /bin/sh -c (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
Run: docker cp 487119d1eb53e11ce7e211634226017eed5b7e65db280e44d90b719acc8f2997:/etc/passwd -
Run: docker exec 487119d1eb53e11ce7e211634226017eed5b7e65db280e44d90b719acc8f2997 test -d /root/.vscode-server
Run: docker exec 487119d1eb53e11ce7e211634226017eed5b7e65db280e44d90b719acc8f2997 test -d /root/.vscode-remote
Run: docker exec 487119d1eb53e11ce7e211634226017eed5b7e65db280e44d90b719acc8f2997 /bin/sh -c set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
mkdir: cannot create directory '/root': Permission denied
Run: docker exec 487119d1eb53e11ce7e211634226017eed5b7e65db280e44d90b719acc8f2997 /bin/sh -c set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.copyGitConfigMarker' ; } 2> /dev/null
mkdir: cannot create directory '/root': Permission denied
Run: docker exec 487119d1eb53e11ce7e211634226017eed5b7e65db280e44d90b719acc8f2997 test -d /root/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390
Installing VS Code Server for commit 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Run: docker exec 487119d1eb53e11ce7e211634226017eed5b7e65db280e44d90b719acc8f2997 mkdir -p /root/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390_1571268628566
mkdir: cannot create directory '/root': Permission denied
Command failed: docker exec 487119d1eb53e11ce7e211634226017eed5b7e65db280e44d90b719acc8f2997 mkdir -p /root/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390_1571268628566
```

### Proposed solution:
I think an easy fix is to run the `docker exec` commands always with `--user root` regardless of which user is used for development (configured in `docker-compose.yml`).

**Comment by Chuxel** [comment]
@Rots Actually these are intended to all go into the non-root user's home folder.  The extension should be using the user specified unless it doesn't actually exist in the container.  

Did you also add a non-root user to the container image?   Just adding "user: 1000:1000" is not enough, it has to actually exist inside the cotnainer. 

See here: https://code.visualstudio.com/docs/remote/containers-advanced#_adding-a-nonroot-user-to-your-dev-container

**Comment by Rots** [comment]
Yes I read the section before posting this...
> For images that only provide a root user, you can automatically create a non-root user by using a Dockerfile. (example following)
That is quite confusing wording though...

Isn't the point of reusing existing Dockerfile to use it for multi purpose? I don't like the idea of having to maintain an extra `Dockerfile` just for devcontainer. I already have the `.devcontainer/docker-compose.yml` and `devcontainer.json`. Should there then maybe be a local `.devcontainer/Dockerfile` as well?

Can I specify the target folder with an environment variable so I can add it in `.devcontainer/docker-compose.yml` to point to `/tmp/.devcontainer`?

**Comment by Chuxel** [comment]
@Rots All of this is somewhat scenario specific depending on what exactly you are trying to do. 
 Generally the recommendation is to run non-root even in production to avoid potential security issues. Base images stick with root to make it easy to install additional software in another Dockerfile.  Some base images like `node` actually ship with a non-root user because of exactly this scenario.

So, if you are in a situation where you want to be able to run as root as well, you can mirror what these base images do. You add the non-root user into the Dockerfile but don't add the `USER` directive.  (The sudo part is even optional if you don't intend to install anything.)  This leaves the default in the container as root.  The `user: 1000:1000` would then change it in this specific scenario. 

However, generally there's some things we could do to make this less painful for existing containers.  While we have "postCreateCommand" in devcontainer.json to allow you to fire scripts to install additional software, this happens too late for user creation. As a result, there is a feature request on auto-generating and using the an in-container non-root user based on your local one that you can upvote: https://github.com/microsoft/vscode-remote-release/issues/1155

**Comment by Rots** [comment]
Thank you.

As a workaround, I was able to run the container by editing `.devcontainer/docker-compose.yml`:
```
    environment: 
      HOME: "/tmp"
```
or alternatively
```
volumes:
     - /tmp:/root

```

#1155 would somewhat ease this pain, I do see a number of buts though...
As the default commented out value for `postCreateCommand` suggest
> #"postCreateCommand": "apt-get update && apt-get install -y git",

we would still want to keep the ability to run additional commands as root, right?

Anyway, I still believe the experience can be streamlined with `--user root` option at least for `postCreateCommand`. For now I have to do it manually via external terminal to install the additional dev tools in the container.

**Comment by Chuxel** [comment]
@Rots We recommend using sudo to cover that case which is why the non-root article includes it (as does the section on [sharing SSH keys](https://code.visualstudio.com/docs/remote/containers#_using-ssh-keys)).

Otherwise there's also some discussion of allowing separating the user that started the container from the user that connects to the container in #538.

**Comment by Rots** [comment]
Great, that's exactly what I have been looking for. Close as duplicate of #538
