### ISSUE TITLE
Opening a public repository in a container does not clone recursively

### ISSUE THREAD

**Issue by jumaffre** [microsoft/vscode-remote-release#1710]
Following https://code.visualstudio.com/docs/remote/containers#_quick-start-open-a-public-git-repository-in-an-isolated-container-volume, using a `devcontainer.json` file in a repository that contains submodules works fine, except that the repository is not cloned with `--recursive`. 

This means that once the container is running, one needs to run `git submodule update --recursive --init`, which is not optimal.

I believe that `devcontainer.json` should support an option to tell vscode-remote that the repository contains submodule(s) and.or clone the repo with `--recursive` automatically.

**Comment by egamma** [comment]
We could add a `recursive` option in the devcontainer.json file that runs `git submodule update --recursive --init` when the container is created. However, this is almost the same functionality as is already provided by the `postCreateCommand`. Therefore, the recommendation is to call `git submodule update --recursive --init` from the `postCreateCommand`.

**Comment by ereOn** [comment]
@egamma Except that calling `git submodule update --init` hangs forever when run from the `postCreateCommand` in some case.

It doesn't hang when run from the same terminal. I suspect HTTP proxy issues, or SSH passphrase issues but it is impossible to investigate, as there are no logs available since the command just hangs forever.
