### ISSUE TITLE
Performance issues - high CPU usage: multiple "orphan" executions of the extension, each consuming about 10% CPU (i7-8550u)

### ISSUE THREAD

**Issue by gsusI** [microsoft/vscode-remote-release#1728]
- VSCode Version: 1.39.2
- Local OS Version: 10.0.18975
- Remote OS Version: Ubuntu 18.04.3 LTS
- Remote Extension/Connection Type: SSH Tunnel + Docker 

Steps to Reproduce:

This is pretty much my code: https://github.com/gsusI/vscode-remote_dev-config_test.

It happens over a wide period of time, I believe it's caused by playing with the configuration and therefore using several times the options Reload Window and Rebuild in container.

The problem continues after closing the VSCode window using the extension (whilst keeping others opened), and even after disabling the extension. Only option has been to kill the orphan processes from the Task Manager.

![image](https://user-images.githubusercontent.com/4558016/67562809-57271b80-f717-11e9-967d-ab39f46eab12.png)

Now, trying to reproduce the error by generating a faulty config file (specifically workspaceMount & docker-compose volumes) , so it causes an "Error setting up the container", I got this situation:

![image](https://user-images.githubusercontent.com/4558016/67562817-5a220c00-f717-11e9-920e-a24e3f52edaa.png)
Error:
![image](https://user-images.githubusercontent.com/4558016/67562822-5e4e2980-f717-11e9-872c-b9086a4e2cbc.png)

Does this issue occur when you try this locally?: Unsure
Does this issue occur when you try this locally and all extensions are disabled?: Unsure

**Comment by gsusI** [comment]
For some reason my first image was overwride by the second one, here it goes:

![image](https://user-images.githubusercontent.com/4558016/67562777-4b3b5980-f717-11e9-872d-f12d66830198.png)

**Comment by gsusI** [comment]
Another screenshot from Task Manager:
![image](https://user-images.githubusercontent.com/4558016/67563000-bab14900-f717-11e9-81f2-4c2ea6a5115a.png)

**Comment by gsusI** [comment]
I'm starting to think that the key to reproduce is use the "Reload window".

**Comment by JohnGalt1717** [comment]
So I have similar. Vmmem starts using 25% of cpu while debug sessions under Chrome are idle.  C# debug does not cause the same thing (uses about 5% cpu while debugging doing nothing which is still more than it should but not crazy) and the angular project just sitting doing nothing other than code editing doesn't do it either. Just Chrome Debug.

This does **not** happen when debugging locally.

Also, there are multiple code.exe orphans left in details under Task Manager even after closing all instances of code.

The fan on my Precision 5340 is driving me nuts because of this.
