### ISSUE TITLE
can't add devcontainer.json to folder on windows

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode-remote-release#1763]
Version: 1.40.0-insider (system setup)
Commit: b7b21844e760e632f39bedf651da2bc93f54b0cc
Date: 2019-10-29T06:48:38.866Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19008

On Windows, create an empty folder and run command: Add Development container configuration file. Select Python3 configuration and reopen in container.  Fails to create the devcontainer because of a binding issue. I don't run into this when I tried on my Mac.

![image](https://user-images.githubusercontent.com/9721254/67908953-a1a30080-fb3a-11e9-9cbf-8bfc2b12a5cc.png)

**Comment by sana-ajani** [comment]
@chrmarti @Chuxel

**Comment by Chuxel** [comment]
@sana-ajani Typically this is because you haven't given Docker permission to access the drive your source code is on.  Mac's defaults give docker wide permissions which is why you don't see it there.  

If it's already shared, I've also seen it stop working with a password change and you have to re-share. Try un-checking and re-checking the drive in the docker settings.

If that doesn't do it see if the [tips in troubleshooting help](https://code.visualstudio.com/docs/remote/troubleshooting#_docker-desktop-for-windows-tips).

**Comment by sana-ajani** [comment]
@Chuxel Yeah, I was logged in with my AAD account and went through these steps to get it working: https://blogs.msdn.microsoft.com/stevelasker/2016/06/14/configuring-docker-for-windows-volumes/

Thanks!
