### ISSUE TITLE
Remote SSH requiring me to input my password twice

### ISSUE THREAD

**Issue by rmw1075** [microsoft/vscode-remote-release#1772]
Every time I try to SSH into my server, it prompts me twice for my password, even if I typed it correctly the first time. It also has me do this every time I change directories, which both Putty and the terminal do not.

Log output when I tried to log in and it prompted me for my password twice. Both times I typed in my correct password.

```
[14:12:46.926] Running script with connection command: ssh -T -D 41945 -o ConnectTimeout=15 **MYSERVERNAME** bash
[14:12:46.926] Install and start server if needed
[14:12:47.183] > Password:
[14:12:47.183] Got some output, clearing connection timeout
[14:12:47.184] Showing password prompt
[14:12:54.207] Got password response
[14:12:54.208] "install" wrote data to terminal: "********************"
[14:12:54.214] > 
[14:12:54.280] > Password:
[14:12:54.280] Showing password prompt
[14:13:00.401] Got password response
[14:13:00.402] "install" wrote data to terminal: "********************"
[14:13:00.443] > 
[14:13:02.979] > **redacted**: running
```

- VSCode Version: 1.39.2
- OS Version: Ubuntu 18.04.3 **AND** Windows 10

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Weird. That is the direct output from ssh. And this doesn't happen if you just run `ssh hostname` from a terminal?

> every time I change directories

That is expected. VS Code has to reestablish the connection.

**Comment by rmw1075** [comment]
If I ssh from either the Windows command line or the Linux terminal, I am only prompted once.

**Comment by justinh00k** [comment]
I too have to enter a password again when choosing a directory. Can I specify a directory in the host so I only have to enter the password (for the SSH key) once?

**Comment by roblourens** [comment]
Not currently.

@rmw1075 I have changed the way auth works, and I would be very curious if this works for you in the nightly version of the extension. If not, then I am stumped :)

**Comment by JosephTLyons** [comment]
The double password thing is a double whammy when coupled with the fact that VS Code SSH still doesn’t have support for saving passwords.  The icing on the cake is when you get disconnected from a server and the “reconnect” button fails to work every single try, forcing you to reload the window.  I spend quite a bit of time just reloading windows and typing the password in multiple times.

I love this tool, it just has some rough edges and I worry they will not be smoothed.

Another annoyance is having to use a new windows for each new SSH session.  Would be phenomenal if you could manage multiple ones within one instance of VS Code.

**Comment by roblourens** [comment]
@JosephTLyons This issue was about getting two password prompts for a single window, I'm guessing that you are just seeing a password prompt for every window. This is improved in the nightly version of the extension, where a single connection can be shared between windows, you should try it out. And if you still see it with the nightly extension, I'd appreciate if you open a new issue with reconnect failing with the log from the Remote-SSH output channel, and I can see whether there's anything I can do to improve that.

I'm going to close this issue as it seems stale.

**Comment by JosephTLyons** [comment]
Really appreciate not having to put in the password twice now.  Huge improvement and massive workflow boost.  Was it added that the password doesn't need to be entered again when reloading the window?  I can't recall what the previous behavior was, but I don't have to put in a password when reloading the VS Code window, which is excellent.  Thanks for the great updates.

**Comment by roblourens** [comment]
Yes, that is the "local server mode" which is on my default.

Just a heads up, if you are using windows, I will probably be turning that off by default in a few days due to some other issues, so if it works for you you can make sure it stays on by setting `"remote.SSH.useLocalServer": true`. If you are not on Windows, you can ignore that.
