### ISSUE TITLE
Can't connect through jumpbox

### ISSUE THREAD

**Issue by Stephen9s** [microsoft/vscode-remote-release#18]
Some users may leverage ~/.ssh/config to set up ProxyJump and ProxyCommands to get to their endpoints. Currently, it appears that VSCode Remote only supports a direct connection.

**Comment by tralston** [comment]
I'm able to connect to a JumpHost endpoint. Mine are configured in my config file. The only thing I had to do was copy my SSH key to the remote endpoint (and jump hosts). For example, if my config was:
```local -> jump1 -> jump2 -> server```
Then I'd have to run "ssh-copy-id" for jump1, then for jump2, then for server. After that, VSCode connected just fine.

**Comment by TheStoof** [comment]
I am able to do the same, but what I found was that I could do the following:

local -> server = OK
local -> jump1 -> server = able to authenticate, but unable to connect. 

I do know that when VSC connects to the remote server, it attempts to install or run a service. My suspicion is that by jumping through from X to Y to Z, the service ends up installing on Y and not X. Perhaps maybe there’s a better way to pivot using JumpHost as you said rather than ProxyCommand. 

I’ll give ProxyJump a shot.

**Comment by tralston** [comment]
@TheStoof for what it's worth, here's an excerpt from my config file (sanitized):

```
host jump1-alias
  HostName jump1
  User myUser
  Port 2202

host server-alias
  HostName server
  User myUser
  Port 2202
  ProxyCommand ssh -W %h:%p jump1-alias
```

**Comment by tralston** [comment]
@TheStoof I just attempted the same connection, but from a Windows 10 machine with WSL, and it didn't work (same problem as #34). It did work though from my Mac.

**Comment by msalvaris** [comment]
Yea, tried various options and nothing succesful to far. I was able to connect once by creating a tunnel in WSL and pointint the Hostname and Port to the tunnel but wasn't able to repeat.

**Comment by pd93** [comment]
Ran into this issue while trialing Remote SSH as an alternative to local development. Connecting from a Windows 10 machine to a remote box works, but only when connecting directly. We cannot connect to any hosts via a jumpbox. In other words:

- `local -> jumpbox` works
- `local -> jumpbox -> remote` doesn't work

Here's my (sanitized) config:

```conf
Host myjumpbox
    HostName    12.34.56.78
    Port        22
    User        user

Host remote
    Hostname    172.16.0.1
    Port        22
    User        user
    ProxyJump   jumpbox
```

There is no way of directly SSHing to `remote` without using a jumpbox, so this functionality it absolutely necessary for us to use Remote - SSH.

**Comment by LeuisKen** [comment]
I'm trying to solve this issue by writing a new `RemoteAuthorityResolver`, which the `Remote SSH` and `Remote Container` based on. But there is no document about this API...

**Comment by suanrong** [comment]
Anyone solve this issue?

**Comment by msalvaris** [comment]
@suanrong 
> 
> 
> Anyone solve this issue?

I was able to overcome the issue by using this method
https://github.com/microsoft/vscode-remote-release/issues/117

I create the proxy in wsl and simply make sure that my ssh config points to localhost and the correct port.

**Comment by pd93** [comment]
I decided to try SSHing (with the same config as above) to my remote boxes via Powershell today. This should use the same version of SSH as the Remote - SSH extension (rather than the WSL version of SSH). 

Unsurprisingly, I got exactly the same result, but a better error message

- `local -> jumpbox` works
- `local -> jumpbox -> remote` fails with the error: 

```
CreateProcessW failed error:2
posix_spawn: No such file or directory
```

A quick search of the error found https://github.com/PowerShell/Win32-OpenSSH/issues/1185.
Not 100% sure if related, but that issue was fixed in Jan which implies that if that issue is the problem, this would be fixed in 1903. Unfortunately, we're still on 1809 at work, so I can't test.

**Comment by axiqia** [comment]
I have copyed my SSH key to the remote endpoint and jump hosts as @tralston suggested. But I still met the issue like @pd93 .  I added more information.

**My config:**
```
Host jumpbox
    HostName example.edu.cn
    User U
    Port xxx
    IdentityFile xxx.id_rsa


Host remote
    HostName remote
    User U
    Port xx
    ProxyCommand ssh -q -W %h:%p jumpbox
``` 

## **On Powershell:**
```
ssh -V
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
```

- `local -> jumpbox` **works**
```
ssh jumpbox
```
- `local -> jumpbox -> remote` **fails** with the error:
```
ssh remote
CreateProcessW failed error:2
posix_spawn: No such file or directory
```

## **On ssh via git bash(windows)**
```
$ ssh -V                                                                         
OpenSSH_7.9p1, OpenSSL 1.1.1a  20 Nov 2018
```

- `local -> jumpbox` **works**
```
ssh jumpbox
```
- `local -> jumpbox -> remote` **works**
```
ssh remote
```

## **On VS Code:**
- `local -> jumpbox` **works**
- `local -> jumpbox -> remote` **fails** with the error:
```
Picking SSH host
Selected remote
Confirming that remote is a valid reachable host
Running type "C:\Users\xxx\AppData\Local\Temp\vscode-linux-multi-line-command-remote.sh" | ssh  "remote" bash to confirm the host platform
> 
> CreateProcessW failed error:2
> posix_spawn: No such file or directory
> 
"uname" terminal command done
remote: unreachable or not Linux x86_64. (posix_spawn: No such file or directory)
```

**Comment by johnymachine** [comment]
Maybe this could help:

`ProxyCommand  C:\Windows\System32\OpenSSH\ssh.exe jumphost netcat -w 120 %h %p`

https://serverfault.com/questions/956613/windows-10-ssh-proxycommand-posix-spawn-no-such-file-or-directory

**Comment by davesdig** [comment]
Seeing same problem here when trying to connect to Centos 7 via a Centos 7 jump box from a mac.  Tried several forms of ProxyCommand and ProxyJump.  Can connect thru proxy to target from command line so the configuration should be good.  Keys are set up on both jump box and target box.  

Code Version: 1.35.0
Extension Version: 0.42.0

**Comment by Higher-Stark** [comment]
I encountered `CreateProcessW failed error:2  posix_spawn: No such file or directory` on my __Windows 10 1903__. The `ProxyCommand` in my config is `ProxyCommand ssh jumphost -W %h:%p`.
Then I change the command to `ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe jumphost -W %h:%p`, and it just works.

@johnymachine I tried yours, but I got `bash: netcat: command not found`. 
I am not going to look into the error, I'd appreciate it if you let me know the why this happens.

OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
Windows 10 - 1903

**Comment by johnymachine** [comment]
> I encountered `CreateProcessW failed error:2 posix_spawn: No such file or directory` on my **Windows 10 1903**. The `ProxyCommand` in my config is `ProxyCommand ssh jumphost -W %h:%p`.
> Then I change the command to `ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe jumphost -W %h:%p`, and it just works.
> 
> @johnymachine I tried yours, but I got `bash: netcat: command not found`.
> I am not going to look into the error, I'd appreciate it if you let me know the why this happens.
> 
> OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
> Windows 10 - 1903

Sorry my bad, I probably copied bad command. 

My config is exactly this and it works:
`ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -W %h:%p -q user@ipaddr`

**Comment by axiqia** [comment]
`ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -W %h:%p -q user@ipaddr`
@johnymachine Thank you. That works for me on my windows platform.

**Comment by axiqia** [comment]
`ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -W %h:%p -q user@ipaddr`
@johnymachine Thank you. That works for me on my windows platform.

**Comment by asmitde** [comment]
@johnymachine Thanks for the solution! Do you know how to how to run the proxy ssh process in the background? There's a blank ssh process window that stays open as long as the connection is active.

**Comment by johnymachine** [comment]
Well 😀

Here Is my question on stackoverflow:

https://stackoverflow.com/questions/56477585/can-i-somehow-suppress-empty-window-with-ssh-exe-when-using-remote-development-e

No luck so far...

**Comment by pd93** [comment]
Thought I'd post a little update to this issue for those who run into it.

The root cause of this issue is a [bug with OpenSSH for windows](https://github.com/PowerShell/Win32-OpenSSH/issues/1172). However, this has now been [patched in the latest release (v8.0.0.0)](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v8.0.0.0p1-Beta).

Unfortunately, this likely [won't get built into Windows until 1909 comes around](https://github.com/PowerShell/Win32-OpenSSH/issues/1411#issuecomment-505095002). However, you can manually patch it yourself!

# Manual Fix

- Download the [v8.0.0.0 release `.zip`](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v8.0.0.0p1-Beta).
- Extract the `.zip` file
- Copy and replace the extracted `ssh.exe` binary into your `C:\Windows\System32\OpenSSH` folder.
- Done! You can now use "Remote Development - SSH" with `ProxyJump` in the expected way.

If you get a permissions error then this may be because there is system protection in place on the existing `ssh.exe` binary. This can be removed by setting yourself as the owner of the file (requires admin) and granting yourself "full control". To do this, follow these steps:

- Right-click on the existing file `C:/Windows/System32/OpenSSH/ssh.exe` and select `Properties`.
- Open the `Security` tab and click on `Advanced`.
- Click the button to change the owner and change it from `TrustedOwner` to your Windows username.
- Type your username and click the `Check Names` button (This should autofill with your full username/email).
- Apply the settings and then close the properties window and reopen it.
- Navigate back to the `Security` tab and click on `Edit`.
- Select the `Users` group and give the group `Full Control`.
- Click `Apply` and exit.
- Now go back and try patching the file again.

**Note:** This does not fix the blank terminal from appearing when creating a new Remote SSH session. I have created a [new issue for this](https://github.com/microsoft/vscode-remote-release/issues/872).

**Comment by HsunGong** [comment]
https://github.com/microsoft/vscode-remote-release/issues/18#issuecomment-507258777 This give a good reply and this issue can be closed.

**Comment by jkurlandski01** [comment]
I thought I was having the issue described here until I discovered this Stack Overflow page: https://stackoverflow.com/questions/57289351/is-it-possible-to-create-a-proxy-in-remote-ssh-visual-studio-code?
Following the example completely resolved my problem.

**Comment by yixuanren** [comment]
> Maybe this could help:
> 
> `ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe jumphost netcat -w 120 %h %p`
> 
> https://serverfault.com/questions/956613/windows-10-ssh-proxycommand-posix-spawn-no-such-file-or-directory
> 
> It worked as expected on Windows 10 1809 but there is probably bug in 1903 and this worked for me.

I tried yours and succeeded. Basically it looks like we only need to replace the executable from `ssh` on Linux to some `ssh.exe` (maybe with path) on Windows in our original commands. The other parts/params can just remain whatever they were.

**Comment by polakpe7** [comment]
Easy workaround: just install git bash and remove OpenSSH from Path.

**Comment by johnymachine** [comment]
> Thought I'd post a little update to this issue for those who run into it.
> 
> The root cause of this issue is a [bug with OpenSSH for windows](https://github.com/PowerShell/Win32-OpenSSH/issues/1172). However, this has now been [patched in the latest release (v8.0.0.0)](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v8.0.0.0p1-Beta).
> 
> Unfortunately, this likely [won't get built into Windows until 1909 comes around](https://github.com/PowerShell/Win32-OpenSSH/issues/1411#issuecomment-505095002). However, you can manually patch it yourself!
> 
> # Manual Fix
> * Download the [v8.0.0.0 release `.zip`](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v8.0.0.0p1-Beta).
> * Extract the `.zip` file
> * Copy and replace the extracted `ssh.exe` binary into your `C:\Windows\System32\OpenSSH` folder.
> * Done! You can now use "Remote Development - SSH" with `ProxyJump` in the expected way.
> 
> If you get a permissions error then this may be because there is system protection in place on the existing `ssh.exe` binary. This can be removed by setting yourself as the owner of the file (requires admin) and granting yourself "full control". To do this, follow these steps:
> 
> * Right-click on the existing file `C:/Windows/System32/OpenSSH/ssh.exe` and select `Properties`.
> * Open the `Security` tab and click on `Advanced`.
> * Click the button to change the owner and change it from `TrustedOwner` to your Windows username.
> * Type your username and click the `Check Names` button (This should autofill with your full username/email).
> * Apply the settings and then close the properties window and reopen it.
> * Navigate back to the `Security` tab and click on `Edit`.
> * Select the `Users` group and give the group `Full Control`.
> * Click `Apply` and exit.
> * Now go back and try patching the file again.
> 
> ## Blank terminal issue
> Note that this does not fix the blank terminal from appearing when creating a new Remote SSH session. ~I have created a [new issue for this](https://github.com/microsoft/vscode-remote-release/issues/872).~
> 
> -- edit --
> 
> See #230 (this is now fixed)

Seems like new Win32-OpenSSH did not mke it to 1909? Currently on Win 1909 and Win32-OpenSHH 7.7.2.1.

**Comment by pd93** [comment]
> Seems like new Win32-OpenSSH did not make it to 1909? Currently on Win 1909 and Win32-OpenSHH 7.7.2.1.

Yeah, I noticed this recently too :/ Kind of a shame tbh - I'd really like to stop patching this on work machines at some point. @manojampalam are you able to comment on this at all?

Would be fantastic if this could be delivered via cumulative update, so enterprise users don't need to wait another 12 months+ to upgrade to Win 2009 or whatever its going to be called (confusing naming scheme!).

**Comment by Kurt-Shiwz** [comment]
our company use jumpserver(https://github.com/jumpserver/jumpserver),i failed.
![image](https://user-images.githubusercontent.com/7554917/70324053-71512f00-1869-11ea-86bb-5313c3af56e2.png)
![image](https://user-images.githubusercontent.com/7554917/70324143-a8274500-1869-11ea-877d-01af83521ffd.png)

**Comment by xgdgsc** [comment]
I have all linux machines on the route.  But it fails with:
```
[17:36:53.965] > Could not open a connection to your authentication agent.
> ssh_exchange_identification: Connection closed by remote host
[17:36:53.965] Got some output, clearing connection timeout
```
running ssh CONFIG_NAME directly in terminal works.

**Comment by pd93** [comment]
@roblourens I know this isn't directly related to VSCode, but it **is** directly impacting it. Our small team has been using VSCode Remote Dev since its release and we're really enjoying it, but we wouldn't feel comfortable having to patch 100s of instances of SSH just to work this way across other teams.

Is there any way to nudge the Windows 10 / OpenSSH guys regarding https://github.com/PowerShell/Win32-OpenSSH/issues/1172? Not much activity over there and it seems like noone has an answer as to when an upgraded version of OpenSSH will make it into Windows 10.

My personal feeling is that OpenSSH updates should be included in cumulative updates to ensure that security patches and bugs like this are ironed out ASAP. Most companies only update their OS on a yearly basis (and that's only if they followed the recommended guidance). Yearly updates to something like SSH seems highly inadequate.

**Comment by taseikyo** [comment]
> Maybe this could help:
> 
> `ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe jumphost netcat -w 120 %h %p`
> 
> https://serverfault.com/questions/956613/windows-10-ssh-proxycommand-posix-spawn-no-such-file-or-directory
> 
> It worked as expected on Windows 10 1809 but there is probably bug in 1903 and this worked for me.

Thanks! Using ssh's full path worked for me :3

```bash
× ProxyCommand ssh -W %h:%p jumpnode
√ ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -W %h:%p jumpnode
```

**Comment by alan23273850** [comment]
> > I encountered `CreateProcessW failed error:2 posix_spawn: No such file or directory` on my **Windows 10 1903**. The `ProxyCommand` in my config is `ProxyCommand ssh jumphost -W %h:%p`.
> > Then I change the command to `ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe jumphost -W %h:%p`, and it just works.
> > @johnymachine I tried yours, but I got `bash: netcat: command not found`.
> > I am not going to look into the error, I'd appreciate it if you let me know the why this happens.
> > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
> > Windows 10 - 1903
> 
> Sorry my bad, I probably copied bad command.
> 
> My config is exactly this and it works:
> `ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -W %h:%p -q user@ipaddr`

@johnymachine 's solution works for me! Great!

**Comment by pd93** [comment]
Hi All, 

A quick update regarding the inclusion of the latest version of OpenSSH in Windows 10.
[See comment](https://github.com/PowerShell/Win32-OpenSSH/issues/1515#issuecomment-586038270) in a different OpenSSH issue.

> We are shipping OpenSSH V8.1 in next windows release that might be available in July 2020.

This will fix the usage of the `ProxyJump` keyword! In the mean time, you can follow the instruction in [my earlier post](https://github.com/microsoft/vscode-remote-release/issues/18#issuecomment-507258777) to manually update to a working version.

**Comment by JustinGrote** [comment]
@pd93 @roblourens Not sure if this is related but I tried using an SSH tunnel via ngrok and I got the "Failed to parse remote port from server output" issue even on 8.1.

Is this a supported scenario or do I have to do the jumpbox method?

```
[17:55:01.210] stderr> OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2
[17:55:02.159] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:ubsZl1Q9SjOlzifmMqGd/w8m95rTpUtsSeRL2FJgMh4
[17:55:03.703] stderr> Authenticated to 0.tcp.ngrok.io ([3.19.114.185]:19084).
[17:55:04.411] stderr> shell request failed on channel 2
[17:55:04.423] > local-server> ssh child died, shutting down
[17:55:04.433] Local server exit: 0
[17:55:04.434] Received install output: OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:ubsZl1Q9SjOlzifmMqGd/w8m95rTpUtsSeRL2FJgMh4
Authenticated to 0.tcp.ngrok.io ([3.19.114.185]:19084).
shell request failed on channel 2

[17:55:04.434] Stopped parsing output early. Remaining text: OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2debug1: Server host key: ecdsa-sha2-nistp256 SHA256:ubsZl1Q9SjOlzifmMqGd/w8m95rTpUtsSeRL2FJgMh4Authenticated to 0.tcp.ngrok.io ([3.19.114.185]:19084).shell request failed on channel 2
[17:55:04.435] Failed to parse remote port from server output
[17:55:04.436] Resolver error: 
[17:55:04.438] ------
```

**Comment by JustinGrote** [comment]
If I turn off "Use Local Server" it gets further and installs the server and starts it, and I can see it running as node on the remote system, however, it just hangs here and never connects. If I turn off "Use Local Server" it doesn't get past the remote port parsing again.

```
vscode-server already installed. Skipping download...
vscode-server with 3943d614597f9f7c384846613d417e97ea6d5ab4 is already running.
61359013d8ae: start
agentPort==2728==
osReleaseId==windows==
osVersion==6.3.9600==
arch==x64==
platform==windows==
61359013d8ae: end
Install script is 680, watching sshd parent 3396
```

**Comment by roblourens** [comment]
@JustinGrote I honestly don't know about your scenario - could you open a new issue with the full log, and some more details about what you're doing?

**Comment by JustinGrote** [comment]
@roblourens I just found my problem is #25, I'll continue it there.

**Comment by bagajjal** [comment]
@JustinGrote , @roblourens  - If it's a OpenSSH issue then please create an issue [here](https://github.com/PowerShell/Win32-OpenSSH/issues)

**Comment by bagajjal** [comment]
Please provide the detailed repro steps isolating the vscode environment (Just using ssh client and sshd server).

**Comment by JustinGrote** [comment]
@bagajjal **My Particular Issue apparently unrelated to this issue** is opened as #2475. According to @roblourens it's been fixed downstream and will be in next release, so further discussion of my issue should go there :)

**Comment by thohe973** [comment]
I got it working by also sending my ssh key to the proxy.
```
Host random_name
  HostName <host name>
  Port 22
  User <host user>
  IdentityFile <private ssh key>
  ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -i <private ssh key> -W %h:%p -q <proxy user>@<proxy host>
```

**Comment by veekayr** [comment]
Below command is working

`ProxyCommand C:\\Windows\\System32\\OpenSSH\\ssh.exe -i <ssh-key> -q -W %h:%p jumpbox`

**Comment by holoword** [comment]
if `ProxyCommand C:\\Windows\\System32\\OpenSSH\\ssh.exe -i <ssh-key> -q -W %h:%p jumpbox` doesn't work, Just use another ssh client. Just like git bin bash ssh client
set Remote.ssh.path in settings as like this
`C:\Program Files\Git\usr\bin\ssh.exe`  or any other ssh client you have

**Comment by Querela** [comment]
For me worked the following: [on **Win10**, w/ w/o WSL]
- starting with the same ssh configs described in https://code.visualstudio.com/blogs/2019/10/03/remote-ssh-tips-and-tricks#_proxycommand
- just replaced `ssh` with `ssh.exe`
- specifying identity files, ssh config files, netcat etc. on ProxyCommand did not work for me -- but I did not test an absolute `ssh` path, just added `.exe`

---

As for my ssh-key login:
For both hosts, I needed to specify my `id_rsa_vscode` file. That I needed to do regardless of proxying or not.
```ssh
Host *
   IdentityFile C:\Users\<username>\.ssh\id_rsa_vscode

[...]
```

And I needed to copy my keys with `ssh-copy-id` to the remote hosts. I *also* needed to specify `-f` because I used different `id_rsa` files for normal ssh login in WSL and for VSCode, and without `-f` it would not copy the second VSCode ssh key. (*That was neccessary because VSCode could not work with ssh-agent or password protected ssh identity files - as far as I know - without always typing the remote ssh passwords on each (re-)connect.*)

**Comment by eromoe** [comment]
I patched windows 10 before.
After upgrading to Windows 10 2004(20H1) . 

```
C:\Users\xxxx>ssh -vvv dc42
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug1: Reading configuration data C:\\Users\\xxxx/.ssh/config
debug1: C:\\Users\\xxxx/.ssh/config line 1: Applying options for *
debug1: C:\\Users\\xxxx/.ssh/config line 152: Applying options for dc42
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug1: Executing proxy command: exec ssh dc_entry -W dc42:22
debug3: spawning "C:\\Windows\\System32\\OpenSSH\\ssh dc_entry -W dc42:22"
CreateProcessW failed error:2
posix_spawn: No such file or directory
```

Is this a new but or not ?

**Comment by pd93** [comment]
@eromoe Unfortunately, that's still version 7.7 which does not contain the fix. You'll need to [manually update to v8.0+](https://github.com/microsoft/vscode-remote-release/issues/18#issuecomment-507258777) or use one of the other workarounds mentioned above.

It has been confirmed [in another issue](https://github.com/PowerShell/Win32-OpenSSH/issues/1515#issuecomment-635668125) that v8.1 will be released in an update later this year, but **is not included in Windows 10 2004 (20H1):**

> v8.1 goes into the next release (not into win10 version 2004) available during fall time.

**Comment by anji993** [comment]
@eromoe @pd93  Did you solve the problem after upgrading to Windows 10 2004 by patching it again. I meet the same problem after I upgrade to Windows 10 2004. But patching manually updating to v8.0+ does not solve this problem.

**Comment by eromoe** [comment]
@anji993 Patching does sovle my problem , may be something wrong with previllage ?

**Comment by susguzman** [comment]
> For me worked the following: [on **Win10**, w/ w/o WSL]
> 
> * starting with the same ssh configs described in https://code.visualstudio.com/blogs/2019/10/03/remote-ssh-tips-and-tricks#_proxycommand
> * just replaced `ssh` with `ssh.exe`
> * specifying identity files, ssh config files, netcat etc. on ProxyCommand did not work for me -- but I did not test an absolute `ssh` path, just added `.exe`
> 
> As for my ssh-key login:
> For both hosts, I needed to specify my `id_rsa_vscode` file. That I needed to do regardless of proxying or not.
> 
> ```
> Host *
>    IdentityFile C:\Users\<username>\.ssh\id_rsa_vscode
> 
> [...]
> ```
> 
> And I needed to copy my keys with `ssh-copy-id` to the remote hosts. I _also_ needed to specify `-f` because I used different `id_rsa` files for normal ssh login in WSL and for VSCode, and without `-f` it would not copy the second VSCode ssh key. (_That was neccessary because VSCode could not work with ssh-agent or password protected ssh identity files - as far as I know - without always typing the remote ssh passwords on each (re-)connect._)

It worked  for me :)
Thank you

**Comment by nicolaipre** [comment]
FWIW: For anyone wanting password authentication only, this config works on Linux for jump-hosts:
```
Host <alias>
    HostName <hostname/ip-addr>
    Port 22
    User <user>
    ProxyCommand ssh -W %h:%p -q <user>@<jump-host-ip>
```

**Comment by tysonite** [comment]
Have anyone seen https://github.com/microsoft/vscode-remote-release/issues/3857 that with jump server too?

**Comment by pd93** [comment]
A quick update for anyone following this issue. MSFT currently have a [pinned issue](https://github.com/PowerShell/Win32-OpenSSH/issues/1693) explaining why OpenSSH was not included in the 20H2 release. I've updated my [workaround comment](https://github.com/microsoft/vscode-remote-release/issues/18#issuecomment-507258777) above to reflect this.

**Comment by plevold** [comment]
[The manual fix](https://github.com/microsoft/vscode-remote-release/issues/18#issuecomment-507258777) by @pd93 worked like a charm for me, but a Windows update seems to have overwritten the updated ssh.exe. Rather than potentially having to replace the executable after future updates I simply extracted the zip to a different location and added it to the systems PATH. My steps:

- Download OpenSSH [v8.1.0.0 .zip](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v8.1.0.0p1-Beta)
- Extract to a suitable location, e.g. `C:\bin\OpenSSH-Win64`
- Open _Edit the system environmental variables_ (found in the control panel or start menu)
- Edit the _Path_ variable and add `C:\bin\OpenSSH-Win64`
- Make sure that the new entry is above the entry `%SYSTEMROOT%\System32\OpenSSH\`
- Restart VSCode

Note that I had to edit PATH for the whole _system_, not my _user_. In the latter case the entry will be added after the system version giving it precedence.

Beware that sometime in the future this solution could cause problems if the system OpenSSH version is updated to a more recent version than the manually installed one...

**Comment by matijagrcic** [comment]
> # Manual Fix
> * Download the [v8.1.0.0 release `.zip`](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v8.1.0.0p1-Beta).
> * Extract the `.zip` file
> * Copy and replace the extracted `ssh.exe` binary into your `C:\Windows\System32\OpenSSH` folder.
> * Done! You can now use "Remote Development - SSH" with `ProxyJump` in the expected way.
> 
> If you get a permissions error then this may be because there is system protection in place on the existing `ssh.exe` binary. This can be removed by setting yourself as the owner of the file (requires admin) and granting yourself "full control". To do this, follow these steps:
> 
> * Right-click on the existing file `C:/Windows/System32/OpenSSH/ssh.exe` and select `Properties`.
> * Open the `Security` tab and click on `Advanced`.
> * Click the button to change the owner and change it from `TrustedOwner` to your Windows username.
> * Type your username and click the `Check Names` button (This should autofill with your full username/email).
> * Apply the settings and then close the properties window and reopen it.
> * Navigate back to the `Security` tab and click on `Edit`.
> * Select the `Users` group and give the group `Full Control`.
> * Click `Apply` and exit.
> * Now go back and try patching the file again.

Worked without any issues. I've used MobaXterm for a long time to first setup the tunnel and then just connect to the destination, but now it's not needed anymore with `ProxyJump` working correctly.

**Comment by AdorableYoyo** [comment]
> For me worked the following: [on **Win10**, w/ w/o WSL]
> 
> * starting with the same ssh configs described in https://code.visualstudio.com/blogs/2019/10/03/remote-ssh-tips-and-tricks#_proxycommand
> * just replaced `ssh` with `ssh.exe`
> * specifying identity files, ssh config files, netcat etc. on ProxyCommand did not work for me -- but I did not test an absolute `ssh` path, just added `.exe`
> 
> As for my ssh-key login:
> For both hosts, I needed to specify my `id_rsa_vscode` file. That I needed to do regardless of proxying or not.
> 
> ```
> Host *
>    IdentityFile C:\Users\<username>\.ssh\id_rsa_vscode
> 
> [...]
> ```
> 
> And I needed to copy my keys with `ssh-copy-id` to the remote hosts. I _also_ needed to specify `-f` because I used different `id_rsa` files for normal ssh login in WSL and for VSCode, and without `-f` it would not copy the second VSCode ssh key. (_That was neccessary because VSCode could not work with ssh-agent or password protected ssh identity files - as far as I know - without always typing the remote ssh passwords on each (re-)connect._)

life saving!!! I had to log in to appreciate your share! Got mine solved! thanks!

**Comment by pd93** [comment]
@roblourens I believe this can be closed now. This was never a VSCode issue and it should now be resolved anyway as a newer (and working) version of OpenSSH is now [included in the latest version of Windows](https://github.com/PowerShell/Win32-OpenSSH/issues/1693#issuecomment-839645418).

Anyone on older versions of Windows (and therefore OpenSSH) can follow the [manual steps](https://github.com/microsoft/vscode-remote-release/issues/18#issuecomment-507258777) I outlined earlier in this issue in order to update.

**Comment by roblourens** [comment]
Thanks for pointing that out @pd93
