### ISSUE TITLE
Remote - Containers 'remote-containers.openFolder' not found

### ISSUE THREAD

**Issue by 33df** [microsoft/vscode-remote-release#1831]
## Remote - Containers

I have installed this official extension `ms-vscode-remote.remote-containers` but I keep getting the error `remote-containers.openFolder not found`, as soon as I try one of the commands that are suggested in the README.

I also get this when I do attach to container:

```
Error running command remote-containers.attachToRunningContainerFromViewlet: command 'remote-containers.attachToRunningContainerFromViewlet' not found. This is likely caused by the extension that contributes remote-containers.attachToRunningContainerFromViewlet.
```

- VSCode Version: latest
- OS Version: Arch Linux 5.3.8-zen1-1-zen

**Comment by 33df** [comment]
@alexr00 Remote Containers 0.83.1, VS Code: 1.40.0

**Comment by Chuxel** [comment]
@33df Are you using the "Code - OSS"  or the official VS Code distribution bits?  For Arch Linux, official bits are here in AUR here:

https://aur.archlinux.org/packages/visual-studio-code-bin/
https://aur.archlinux.org/packages/visual-studio-code-insiders/

I've seen a few people mention this the past few days on Arch because there seem to be a few other packages in the distro that are different flavors of the open source builds (like "code") which is why its not showing up for other distributions.
