### ISSUE TITLE
Extension version ignored

### ISSUE THREAD

**Issue by catkins-miso** [microsoft/vscode-remote-release#1833]
- VSCode Version: 1.39.2
- Local OS Version: Windows 10
- Remote OS Version: N/A
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. In devcontainer.json specify `"extensions": ["extension id@version"]`
2. VSCode installs only the latest version

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by chrmarti** [comment]
@sandy081 It appears to install the specified version, but then immediately auto-updates. Maybe the version should be pinned when specified on the command line?
![image](https://user-images.githubusercontent.com/9205389/68752407-8e486880-0603-11ea-9a83-e474bbdf1015.png)

**Comment by sandy081** [comment]
Version is not remembered when installed (particular version) from command line - https://github.com/microsoft/vscode/issues/63903

Even though above feature is supported, it is very tricky to support in remote case. Because versions are remembered in the storage and auto updates are triggered from UI. So in remote case there is no way to communicate from remote cli to UI to remember the version.
