### ISSUE TITLE
Customize repository-containers dir

### ISSUE THREAD

**Issue by mtsmfm** [microsoft/vscode-remote-release#1885]
I'd like to customize repository-containers dir to have my own definition.
It can be useful:

- Contain my favorite settings (zshrc etc), tools (hub etc)
- Test before sending PR to this repo

**Comment by mrpastewart** [comment]
@mtsmfm you can also add your own to the /dist/node_modules/vscode-dev-containers/repository-containers folder and delete ones you don't like so in a sense you can customize it you just would need to store your setup in git and when you add new definitions push them in your git repo so that when you setup vscode or recover from an update you can run a script that deletes the defaults and in seconds reinstall your customized container definitions. thats what i am doing now and it works.

**Comment by mtsmfm** [comment]
It seems this feature request is duplicated with https://github.com/microsoft/vscode-remote-release/issues/3218.
It's already implemented but [doesn't work on WSL though](https://github.com/microsoft/vscode-remote-release/issues/3708), let me close.
