### ISSUE TITLE
file links don't work

### ISSUE THREAD

**Issue by corani** [microsoft/vscode-remote-release#1942]
Version: 1.41.0-insider (user setup)
Commit: bf7d03bf88732af0b46e473c663c49e18e839f9c
Date: 2019-11-15T05:40:12.201Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

Remote OS: Ubuntu 18.04.3 LTS x64
Remote Extension: SSH

Steps to Reproduce:

1. Use the TODO+ extension (https://github.com/fabiospampinato/vscode-todo-plus) to generate a list of TODOs in a project
2. Links look sensible: `@file:///path/to/file.ext#33` but clicking them doesn't work
3. Note: Links in the sidebar *do* work

I guess VS Code tries to resolve the links locally, instead of remotely.

Related: https://github.com/fabiospampinato/vscode-todo-plus/issues/234

**Comment by corani** [comment]
Error:

```
Unable to open 'file.ext'
Unable to read file (Error: File not found \path\to\file.ext)
```

**Comment by roblourens** [comment]
Link provider not going through the URI transformation, not sure who knows about this? @rebornix, @isidorn, ...?

**Comment by isidorn** [comment]
I do not know this, sorry.
Here's the editor link detector which might be good reference to investigate further https://github.com/Microsoft/vscode/blob/4341ec073d7c9248983dd385e3860c2ec77e56ec/src/vs/editor/contrib/links/links.ts#L100

**Comment by roblourens** [comment]
@jrieken?

Can repro without extensions involved, just paste something like `// file:///datadrive/vscode-oss/package.json` (for a valid path) into a file in a remote window.

**Comment by jrieken** [comment]
Depends on who is creating the link. For `http`, `https`, and `file` that happens on the renderer side (editor worker) and without any remote knowledge. If links are provided by extensions then they overrule the default link provider and they get transformed. Looks like there is no easy solution for this because I can easily create a broken link the other way around and it seems that this can only be fixed in the TODO extension but checking where it runs and what it targets but adding @alexdima for more insights
