### ISSUE TITLE
Deleting a repository container could not offer to delete the volume if in use

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#1949]
Testing https://github.com/microsoft/vscode-remote-release/issues/1931

It would be nice if the "Do you want to delete the volume?" prompt that shows when you remove a repository container doesn't show if you're currently connected (in the same window) to a container that uses the same volume.

**Comment by chrmarti** [comment]
From the duplicate:

When removing a Repository Container I'm asked if I want to remove the associated volume even when there are still other containers using it. Trying to remove the volume fails because it is still in use.

When there are no other containers using the volume we might still want to warn the user IN CAPS when there are other repositories than the one from the container being removed.

**Comment by egamma** [comment]
To verify:
- 1st container: Remote Containers Open Repository in Container
- Enter a repository, e.g., https://github.com/Microsoft/vscode-npm-scripts
- Create new volume for the repository
- Close the Remote Container
- 2nd container: Remote Containers Open Repository in Container
- Enter another repository, e.g., https://github.com/Microsoft/vscode-tslint
- Create new volume for the repository
- Close the Remote Container
- In the remote explorer remove the first container
- Verify, that you are not prompted to remove the volume (the volume is still in use by the 2nd container)
- In the remote explorer remove the 2nd container
- Verify, that you are now prompted to remove the volume, since it is no longer in use.

**Comment by alexr00** [comment]
Verifying blocked on https://github.com/microsoft/vscode-remote-release/issues/2654 for Windows right now. Will verify when there's a new build.
