### ISSUE TITLE
Open attached container config command fails confusingly when no folder is open

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-remote-release#1959]
Testing https://github.com/microsoft/vscode-remote-release/issues/1937

1. Start a container to attach
2. Use remote explorer to connect to container
3. Run command for opening attached container config

:bug: => it fails saying we are not attached to a container and has you select one.

it should tell you to open a folder.

**Comment by chrmarti** [comment]
`Remote-Containers: Open Container Configuration File` should immediately open the configuration file.

`Remote-Containers: Open Attached Container Configuration File...` would let you choose a configuration. Maybe that command should not be available while connected to a container because it cannot be distinguished from the first.

Did you use one of those commands? They don't talk about not being attached to a container. 🤔

**Comment by sbatten** [comment]
You are right, I was confused by the existence of the 2 commands. However, if I've never run either command and follow the repro steps, I get the following: 
![image](https://user-images.githubusercontent.com/6561887/70174000-e9143380-1688-11ea-9c7b-689ce17d6e36.png)

It says "Attach to a container first" when I am already attached to a container.

**Comment by sbatten** [comment]
This removes the text about the incorrectly needing to attach to a container, but I can infinitely loop through several steps.

1. Attach to Container A
2. Run `Open attached Container Configuration File...`
3. Select `No configuration found`
4. Select Container A to attach => go to step 2
