### ISSUE TITLE
Starting vscode in WSL terminal can't find remote wsl extension

### ISSUE THREAD

**Issue by kwint** [microsoft/vscode-remote-release#2043]
- VSCode Version: 1.41.0
- Local OS Version:  10.0.18363.535
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: WSL

Steps to Reproduce:
When I open vscode in a wsl terminal with `code .` vscode can't find the remote wsl extension. When I go to the marketplace to install the extension it is already installed and it says that I need to reload vscode. When I do this vscode restarts but nothing has changed. When I open vscode in windows and then connect to wsl everything works as expected. 

This is what I see when I start vscode in wsl:
![Code_saC5ytw2ME](https://user-images.githubusercontent.com/7907280/70978969-10b7c280-20b1-11ea-8bf6-1e9ee650290c.png)

**Comment by WSLUser** [comment]
>When I open vscode in a wsl terminal with code .

You already stated why the Remote - WSL extension doesn't work. When in WSL, you're running Linux. So of course the extension won't work. Remote - SSH and Remote -Containers will but Remote - WSL is a Windows specific extension since it only exists on Windows. So it won't execute Linux commands but Windows commands. Technically the interop should allow those commands to run but something in the implementation of the extension obviously prevents that interop. I don't see this as being an actionable item but rather "by-design".

**Comment by kwint** [comment]
This worked before and also works for my colleagues

**Comment by WSLUser** [comment]
Are you aliasing `code . ` to run Windows VS Code within WSL? Or do you have the Linux version of VSCode installed?

**Comment by kwint** [comment]
So these are steps I followed: https://code.visualstudio.com/docs/remote/wsl#_open-a-folder-in-wsl
worked before, now it doesn't anymore

**Comment by WSLUser** [comment]
Sounds like an interop problem which might of been changed in the extension, WSL, or some Windows patch that affected something WSL uses. From the sounds of it, the latter is the most likely culprit.

**Comment by aeschli** [comment]
@sandy081 Any idea how to debug this?
Looks like the extension is installed, but never enabled.

@kwint When you select the disabled extension, does it show any reason in the extension viewer?

**Comment by sandy081** [comment]
@aeschli Are you able to reproduce this? If so we I can help you in debugging.

Let's wait for user's response on why the extension is disabled.

**Comment by aeschli** [comment]
@sandy081 I'm not able to reproduce

**Comment by kwint** [comment]
When I click the install button on the pop up thingy in the picture above I see this:
![afbeelding](https://user-images.githubusercontent.com/7907280/71980023-63ebe380-321f-11ea-9c21-b39ad5465592.png)

When I manually search for the extension I see this, so it does not really show any reason:
![afbeelding](https://user-images.githubusercontent.com/7907280/71980059-7e25c180-321f-11ea-8e35-82fd92d96dfe.png)

**Comment by sandy081** [comment]
I see icons are not loaded in your screenshots. Are you able to install other extensions without issues?

**Comment by kwint** [comment]
I cannot install extensions when I'm in wsl. I can in "windows mode".
Icons are loaded at the moment, but it can't connect to the marketplace:

![afbeelding](https://user-images.githubusercontent.com/7907280/72073257-db894380-32ef-11ea-9c16-95db036d89b8.png)

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by sandy081** [comment]
Thanks for the update.
