### ISSUE TITLE
Opening home folder in WSL remote explorer closes the current editor window

### ISSUE THREAD

**Issue by ahmedkrmn** [microsoft/vscode-remote-release#2044]
- VSCode Version: 1.41.0
- Local OS Version: Windows_NT x64 10.0.18362
- Remote OS Version: 0.41.6
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Setup a [Linux Subsystem for Windows](https://docs.microsoft.com/en-us/windows/wsl/install-win10).
2. Install the [Remote - WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) extension.
3. Open your Linux home folder from the Remote Explorer icon on the sidebar of VS Code extensions sidebar.

![demo](https://user-images.githubusercontent.com/20889958/70989186-d871ad80-20cb-11ea-8986-2ba5111e0bcd.gif)

**Comment by alexr00** [comment]
This is as designed. Check out the `window.openFoldersInNewWindow` setting. The `default` value says "Folders will open in a new window unless a folder is picked from within the application (e.g. via the File menu).". Since the Remote Explorer is "within the application" it doesn't open a new window.
