### ISSUE TITLE
Support starting Remote Containers under WSL2 VolFs using WSL-side Docker binaries

### ISSUE THREAD

**Issue by lbssousa** [microsoft/vscode-remote-release#2103]
Currently VSCode **Remote - Containers** extension starts containers using Windows-side Docker binaries (`docker.exe`, `docker-compose.exe`), which mess up file ownership/persmissions of shared volumes when my workspace is under a WSL2 native filesystem (VolFs). The only workaround I've found for this trouble is starting manually my containers using WSL-side Docker binaries (`docker`, `docker-compose`) and then use VSCode option to attach to running container.

I would like to suggest you to make VSCode able to start remote containers under WSL2 VolFs using WSL-side Docker binaries. For example:
* If I connect to a WSL remote (using **Remote - WSL** extension) whose workspace folder has a `.devcontainer` configuration, show a button **Reopen in Container** (in this case, prefer using WSL-side Docker binaries to start the container).
* If I directly open a project folder whose full path matches WSL pattern (e.g. `\\wsl$\Ubuntu-18.04\home\user\workspace`) and it has a `.devcontainer` configuration, VSCode should try to start the container using WSL-side Docker binaries.

**Comment by lbssousa** [comment]
It seems there's some WIP now: https://github.com/microsoft/vscode-remote-release/issues/2498

**Comment by mwoodpatrick** [comment]
I could definitely use this change

**Comment by gitfool** [comment]
[WSL 2 Support](https://github.com/microsoft/vscode-docs/blob/master/remote-release-notes/v1_45.md#wsl-2-support) works! 🎉 🍺 🍰 ❤️

**Comment by PavelSosin-320** [comment]
Docker Desktop is WSL 2 the distro itself now. It implements a certain Docker spec version. If the remote image will implement another Docker spec version it will be very inconsistent. 
For the real remote, i.e. serverless landscape Docker offers another proven and consistent solution: Swarm or Kubernetes. Both solutions are available out-of-the-box. Both solutions are easily manageable. Every machine with Docker Desktop is a Single node cluster, master, or slave node and can be attached to the cluster with almost zero efforts. Even minimal Swarm offers overlay networks and the many other necessary features like mesh, node proxy, service discovery, etc. This is the essence of a distributed Docker solution. The proposal says Node-inside-node but it contradicts the existing Cloud infrastructure architecture in which node nesting is impossible due to simple reasons- **it breaks commonly used Node-port service publishing mechanism.**  
it means **Docker proxy behind Docker proxy** 
Unless running several WSL 2 images in parallel with Docker daemons on the same machine is possible, i.e. replication of Node-pod Cluster stack such a solution has no benefits.

**Comment by chrmarti** [comment]
@gitfool Indeed, this is available with #2779. Closing. :)
