### ISSUE TITLE
Support ${localWorkspaceFolderBasename}

### ISSUE THREAD

**Issue by thaney071** [microsoft/vscode-remote-release#2129]
VS Code documents the available variables at https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables. When I try to use these in the devcontainer.json for mounting, they don't apear to work. 

Please add documentation for what predefined variables this extension recognizes.

**Comment by Chuxel** [comment]
I believe the `mounts` property in the devcontainer.json reference includes this information: https://code.visualstudio.com/docs/remote/containers#_devcontainerjson-reference

Does this cover what you are looking for or is there something else you are looking for beyond what is in devcontainer.json?

**Comment by thaney071** [comment]
This helps, but if I understand it correctly, I should be able to do 
```
"workspaceMount": "source=${localWorkspaceFolder},target=/go/src/<go-import-path>/${localEnv:workspaceFolderBasename},type=bind,consistency=delegated",
"workspaceFolder": "/go/src/<go-import-path>/${localEnv:workspaceFolderBasename}",
````
but the `workspaceFolderBasename` is a VS code variable not in localEnv. The example has `localWorkspaceFolder` but that give the full path an I only want the Basename not the full path.

**Comment by Chuxel** [comment]
@thaney071 `localEnv` is purely for accessing local environment variables. It's similar to `${env:VARIABLE}` in `launch.json` or `task.json` (which is the context of https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables).  

The reason for the `local` prefix is  because there are also container variables that can be used with the `remoteEnv` property in devcontainer.json for things like updating the `PATH`.

That said, unfortunately, there is no `localWorkspaceFolderBasename` variable today in `devcontainer.json`, but we could change this to a feature request to add it if you find that you need it for your scenario. Would that make sense?

//cc: @chrmarti

**Comment by Chuxel** [comment]
This has actually been available for a while now, so closing as done!
