### ISSUE TITLE
Be smarter about when to use the proxy settings from the local side

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#213]
From https://github.com/microsoft/vscode/issues/60773#issuecomment-490236862_

**Comment by BobVul** [comment]
So currently the proxy is always taken from local if not explicitly set on the remote side?

Would it work to simply never use local proxy settings on remote, and instead force users to explicitly configure it? Either via `http_proxy` on the remote, or via remote settings in vscode. This would be consistent with keeping proxy settings machine-specific.

I certainly wasn't expecting local network configs to be used on the remote. Though I suppose sometimes remoting would happen between computers in the same network.

**Comment by chrmarti** [comment]
For Remote-WSL and Remote-Containers using the local settings is usually the correct. (Remote-Containers can connect to a remote machine, but that is currently not the common case.)

`http_proxy` does override that and there is a setting that you can use to override it as well.

**Comment by BobVul** [comment]
Ah, sorry - I only thought about the SSH case. 

In that case would it be possible to special case

**Comment by BobVul** [comment]
Ah, sorry - I only thought about the SSH case. I can see how copying local proxy makes sense for WSL/Containers where local network is implied.

I did eventually discover the overrides. It took a while to figure out that my local proxy was being applied to the remote, though. 

Since `http_proxy` overrides, can absence of `http_proxy` be taken as no proxy instead? Is it possible/easy to apply that only to the SSH connector?

**Comment by chrmarti** [comment]
I agree this can be improved. A notification would likely be seen as noisy, as you suggest.

**Comment by chrmarti** [comment]
Fixed with #2487.
