### ISSUE TITLE
Unable to open vscode from wsl?

### ISSUE THREAD

**Issue by rohitkrishna094** [microsoft/vscode-remote-release#2139]
I am using hyper terminal and I have given this as the shell in hyper config file.

`shell: 'C:\\Windows\\System32\\wsl.exe',`

Now when I open hyper and type code . from any folder, I am getting this message.

```
For the current version of WSL, VS Code Remote - WSL can be opened from the command line only from the 
default distro. Use 'wslconfig.exe' to configure the default distro. Alternatively update your version 
of WSL by updating Windows 10 to the May 19 Update, version 1903.
```

So the above message is asking me to either update to May 19 update(which I cannot do) or set the default distro using wslconfig.exe.

So I tried running wslconfig.exe /l and this is what I get:

```
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
```

As you can see, Ubuntu is the only distro I have and it is set to Default anyway. So why am I getting the above prompt whenever I run `code .` or something similar from my terminal?

I also posted the same on stackoverflow [here](https://stackoverflow.com/questions/59638746/unable-to-open-vscode-from-wsl), but have got no response yet.

**Comment by aeschli** [comment]
What happens if you get a regular Ubuntu shell (Run 'Ubuntu' from the Windows start menu), and type `code .` in there?

**Comment by yanglr** [comment]
Open command line in Windows, then type:
```bash
wsl --shutdown
wsl
```
I solved the issue by rebooting the WSL using above commands.

Refer to:
<https://stackoverflow.com/a/57887086/6075331>

**Comment by rohitkrishna094** [comment]
Thanks @yanglr . I was able to resolve the issue long back by just reinstalling everything. But looks like your solution was what I needed back then. Closing the issue now. Thanks.

**Comment by PavelSosin-320** [comment]
It looks like this issue is resolved already in the Windows build 2061
but numerous incompatible changes were introduced in WSL2, like 
Linux kernel was upgraded

- addressing WSL distros via \\wsl\ instead of \\\wsl$
Windows - Linux interoperability was "improved"
 

- support of systemd, i.e. it's enough to restart systemd service via systemctl daemon-reexec instead of full wsl restart in most cases

automount has been corrected. 
etc.
Old Linux distro may not work properly unless re-installed on the top of the new Windows build, it happened me.
