### ISSUE TITLE
VSCode throws error when setting PATH environment variable in devcontainer.json

### ISSUE THREAD

**Issue by pcgeek86** [microsoft/vscode-remote-release#2324]
I have the following `devcontainer.json` file in a project.

When I try to open VSCode in a container, it crashes. The container builds successfully, but the following logs are emitted during startup. When I remove the environment variable configuration, the container starts up and stays running just fine.

I followed the example for configuring environment variables inside the dev container, according to the Visual Studio Code documentation for [Advanced Container Configuration](https://code.visualstudio.com/docs/remote/containers-advanced).

**Question**: How do I properly configure the `PATH` environment variable in my `devcontainer.json` file? 

### devcontainer.json

```json
{
	"name": "Ubuntu 18.04 & Git",
	"dockerFile": "Dockerfile",
	"settings": { 
		"terminal.integrated.shell.linux": "/bin/bash"
	},
	"containerEnv": {
		"PATH": "${containerEnv:PATH}:/root/.customfolder/bin/"
	}
}
```

### Logs

```
6499 ms] Successfully built 096d41dceada
[6503 ms] Successfully tagged vsc-asdf-73cee28d5205fdd4a6063fc596248885:latest
[6506 ms] Start: Run: git rev-parse --show-toplevel
[6533 ms] Start: Starting container
[6533 ms] Start: Run: docker run -a STDOUT -a STDERR --mount type=bind,source=/Users/username/git/asdf,target=/workspaces/asdf,consistency=cached --mount source=/Users/username/.aws/credentials,target=/root/.aws/credentials,type=bind -l vsch.quality=stable -l vsch.remote.devPort=0 -l vsch.local.folder=/Users/username/git/asdf -e PATH=${containerEnv:PATH}:/root/.customfolder/bin/ --entrypoint /bin/sh vsc-pulumi-73cee28d5205fdd4a6063fc596248885 -c echo Container started ; while sleep 1; do :; done
[6852 ms] /bin/sh: 1: sleep: not found
[6852 ms] Container started
[6873 ms] Start: Inspecting container
[6879 ms] Start: Run in container: uname -m
[7031 ms] Start: Run in container: cat /etc/passwd
[7035 ms] Shell server terminated (code: 1, signal: null)

Error response from daemon: Container 8e0f6eeb22c358b0dfd8f1c1410c10b382ea66aa432e7e400a4564671619046f is not running
```

[![An error occurred setting up the container][1]][1]

> An error occurred setting up the container

### Environment

* MacOS Catalina
* Docker Desktop 2.2.0.0
* Microsoft Visual Studio Code 1.42.0
* VSCode Remote-Containers extension 0.101.0

[Originally posted on StackOverflow](https://stackoverflow.com/questions/60143713/vscode-crashes-when-setting-path-environment-variable-in-devcontainer-json)

  [1]: https://i.stack.imgur.com/VcyRH.png

**Comment by Chuxel** [comment]
This was answered on Stack overflow and twitter.

---

You should be able to change the property from `containerEnv` to `remoteEnv` to resolve the issue.

Only the `remoteEnv` property supports referencing existing container env vars.  The `containerEnv` property is like `-e` for the Docker CLI and is therefore evaluated before the container is created.  This is mainly useful when your Dockerfile itself depends on certain env vars being set (though you can modify the PATH inside your Dockerfile if you so desire).

For everything else, `remoteEnv` is the way to go since VS Code and all sub-processes like terminals us it. Since this is evaluated after container create, you can update the path as the examples illustrates.

```
"remoteEnv": {
    "PATH": "${containerEnv:PATH}:/some/other/path",
    "MY_REMOTE_VARIABLE": "some-other-value-here",
    "MY_REMOTE_VARIABLE2": "${localEnv:SOME_LOCAL_VAR}"
}
```
---

In the case where the path needs to be updated before the container starts, the only option is to add it to a Dockerfile or apply another workaround that updates something like `.bashrc`.

To update the `Dockerfile`, you'd just add:

```
ENV PATH=$PATH/some/other/path
```
