### ISSUE TITLE
Reconnection dialog still shown when maxReconnectionAttempts is 0

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-remote-release#2443]
Issue Type: <b>Bug</b>

https://github.com/microsoft/vscode-remote-release/issues/2010

1. Set `remote.SSH.maxReconnnectionAttempts` to 0
2. Connect to an SSH remote
3. Turn off wifi

A reconnection dialog appears after a moment, I was expecting it to not be shown.

VS Code version: Code - Insiders 1.43.0-insider (b0be0672c210f1fa76109ce675365bb785657e84, 2020-02-26T05:28:00.237Z)
OS version: Darwin x64 18.7.0

remote-ssh-nightly|ms-|2020.2.35520

</details>

**Comment by roblourens** [comment]
Yeah, I thought about putting this setting in the core where it would be slightly nicer and I could avoid this. As-is I can't do anything about this. But since I don't think there is really any other application for this, I'll leave it in the extension. At least the dialog only shows up for a few seconds.
