### ISSUE TITLE
Disconnects when using on AWS instance with the Comment Anchor extension

### ISSUE THREAD

**Issue by BrunoFant** [microsoft/vscode-remote-release#2502]
Issue Type: <b>Bug</b>

Connection to the server (using a key pair) works without problems, but when and only when the Comment Anchors extension is installed, the connection will drop a few moments in (when comment anchors is ~7% into scanning a large workspace), forcing a reload.

Extension version: 0.49.0
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.3.0-40-generic
Remote OS version: Linux x64 4.15.0-1058-aws
Remote OS version: Linux x64 4.15.0-1060-aws

**Comment by roblourens** [comment]
I can't reproduce this but it sounds like Comment Anchors might be crashing the extension host process.  It looks like there are some issues related to this: https://github.com/ExodiusStudios/vscode-comment-anchors/issues/66 and https://github.com/ExodiusStudios/vscode-comment-anchors/issues/54. Please file an issue on the comment anchors extension repo, since they might know where to find any more logs.
