### ISSUE TITLE
can't install extension pack

### ISSUE THREAD

**Issue by uishon** [Microsoft/vscode-remote-release#26]
Can't install. Clicked on the "install" button of the extension-pack [here](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) - extension was opened in the stable VS code version, not in the insiders version (both are installed on my Windows 10 machine). Tried to search for the extension manually from my insiders version, but the extension pack is not found (tried "remote development", "vscode-remote-development", etc.). How can I go about installing it?

**Comment by a2975667** [comment]
I actually had to change the HTML so that the extension launches in vscode-insiders. Otherwise, you can always download the extension and install it directly from the downloaded file.

**Comment by egamma** [comment]
@a2975667 sorry that it is not easy to search for the remote extensions. We are working on improving it. What works is in **VS Code Insiders** (not stable, since the extensions are not supported there) search for **remote**. And then scroll down until you find the remote extensions with this icon:

<img width="165" alt="image" src="https://user-images.githubusercontent.com/172399/57108139-2a7ae400-6d32-11e9-9427-6f7e21ed1240.png">

**Comment by uishon** [comment]
Thanks. Got it installed.
