### ISSUE TITLE
problems developing with non root user inside container, workspace folder has no user permissions

### ISSUE THREAD

**Issue by lucaszanella** [microsoft/vscode-remote-release#2695]
- VSCode Version: 1.43.2
- Local OS Version: Debian 9
- Remote OS Version: Node docker image
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

```
{
	"name": "ead_scrapper",
	"dockerFile": "../docker/Dockerfile",
	"extensions": [],
	"workspaceFolder": "/home/user/project",
	"containerEnv": {
		"DISPLAY": "unix:0"
	},
	"mounts": [
		"source=/tmp/.X11-unix,target=/tmp/.X11-unix,type=bind,consistency=cached",
	],
	"remoteUser": "user",
	"runArgs": [
		"--privileged"
	]
}
```

I've put `"remoteUser": "user"`, but it mounts the project inside `/workspace/ead_scrapper`, where the user cannot alter anything. It should mount things inside `/home/user/project` where user `user` can alter things. What is `"workspaceFolder": "/home/user/project"` if not for setting where the workspace is gonna be mounted?

**Comment by chrmarti** [comment]
Since you are on Linux, the mounted files will always have the same UID:GID as on your local filesystem. There is a feature to automatically update UID:GID of the container's user to the local UID:GID, but that depends on that UID:GID combination not being used by some other user or group in  the container already.

Check what you get for running `id` locally and then check if these are taken in the container's `/etc/passwd` and `/etc/group`.

Can you also attach the log (`F1` > `Remote-Containers: Show Log`) here?
