### ISSUE TITLE
${workspaceFolder} in remote workspaces for UI DAs

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#270]
From https://github.com/microsoft/vscode-chrome-debug/issues/832, when a DA is running as a UI extension, I think `${workspaceFolder}` in the launch config should be resolved to the full remote URI, because the DA needs to return the full URI for non-file paths. But when running as a workspace extension, it should still be an absolute path (or file URI).

**Comment by isidorn** [comment]
This might have reprocussions for tasks. Should other variables be resolved differently as well then?
Either way feels a bit unnatural to me, the variables are resolved by the renderer, why would the renderer resolve this variable differently just because some extension is running remotly. The resolver is not aware for what the variable will be used.

fyi @dbaeumer @alexr00

**Comment by roblourens** [comment]
Well the extension has to get the correct URI somehow, because it is expected to return proper remote URIs. Something must know that there is a difference between remote and local extensions.

**Comment by roblourens** [comment]
Actually there is no way to get around the DA needing to make changes to support this kind of scenario, not sure it makes sense to resolve `workspaceFolder` differently. I think I will need to do something with the debug config resolver and make this as close to the normal remote debug scenario.
