### ISSUE TITLE
reload session window when computer sleeps/lid is closed

### ISSUE THREAD

**Issue by seen76** [microsoft/vscode-remote-release#2765]
Hi,

I am using the insider's version of vscode remote and it happens to me quite often that the reload session modal appears if my computer is going to sleep, or i close and re-open the lid. I guess that means the local server was terminated behind the scenes. What causes the local server to terminate? Is it a timeout? Can I influence it?
My goal would be to have a "constantly running" local server on the machine.

**Comment by bamurtaugh** [comment]
Hey there! I believe this is addressed in https://github.com/microsoft/vscode-remote-release/issues/440 and https://github.com/microsoft/vscode-remote-release/issues/3096, so going to close this issue since the requests are being tracked there. But if your request is related to something else, please just let us know. Thank you!

**Comment by seen76** [comment]
Hi Brigit,

Can you please tell me, where can I change the timeout? I have read both of the mentioned issues, however there is no info provided how to change it.

Thanks,

Zsolt "seen" FARKAS

Technical fellow

+36 20 584 8084
