### ISSUE TITLE
"extension is enabled on [remote container] and disabled locally"

### ISSUE THREAD

**Issue by garthk** [microsoft/vscode-remote-release#2811]
My “local - installed” extensions list is a mess, with a good proportion of the extensions dimmed with a blue `(i)` icon and a tooltip "extension is enabled on [remote container] and disabled locally". Uninstalling and re-installing the extensions does not help. Installing Insiders for the first time comes up with a fresh configuration and still shows the problem.

- VSCode Versions: 1.44.2, 1.45.0-insider
- Local OS Version: macOS 10.15.4 (19E287)
- Remote OS Version: Linux
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

* Open extensions panel
* Observe extensions are enabled
* Hover over green corner icon of one extension
* Observe “This extension is enabled globally.”
* Remote Containers: Reopen in Container
* Open extensions panel
* Open local - installed group
* Observe previous extension is greyed out
* Hover over green corner icon of extension
* Observe "extension is enabled on [remote container] and disabled locally"

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by egamma** [comment]
I assume this is the expected behaviour pls see https://code.visualstudio.com/docs/remote/containers#_managing-extensions

>“This extension is enabled globally.”

This means it is enabled globally for all workspaces (this has nothing to do with remote).

> Observe "extension is enabled on [remote container] and disabled locally"

You must have installed the extension into the container. Since it is a workspace extension it can only run remotely and is disabled locally.

![image](https://user-images.githubusercontent.com/172399/79966053-2426d000-848d-11ea-8a6b-9e90e758706f.png)

This is the expected behaviour. Are there any problems with this or do you find this confusing an we should work on the wording?
