### ISSUE TITLE
Test: Regressions from WSL2 support

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2850]
Ref - #2779

- [x] linux @connor4312
- [x] macOS @mjbvz

Complexity: 4

---

Run the Smoke-Test (https://github.com/microsoft/vscode-remote-release/wiki/Remote-Containers-Smoke-Test) on the two non-Windows platforms and test basic operations using `Remote-Containers` commands and the Remote Explorer to ensure there are no regressions from the rework for WSL2.

**Comment by connor4312** [comment]
There's no "Forward Port from Container" command:

![](https://memes.peet.io/img/20-04-867e3325-0803-49f5-9b14-860dcfc128c1.png)

"Forward a Port" works, but I have to manually look and type in the port from the "Forwarded Ports" view.

![](https://memes.peet.io/img/20-04-1a557367-1f69-4949-b398-d604cea3efae.png)

Unsure if the instructions are outdated or if it's a bug, let me know if you'd like an issue for this.

Smoke test passes otherwise.

**Comment by chrmarti** [comment]
@connor4312 The instructions need an update there. Thanks.
