### ISSUE TITLE
Rank newer versions higher

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-remote-release#2864]
re #2844

related to https://github.com/microsoft/vscode-remote-release/issues/2863

* see attached screen shot
* i'd say Node 12 should always come before Node 10

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/1794099/80486060-c85fb980-895a-11ea-96c1-604b0c7a1ff6.png">

**Comment by egamma** [comment]
fyi @Chuxel  adding meta data for this is likely overkill and the hope is that we do not have too many versions of a container.

**Comment by Chuxel** [comment]
The only ones in the list are currently supported LTS versions.  The reason the Dockerfiles have a pointer to a tag instead of "master" for the Dockerfile and readme is so that we can remove out-of-support versions from master in vscode-dev-containers and by extension this dropdown. Node has between 2 and 3 versions supported - v14 just got released so we should technically have three now.

That said, one of the things I am generally wondering about is whether we should be consolidating the different version variants of the definition in favor of a build arg wherever possible.

The "python 3" definition actually supports 3, 3.6, 3.7, and 3.8 with some enhancements I added to the build system and the addition of build args into the main extension.

I've been debating whether it would be better to automatically expand this so you can pick a specific version in this dialog, however.

**Comment by egamma** [comment]
This has been changed in the meantime. The recommendation no longer shows versions, but the user can then pick which version to install.
