### ISSUE TITLE
Inconsistent locale behaviour in extensions over SSH remote

### ISSUE THREAD

**Issue by jannek** [microsoft/vscode-remote-release#2884]
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:50:03.709Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-26-generic snap

Steps to Reproduce:

1. Create an extension which uses `Intl.DateTimeFormat()` or `Date.toLocaleDateString()` with non-default locale.
2. Open a remote connection and install same extension.
3. Remotely executed extension seems to always fall back to default locale (en-US)

Does this issue occur when all extensions are disabled?: Haven't tested - seems to occur in extension code.

**Comment by deepak1556** [comment]
This needs `full-icu` support from node , its only available from `v13.0.0` and higher https://github.com/nodejs/node/commit/1a25e901b7c380929f0d08599f49dd77897a627f

For electron, due to the way node is integrated, the v8 and icu component are shared with chromium, and it builds icu component with full i18n support.

**Comment by jannek** [comment]
That explains the behaviour observed. Are the any plans to upgrade remote Node to v13+ soon?

**Comment by deepak1556** [comment]
Node 14 is being used in remote since `v1.56`, it should have full-icu support by default.
