### ISSUE TITLE
WSL2 Default Workspace Binding Issue with DevContainers

### ISSUE THREAD

**Issue by NathanNZ** [microsoft/vscode-remote-release#2929]
- VSCode Version: 1.44.2 & 1.45.0 (Insider)
- Local OS Version: Windows 10 2004
- Remote Extension/Connection Type: Docker with WSL2

Steps to Reproduce:

1. Set up Dev Containers using the following template.

> https://github.com/microsoft/vscode-dev-containers/tree/master/containers/azure-functions-python-3

2. Create a requirements.txt with the single line below

> azure-functions

3. Update the devcontainer.json file with a postCreateCommand to install packages.

>  pip install -r requirements.txt

Outcome:

This will intermittently end up with one of the two errors occurring:

1. postCreateCommand does not work with the following error. Note that this did not seem to happen with the Stable build, and one could open a terminal in VSCode and access the /workspace/projectname folder without issue.

> OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "chdir to cwd (\"/workspace\") set in config.json failed: no such file or directory": unknown

2. Get the following error with no directory view possible and the /workspaces folder unmounted.
I found this to happen all the time in the Insider Build and intermittently in stable - notably upon a first run before I restarted my machine to ensure it wasn't due to switching Docker engines without a restart

> "The terminal shell CWD "/workspace" does not exist" 

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: Yes (excluding the Remote Extension)

**Comment by Chuxel** [comment]
//cc: @chrmarti

**Comment by NathanNZ** [comment]
I should probably clarify as I've reread my issue and noticed it's a bit ambigious.

I'm using the DevContainers functionality within Windows however the Docker agent (19.03.8) is set up to use the WSL 2 based engine.

I've switched back to using the older engine for now and that seems to be working as expected, so I assume this is a regression to how the workspace is mounted when the Docker Container is using WSL 2.

**Comment by PavelSosin-320** [comment]
Windows 10 ver 2004 with WSL 2.0 is out to GA is already a few days. Docker
Desktop ver 2.2.3 is built on the top of the 2004 pre-release. All users
will be with the same stack in the few days. WSL 2.0 gives a huge benefit
to the docker developers - POSIX filesystem compatible with Docker
specification. I had to make some adoptions in my Ubuntu distro to make
everything works smoothly but they are mostly know-how and how-to-do-it.
Now I have an entire stack including docker-compose and stack deploy. If
you have any questions you can ask me directly via mail.

**Comment by NathanNZ** [comment]
Hi Pavel.

I'm not using Ubuntu - I'm using the default Docker provided container environment. One of the benefits I enjoy with devcontainers is how it easy it is to set up an entire environment without having manual steps and tweaks, so ideally I'll be hunting for a method to be able to do that.

Looking through the Docker Desktop version history it does look like 2.3.0.0 fixes a couple of binding issues - so I'll hold fire for a GA of that and see how we go from there :+1:

**Comment by chrmarti** [comment]
@NathanNZ Could you append the DevContainer log from when it fails? (`F1` > `Remote-Containers: Show Log`)

**Comment by chrmarti** [comment]
@NathanNZ Also: Which version of Docker Desktop for Windows are you using?

**Comment by NathanNZ** [comment]
Apologies, I don't have access to that DevContainer log anymore as I have reverted to the older method of running Linux containers on Windows.

Regarding Docker Desktop for Windows was using 2.2.0.5. However as 2.3.0.0+ has a few fixes to binding that may resolve this issue I will wait for that to be released and see how we go from there, and report back if the issue still remains.

**Comment by PavelSosin-320** [comment]
@chrmarti 
@NathanNZ 
For me, Dockerdesktop & WSL 2.0 with Ubuntu solved the binding issues when I run Ubuntu image from WSL2 Ubuntu due to POSIX WSL nature: 
I created symlink in my Ubuntu for my Workspace for convenience
pavel@MSI:~$ ls -al /var/VSCODEWS in var because it is Unix standard place
and
I can bind/mount my $VSCODEWS using -v or --mount to any container because in the WSL2 based
`avel@MSI:~$ ls /mnt/c/Users/Pavel/VSCODEWS
Config.code-workspace  Dockerfile.txt          docker-compose.debug.yml
Dockerfile             VSCodeMapWorkspace.txt  docker-compose.yml
docker run -d -i -t--mount type=bind,source=/mnt/c/Users/Pavel/VSCODEWS,target=/vscodews

pavel@MSI:~$ docker run -i -t --mount type=bind,source=/mnt/c/Users/Pavel/VSCODEWS,target=/vscodews ubuntu
root@cae24c4a3496:/# ls /vscodews
Config.code-workspace  Dockerfile  Dockerfile.txt  VSCodeMapWorkspace.txt  docker-compose.debug.yml  docker-compose.yml
I don't see any issue with binding - **I see my workspace content from any place consistently**.
The correct volume drive is an offline discussion
`
