### ISSUE TITLE
user: override with numeric id is not picked up by provision process

### ISSUE THREAD

**Issue by hholst80** [microsoft/vscode-remote-release#2950]
![image](https://user-images.githubusercontent.com/6200749/81287420-03e93a80-9063-11ea-91c3-5f5e611cd2a9.png)

- Local OS Version: Fedora 32
- Remote OS Version: docker.io/gradle:jdk8 container
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

Start a gradle container using the following docker-compose.yml script:

docker-compose.yml

```
gradle:
  image: gradle:jdk8
  command: ["sleep","inf"]
  user: 1000:1000
```

Attach to the running container. It will try and provision using `root` and not pick up on the uid:gid override.

Replace with `user: gradle` and it works as expected. 

The remote provisioning script should also work with `user: 1000:1000`.

**Comment by Chuxel** [comment]
I'm not sure what would be going on there since this would be managed by Docker Compose.  This is the user you are connecting as, however, so try `1000` instead of `1000:1000` assuming that's the UID of the user in the gradle image.

That said, if you're asking about automated UID/GID changes, that is not supported for Docker Compose. That's feature request https://github.com/microsoft/vscode-remote-release/issues/2228 if you'd like to upvote.

**Comment by chrmarti** [comment]
Seems to work now. Probably fixed by https://github.com/microsoft/vscode-remote-release/issues/3428.
