### ISSUE TITLE
remoteUser in devcontainer.json doesn't work in corporate environment

### ISSUE THREAD

**Issue by clssn** [microsoft/vscode-remote-release#2957]
Issue Type: <b>Bug</b>

Reason: users are not listed in /etc/passwd because they are taken from a corporate domain controller via sssd. 
Potential solution: use `id -u username` and `id -g username` to determine the user's uid/gid.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 4.15.10-041510-generic
Fetching remote diagnostics for 'Dev Container: C++' failed.

**Comment by SirFerdek** [comment]
Hi,
I thought I was doing something wrong when configuring my `devcontainer`, I missed a critical line in the documentation *once again* ;) or it's not supported with WLS2 and couldn't figure out why [Developing inside a container on a remote docker host](https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host)  did not [automatically update my UID and GID as described.](https://code.visualstudio.com/docs/remote/containers-advanced#_adding-a-nonroot-user-to-your-dev-container)

Turns out I hit the exact scenario as described by @clssn - my username does not exist in `/etc/password` on the remote host as it is recevied via sssd. I think the proper way to obtain numerical UID and GID in this environment would be to use something like

```
getent passwd USERNAME
```

It's a pity we cannot see the source code to fix this ourselves... ;) But well, the issue still exists and it cost me 6 hours of dev time. You guys probably have a lot on your plate either way, but is there any small chance this could be fixed in, like, next year maybe? :D

**Comment by chrmarti** [comment]
Updating to use `getent passwd <user>` in Dev Containers extensions 0.300.0-pre-release.

**Comment by Alwaysproblem** [comment]
it is worked for me with version `v0.300.0`, Thanks @chrmarti

**Comment by akkuman** [comment]
> `getent passwd <user>`更新以在开发容器扩展 0.300.0-预发行版中使用。

getent passwd <user> error ret code 2

but sudo getent passwd <user> success

env:
ubuntu + samba AD

**Comment by romankarlstetter** [comment]
I have a problem with this change. Our setup: windows domain controller with opensuse linux hosts. User name on linux host has the following format:
`DOMAINNAME\username`, i.e., it contains a backslash. 

As a consequence, `getent passwd DOMAINNAME\username` fails with return code 2.

One of 
`getent passwd "DOMAINNAME\username"` or 
`getent passwd DOMAINNAME\\username` 
would work.
