### ISSUE TITLE
Set up environment on remote host (module load)

### ISSUE THREAD

**Issue by Flamefire** [microsoft/vscode-remote-release#2982]
I'd like to use VS Code to develop on our HPC cluster via the remote-SSH extension.

In short: The environment after SSH is minimal. Almost no software is available. To get that you need to issue 1 or more `module load <software>` commands which set up PATH/LD_LIBRARY_PATH and more. This `module` is a bash (or other shell) function.

So what I'd like to do: Specify commands to run before starting the remote VSC instance so it picks up the changed environment or alternatively modify the environment via a shell and reload the remote VSC in that environment.

Another solution would be to specify a (remote) file to be sourced before loading the remote VSC instance. This could then contain e.g. `module load <foo>` and `export FOO=bar` statements which the remote VSC will pick up.

**Comment by psakievich** [comment]
I would also add that I'd like to see an ability to load modules when running the debugger. Something in the launch.json like:

`"moduleList": ["package1", "package2"]`

**Comment by fteufel** [comment]
Hi, 
I'm facing the same problem on my HPC cluster. Specifically, I need to load python3 with `module load python3`. Because python3 is not available at the start of vs code, the python extension cannot recognize python3 and all the virtual environments, effectively making it impossible to use most functionalities of the extension.
See 
https://github.com/microsoft/vscode-python/issues/13313

**Comment by Zho-o-o-u** [comment]
Hi, I'm facing the same problem when using ssh remote host. Because python3 and virtual environments(conda) can't be recognized, I can't use python to deal with snakefile.

**Comment by Chuxel** [comment]
@roblourens This is sort of in the same class as #690

**Comment by roblourens** [comment]
You can also set this stuff up in a bashrc, does that help?

Also https://github.com/microsoft/vscode-remote-release/issues/1722

**Comment by chrisb2244** [comment]
@roblourens That's true (at least from my experience), but only helps if you're willing to semi-unconditionally (because you can still draw some distinction between login and non-login shells) run the command.
What if you want VSCode to always run the code, but when you SSH to the remote from a terminal you don't want the module loaded/command executed?

In the case of modules, you could just unload it interactively... but that's a workaround to a workaround.
