### ISSUE TITLE
"forwardPorts" conflicts with docker-compose port mapping

### ISSUE THREAD

**Issue by Foreverflying** [microsoft/vscode-remote-release#3025]
- VSCode Version: 1.45.1
- Local OS Version: MacOS 10.15.4
- Name of Dev Container Definition with Issue: forwardPorts conflicts with docker-compose port mapping

If we open a browser by auto launching after build (or by clicking an HTTP link maybe), which accesses port 8080, the vscode will try to map 8080 to a random localhost port and open the link with that port.

If we want it to mapping to a fixed port, we need to add a line `forwardPorts: [8080]` in devcontainer.json. Then when container get created, vscode will add a "8080:8080" mapping to the container, and open the link to port 8080 with port 8080.

**however, when devcontainer.json indicates to start a container with a docker-compose.yml file, and the port mapping 8080:8080 is already set, the forwardPorts config seems not work anymore, I guess it tries to do the mapping but fails due to the port is in use.**

In this case, when you open a link to port 8080, the vscode will map it to a random port rather than 8080, even the forwardPorts is set to [8080].

Steps to Reproduce:

1. Add forwardPorts in file .devcontainer/devcontainer.json, mapping the same ports in docker-compose.yml as well.
2. From vscode, launch a browser by a url with that port.

**Comment by PavelSosin-320** [comment]
[This is the usual service mesh behavior ](https://docs.docker.com/engine/swarm/ingress/)
Single ingress instance should be able to access running Service container by node and port. Combination of node-port should be unique, i.e. random

**Comment by Foreverflying** [comment]
> Yes, if the port is already in use locally - which would be the case here - forwarding works but uses an alternate port. For example, you may be running a server on your local machine for that is taking up the port, so it uses another one. That's the expected behavior. Is this causing a problem for you?

Thanks!

Yes this feature may be useful, except for:

when setting `forwardPorts = [8080]`, the user's intention is really to tell vscode "I hope port 8080 maps to 8080, so please don't map it to another port, thank you".

So I guess the correct way is, when `forwardPorts` set, even vscode tries to map the port again and fails, it shall assume the user has done this mapping himself, so not to choose anther random port.

**Comment by PavelSosin-320** [comment]
The description How to bypass Swarm mesh networking logic is provided in the same document mentioned in my previous comment. The purpose of Composefile v 3 > is to support the Service deployment.  Docker stack deploy uses the same compose file with some extensions introduced after v2. Placement option allows deploying the stack which consists of a single container to the desired node with the desired networking model. Long port publish format with published and target options are always at your disposal.

**Comment by Chuxel** [comment]
@Foreverflying `forwardPorts` is acutally different than the port publishing that is in Docker Compose.  This is the `appPort` property in `devcontainer.json`. 

Publishing is done using Docker - it exposes the port on the Docker network, but the application inside the container needs to be listening on all ports.  `forwardPorts` does not have this limitation.  It can handle localhost and be done dynamically.  It's designed to allow you to do something during development that you may not even want to expose in your production environment.  That's why you are seeing this behavior.

**Comment by PavelSosin-320** [comment]
Expose definition in Compose-file has really universal meaning because it works in a very different networking scenario: It works in the scope of docker daemon on the local machine - exposes container's port to other containers, it exposes the port to other processes on the same machine, it exposes container's port to container's running on other nodes managed by the same orchestrator, it exposes container to the external load balancer without or minimal configuration. 
I created my own repository service and tested lost all these scenaria.
If necessary, service can be easily updated, including expose definition while running without a rebuild of the stack's images.
Why not use such a reliable and proven mechanism?
If expose definition

**Comment by Foreverflying** [comment]
@PavelSosin-320 Thank you for your reply! I think I've got what you are talking about now, and I agree with you.

**Comment by Foreverflying** [comment]
@Chuxel Thank you!

According to your comment, now I understand the `forwardPorts` is totally different mechanism with the docker port mapping.

However, I still insist this behavior will lead misunderstanding, maybe to make the `forwardPorts` an optional parameter is a better choice:
1. when `forwardPorts` not set, vscode will not forward ports at all.
1. when `forwardPorts` set to "8080:80", vscode will forward 8080 to 80.
1. when `forwardPorts` set to "8080:*", vscode will forward 8080 to a random port.

And if another parameter (say `containerPortMapping`) can be added, it will solve the scenario:

- For some reason the docker-compose file need to expose ports like "8080:8080".
- The user want to open the browser with 8080 rather than other ports.
- The user knows the port has been mapped by docker port mapping, so they are listening on 0.0.0.0 in the container.

Or if the vscode can detect the port mapping in the container, it's even better, we do not need to set a same mapping in 2 different configurations.

BTW, I tested `appPort` but it seems not working, so I assumed it's not for this purpose.

**Comment by PavelSosin-320** [comment]
Hi Chuck! Please be patient! It works but the simple truth is that changing
port mapping for running containers is impossible, yet(?). To change the
port mapping for service the service has to be scaled down and, then scaled
up back. The newly created task gets the correct port mapping according to
the new service definition. The single container service is a very special
case in which dynamic re-scaling is impossible 😕

**Comment by PavelSosin-320** [comment]
The reason why container must have a port mapping in any orchestration
scenario is simple - SSL termination. This function is implemented by all
Ingresses out-of-the-box by the specification. The simplest case is mapping
port 443 used for communication with the remote client to port 80 used for
communication between ingress and container inside the cluster. Otherwise,
every microservice has to implement full security requirements for every
protocol, http/s ws/s . This is really dumb requirement. Using TLS inside
the cluster also speeds down communication between ingress and containers.

**Comment by Chuxel** [comment]
@Foreverflying Since Docker Compose has its own mechanism in place `appPort` property is for using a straight Dockerfile. We actually describe this in [our docs](https://code.visualstudio.com/docs/remote/containers#_forwarding-or-publishing-a-port). If this is set, you don't need to do anything else. The idea behind port forwarding is to forward something that you wouldn't add to your compose file or to forward while the container is already running.

The core problem here I think is when a port is forwarded to something other than the port it is in the container. Auto forwarding is something we've considered doing, but the behavior of mapping to a different port would still remain - not port forwarding when something is published can lead to an even more confusing behavior of applications listening on localhost not working. However, I do think we can provide a notification in this case to help alleviate the confusion.  There is also a scenario where the port is already in use locally outside of Docker itself that can cause confusion here. This is https://github.com/microsoft/vscode-remote-release/issues/2249.  Make sense? //cc: @chrmarti 

@PavelSosin-320 The discussion here is about straight Docker Compose, not Swarm or Kubernetes which do not have specific support in Remote - Containers today beyond attach.

**Comment by Foreverflying** [comment]
@Chuxel I agree if a feature that provided by default doesn't serve anymore, that would bring more confusing, but I think it's still possible to give a way to explicitly disable  it, like
`forwardPorts = []`

**Comment by Chuxel** [comment]
> I agree if a feature that provided by default doesn't serve anymore, that would bring more confusing, but I think it's still possible to give a way to explicitly disable it, like
`forwardPorts = []`

So, currently not specifying `forwardedPorts` should not result in a problem here. So, just omitting the property should do what you ask.  Or are you seeing a different behavior unrelated to the property?

**Comment by PavelSosin-320** [comment]
As it is emphasized by docker documentation the container's port mapping is totally deployment consideration based on availability, accessibility (firewalls, protocol defaults from the frontend, and backend sides ! ). Docker container doesn't do any port forwarding or publishing to the outside world - it is done by the infrastructure of the node / VM on which docker-engine runs Docker desktop uses Linux VM to run Docker daemon. Ports published by the container can be re-mapped by the proxy or load balancer installed on the same hardware node or external **with no restrictions**!

**Comment by Chuxel** [comment]
@PavelSosin-320 Our forwarding is via a VS Code mechanism that works as long as it has a connection to the container. Docker does not forward but publish. See [here](https://code.visualstudio.com/docs/remote/containers#_forwarding-or-publishing-a-port).  I'd like to keep this conversation focused on @Foreverflying 's concerns if possible - you seem to be discussing a different consideration.

**Comment by Foreverflying** [comment]
> So, currently not specifying forwardedPorts should not result in a problem here. So, just omitting the property should do what you ask. Or are you seeing a different behavior unrelated to the property?

If not specify `forwardedPort`, only one side effect:

When you trying to open a browser from a link in vscode, it will always open it with a different (and random) port. This is annoying especially when you have already do the port mapping yourself with container support. So, if just provide a way to explicitly disable the port forwarding feature of vscode, open exact `http://0.0.0.0:8080` with the browser when you clicking a link `http://0.0.0.0:8080` (no matter if succeed of not), that will help.

Thank you for your patience!

**Comment by PavelSosin-320** [comment]
Port mapping at the container level says about HTTP port which shall be used by the browser just nothing because it is low-level protocol mapping: TCP, UDP, etc. It is intended for exposure of containers to the Docker network! The application can be exposed to the browser only via Node or Service ports because it is absolutely impossible to create DNS record based on in-cluster container's IP assigned by Docker without public IP. **Since any OS supports hosts file, at least**  Docker container mapping can't be used for the client access via HTTP.

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/1817
