### ISSUE TITLE
Test: postStartCommand and postAttachCommand properties

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#3051]
Refs: #2772

- [x] anyOS @mjbvz
- [x] anyOS @eamodio

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%233051%0A%0A)

---

- The `postStartCommand` and `postAttachCommand` properties can be used in 4 different cases (see [instructions](https://github.com/microsoft/vscode-remote-containers/blob/master/CONTRIBUTING.md#testing-remote-containers)):
  - Single container.
  - Single container from Git repository.
  - Docker Compose.
  - Attach to existing container (`postAttachCommand` only).
- Verify `postStartCommand` is only run when the container was (re)started. Note that by default the container is stopped after the last window disconnected (not in the 'attach' case), but only after 10 seconds (to speed up window reloads).
- Verify `postAttachCommand` is always run when the window connects (aka 'attaches') in all 4 above cases.
- The property value can be a string or an array of strings. A string is run in a `/bin/sh`, an array is run as a command with parameters without shell.

**Comment by mjbvz** [comment]
@chrmarti It's not clear to me how to configure `postStartCommand` when I attach to an existing container?

For the other cases, it seems like the new properties work as expected

**Comment by PavelSosin-320** [comment]
Docker spec implements the classic Observer design pattern via Docker events API
If VSCODE Dev container is a docker container it inherits this API automatically from the Docker engine. Since the observer pattern is the blueprint for Promise every Docker API operation creates a promise resolved when the corresponding Docker event is raised. 
When the build new image operation promise is resolved new image can be run or pushed to the local repository.
Upon the container has started or replicated i.e. in the running state it can be attached
When the Attach promise is resolved a first terminal operation can be started.
When the operation is finished a next operation can be started.
Until no more operations in the queue or Container detached/exited event reported by the Docker engine. Thus no more operations can be submitted. Any attempt to submit operations causes rejection of its promise.
Such behavior of clients is assumed by the Docker engine and client libraries.
So, from the Docker point-of-view  there are very few Observable's events exist and promise chain is very simple:
1. Pre-operation - Operation's promise is created; Error in pre-operation causes Promise's reject
2. Post-operation success. i.e. Expected Docker event is received. Error in post-operation causes Promises chain reject.
3. Post-operation reject - any Error event is received or timeout.

**Comment by chrmarti** [comment]
@mjbvz `postStartCommand` is not supported when attaching to an existing container. Thanks!
