### ISSUE TITLE
When opening a PHP container, PHP debug extension is not automatically installed into the container

### ISSUE THREAD

**Issue by rspiewak47** [microsoft/vscode-remote-release#3148]
When connecting VS Code to a running container which has PHP code, it becomes necessary to install the PHP debug extension into the container manually. This should be detected and done automatically.

**Comment by Chuxel** [comment]
This is why we have some pre-defined development containers. Open your folder, and select **Remote-Containers: Add Development Container Configuration Files...** select PHP. More details on extension management can be found here: https://code.visualstudio.com/docs/remote/containers#_managing-extensions

**Comment by chrmarti** [comment]
There are also recommendations for extensions in the Extensions viewlet based on the files you have in your workspace. We try to avoid doing too much extras automatically because that is not always what users want or expect.

Closing as we have the pre-defined dev containers for this (see above comment).
