### ISSUE TITLE
Improve error message workspace folder is not shared. 

### ISSUE THREAD

**Issue by Jerry-Chow** [microsoft/vscode-remote-release#315]
Hello,
I have download the code and vscode insiders and Remote Development extension but it showed failed Please help me check it , thanks
![image](https://user-images.githubusercontent.com/13084763/57532543-d2b62b80-7376-11e9-8ada-059da767cc55.png)

**Comment by marco-m** [comment]
@chrmarti The fact that this extension requires to read `HOME/.gitconfig` is a security vulnerability. Consider the following:

- It is not possible to tell vscode: I don't want you to bind mount `$HOME/.gitconfig`
- As a result, anybody using this (BTW wonderful) extension will configure their Docker engine to allow sharing the `HOME/.gitconfig` file.
- It turns out that the UI of the Docker engine, at least on macOS, does NOT allow to specify a file for bind mount, it wants a directory
- Then, the user will tell the Docker engine to share his own home directory.
- The problem with this is that this sharing is global! It is not limited to a given Docker image I have control of or I trust. ANY Docker image ever I will run on my computer will have access to my home directory forever, wether I use vscode or not.
- Even If I uninstall vscode, this global setting in Docker engine will stay there forever.

So please consider giving people
- a way to disable bind mounting `.gitconfig`, no matter where it is.
- a way to specify an alternative location for `.gitconfig`, so that I can have the comfort of doing git operations in the container and at the same time keep my home directory safe.

thanks!

**Comment by chrmarti** [comment]
We changed this to copying the .gitconfig to the container instead of mounting. (You currently need VS Code Insiders to get that update - until VS Code 1.36 is out which will get it too.)

I'm not sure I understand though: A container only has access to those file/folders on the host machine that are explicitly mounted when the container is created - not everything that is available for mounting. Am I missing something?

(Closing because the error message is accurate now that we no longer mount .gitconfig.)
