### ISSUE TITLE
[Remote - SSH] Allow sending WOL magic packet via settings

### ISSUE THREAD

**Issue by niccolomineo** [microsoft/vscode-remote-release#3162]
I haven't seen this requested before: it would be nice to have a per-connection group of settings to send the WakeOnLan magic packet as soon as the extension attempts to connect with the remote server.

**Comment by jwbee** [comment]
Since this is a high-ranking Google search result for the topic, here is how I solved this. Instead of making Code do this, I fixed it at the SSH level. SSH can exec any command before connecting, so for my dev box I added a line to .ssh/config `Match host myhost exec "wakeonlan -i my_address my_mac_address"` . It only solves the particular case of a user with one main remote session, and the details would need to be tweaked for your platform if you are not running Code on a Mac, but I hope it helps a few people.
