### ISSUE TITLE
VS Code can't choose Python interpreter

### ISSUE THREAD

**Issue by liualexiang** [microsoft/vscode-remote-release#3227]
I'm using Windows 10 WSL (Ubuntu 18.04 and Ubuntu 20.04) with VS Code, I've installed python3 on both 18.04 and 20.04, however, I can't choose Python interpreter.
[https://raw.githubusercontent.com/liualexiang/images/master/choosepython.jpg](url)
There is an option for me to choose "Python Interpreter", however, even if I click it and choose the correct python, it still asks me  "Select Python Interpreter". I confirmed I've clicked it. The settings.json:

```
{
    "workbench.colorTheme": "Monokai",
    "python.defaultInterpreterPath": "/usr/bin/python3",
    "python.pythonPath": "/usr/bin/python3",
    "python.terminal.launchArgs": [
    
    ]
}
```

I tried to re-install VS Code and the python extension, restarted computer, tried both WSL 1 and WSL2, tried Ubuntu 18.04 and 20.04, the issue still exist.

It confused me quite a while, Is there someone could help me? Many appreciate.

**Comment by liualexiang** [comment]
I'm using Windows 10 WSL (Ubuntu 18.04 and Ubuntu 20.04) with VS Code, I've installed python3 on both 18.04 and 20.04, however, I can't choose Python interpreter.

There is an option for me to choose "Python Interpreter", however, even if I click it and choose the correct python, it still asks me  "Select Python Interpreter". I confirmed I've clicked it. The settings.json:

```
{
    "workbench.colorTheme": "Monokai",
    "python.defaultInterpreterPath": "/usr/bin/python3",
    "python.pythonPath": "/usr/bin/python3",
    "python.terminal.launchArgs": [
    
    ]
}
```

I tried to re-install VS Code and the python extension, restarted computer, tried both WSL 1 and WSL2, tried Ubuntu 18.04 and 20.04, the issue still exist.

It confused me quite a while, Is there someone could help me? Many appreciate.

**Comment by liualexiang** [comment]
[](url)

**Comment by liualexiang** [comment]
The VS code python interpreter works will on Windows 10. It's quite strange

**Comment by liualexiang** [comment]
when I add a new workspace or a new folder in the workspace, I can choose WSL python interpreter then.
So I installed a extension named "WSL workspaceFolder" in WSL VS Code extension, then the issue was resolved.

**Comment by tahzabbani** [comment]
I've also been having this problem with WSL and VS Code. Where can I find that settings.json file exactly?

**Comment by iamjohnnyli** [comment]
I have the same issue. When using WSL, when I type `code xx.py` I can't choose a python interpreter.
![image](https://user-images.githubusercontent.com/5987932/93283697-e8ffa300-f785-11ea-9d4d-f7aba96cb0aa.png)
But if I open the folder from menu, VS Code can find the correct python interpreter.

**Comment by LongBeachHXC** [comment]
So I was having this same exact issue until I read this [article](https://code.visualstudio.com/docs/remote/wsl-tutorial) on a wsl tutorial. In there it says we should have "Remote - WSL" extension installed (already did). In the bottom left corner "Remote - WSL" installs a status button that has the "greater than" and "less than" symbols displayed. If you click that button and tell VSCode to open up in the remote WSL distro environment it fixed my issue where vscode was unable to find an interpreter for python. Glad I was finally able to fix this as it was a bit annoying

**Comment by bamurtaugh** [comment]
I'm glad to hear the issue was resolved for folks and that the tutorial [here](https://code.visualstudio.com/docs/remote/wsl-tutorial) was helpful. 

When I take a look at my `settings.json`, the only Python-related setting I have is: `"python.pythonPath": "/usr/bin/python3",` which is the path to the version of Python I have installed on my WSL instance (I have Python 3 installed on my WSL distro and use Python 2.7 on my local machine). The recommended workflow (that should work out-of-the-box) is to install Python in your WSL distro, open VS Code from a WSL terminal using `code .` in your chosen Python app's directory, install the Python extension, reload VS Code, and install any other relevant tools like a Python linter. The steps are outlined in the [linked tutorial](https://code.visualstudio.com/docs/remote/wsl-tutorial#_python-development). 

Regarding how to locate your `settings.json`: you can open the command palette (Ctrl + Shift + P), type "settings," and then select either the general settings or WSL-specific settings:

![image](https://user-images.githubusercontent.com/25310137/98607225-9af6af80-229d-11eb-9cf4-74edd1afe747.png)

Since it sounds like folks were able to get this working, going to close the issue, but please let me know if you're still running into any trouble or have questions or feedback about the above. Thank you!

**Comment by AltfunsMA** [comment]
Not sure if this is similar or a completely different problem.

I'm using VS code to ssh into a remote machine with various python installations, one venv and two workspaces: A and B. A has several folders, B only one. 

The venv with 3.8.2. which is sitting in the folder under WS B is being used as a default, whenever I launch anything on WS A and I can't change it to any of the Python installations I have (2.7, 3.6, 3.9). All appear for selection, and I can click on them; but nothing happens. I can run them in a Jupyter notebook within the Workspace but if I send anything to the terminal, it's the 3.8.2 that appears. I have checked Python: Python Path in User, Remote, Workspace and every single folder setttings; they're all set to "python"

Weirdly, Workspace B does let me change interpreters without problem. The settings look identical to Workspace A except there are no folder settings of course.

I've reinstalled the whole python extension to no avail, and I'm a bit lost as to what the problem might be.
