### ISSUE TITLE
Can't start Live Share session when using dev container

### ISSUE THREAD

**Issue by ahayzen** [microsoft/vscode-remote-release#323]
- VSCode Version: 1.34.20-insider (57b550c559b945eb9d871dbf2b2e4cb9e31e2551)
- Local OS Version: Ubuntu 18.04.2
- Remote OS Version: Debian 9
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Setup a dev container with `ms-vsliveshare.vsliveshare` in the list of extensions to install
2. Open the dev container
3. Notice that "Live Share" is available at the bottom of the app, click on it
4. This launches the web browser session, follow the instructions to sign in. Once this has been completed the browser states that the VSCode session is ready.
5. Go back to VSCode and notice how it is stuck on waiting for the code (when doing this locally this is automatic)
![Screenshot from 2019-05-14 22-47-38](https://user-images.githubusercontent.com/3669750/57734996-27b9b080-769b-11e9-9764-37defb7d6ce6.png)
6. I tried copying the code from the url in the web browser and entering this but then VSCode states "Starting collaboration session: Could not connect to the server. Check that you are connected to the internet.".  However I do have a connection to the internet and from the containers terminal I am able to ping web addresses.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: n/a

**Comment by Chuxel** [comment]
@ahayzen The Live Share team has plans to improve the remote experience over time. Right now you need to click the "Show Code" in the sign in page to get the code that is pasted in here. 

It should work at that point, but from what you describe, it may not be for some reason. The Live Share repository (https://github.com/MicrosoftDocs/live-share) is the right place to log it the issue so that team can look into it.

**Comment by Chuxel** [comment]
@ahayzen Since I couldn't transfer, I created https://github.com/MicrosoftDocs/live-share/issues/2101
in the correct repository.
