### ISSUE TITLE
Containers: Command to clone repo in contianer

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-remote-release#3292]
Testing #3265

It would be nice to have a command to perform the "Clone repo in container" action, analogous to the "reopen in container command"

**Comment by deepak1556** [comment]
Yeah this could be helpful, when the prompt appears to enter the github branch, I had to briefly unfocus the window which causes the prompt to go away thereby nullifying the `Clone in volume` step. I had to reload the window to bring back the notification to restart the process.

**Comment by chrmarti** [comment]
There is the `Remote-Containers: Open Repository in Container...` command. It might be hard to find because the wording is different. Would it make sense to change the command's name to `Remote-Containers: Open Repository in Volume...`? The notification could then say 'open repository in volume`, the button `Open in Volume` (instead of 'clone').

We could also prefill the repository URL for the command with the same logic we use for the notification and fall back to the current default if we cannot find one.

/cc @egamma

**Comment by deepak1556** [comment]
That sound good to me, seems consistent.

**Comment by chrmarti** [comment]
One issue I see is that we usually use (Open Folder..., Reopen...) '... in Container' and not '... in Volume'.

On the notification it makes sense to say 'in Volume' for short because that is the main difference we are offering.

**Comment by chrmarti** [comment]
The command is `Clone Repository in Container Volume` now, hopefully hitting all the right keywords. Closing as fixed.
