### ISSUE TITLE
Reopen notification mentions folder contains dev container config, even in the repo container case

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#3293]
Testing #3268 (and #3218)

A bit of a polish item.

Now that `onStartupFinished` has been adopted, I noticed that we show a reopen notification when opening a folder locally that has a repository container like those you can now configure locally (#3218). Which is great!!

The only issue is that the notification mentions that the folder **contains** a container configuration file which isn't the case in this scenario. We could say something like, "a container configuration is available for this folder," instead since that makes sense in both cases.

**Comment by chrmarti** [comment]
There are two variations at the moment. For built-in configuration:
![image](https://user-images.githubusercontent.com/9205389/86211835-43ba3300-bb77-11ea-9ebb-109765b59d55.png)

Configuration in the folder:
![image](https://user-images.githubusercontent.com/9205389/86211923-6a786980-bb77-11ea-8b65-5178da2c6c4b.png)

**Comment by egamma** [comment]
It would be good when the notification provides some more information about where this configuration file is coming from. 

Could we add some inline link that provide information about where this devcontainer is coming from:
```
There is a Dev container configuration available for this repository in the <link>definition repository</link>. Use 'Reopen in Container' to develop in a container. (
```

**Comment by Chuxel** [comment]
@chrmarti Okay, the issue must be the intersection of these two features then.  I created my own user-defined "repository container" configuration locally which is where I saw this happen.

If this appeared in that case, then we'd be ok:

![image](https://user-images.githubusercontent.com/312252/86272031-cac0d880-bb82-11ea-85a7-3d41f5264d05.png)

Erich's suggestion is good to - we could have a link that basically fires "Open Container Configuration File".

**Comment by chrmarti** [comment]
Wondering if we should put the link on 'definition repository' or 'Dev Container configuration'. If it opens the local devcontainer.json, it might make sense to have it on 'Dev Container configuration' because that is what it links to.

A:
![image](https://user-images.githubusercontent.com/9205389/86337373-4db06480-bc51-11ea-869d-3ce3b3ee85e4.png)

B:
![image](https://user-images.githubusercontent.com/9205389/86337482-72a4d780-bc51-11ea-90df-904bea426c76.png)

Maybe with that it would make sense to remove the reference to 'definition repository' and instead have a comment in these devcontainer.jsons saying where they come from:
C:
![image](https://user-images.githubusercontent.com/9205389/86337725-c9121600-bc51-11ea-958f-7ff3c8fef8f9.png)

Also: We don't have solution for the user to use a given configuration and adapt it. If they do, they will loose their changes when the extension updates next time. (We can now add local folders as lookup paths, but there is no guidance/support on how to get there.)

**Comment by chrmarti** [comment]
Filed https://github.com/microsoft/vscode-dev-containers/issues/392 as a follow-up.
