### ISSUE TITLE
Not all remote branches are shown when clone in volume

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode-remote-release#3294]
Testing #3265

* Have a git repository with multiple remotes
* Open in container and branch icon in status bar can show all remote branches available
* Clone in volume
* Only default origin remote branches are shown and any branch that was explicitly specified during clone.

**Comment by chrmarti** [comment]
It tries to use the current branch and looks up its tracking branch and remote. That should work if the branch is not the default branch and also if there are multiple remotes registered. It does not offer a list of options because the mapping from branch to tracking branch to remote is unique (or missing).

Does that not work?
