### ISSUE TITLE
Remote host changed message not helpful. 

### ISSUE THREAD

**Issue by MasonMcV** [microsoft/vscode-remote-release#3416]
The popup error when a remote host has changed is not helpful. It says the following:

![non-existent pipe message](https://user-images.githubusercontent.com/34190043/88333318-44b13100-cced-11ea-8285-48583926ccd3.png)

Here is the output in the output pane describing the known hosts issue. 

```
[14:00:45.359] > @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> 
[14:00:45.368] > @    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
> Someone could be eavesdropping on you right now (man-in-the-middle attack)!     
> It is also possible that a host key has just been changed.
> The fingerprint for the ECDSA key sent by the remote host is
> SHA256:DsU6Uj+M8KE9M7YJF9OeM9TrgvI8PqtCzeeT5Qzib1M.
> Please contact your system administrator.
> Add correct host key in C:\\Users\\mcvicmk/.ssh/known_hosts to get rid of this m
> essage.
> Offending ECDSA key in C:\\Users\\mcvicmk/.ssh/known_hosts:1
> ECDSA host key for 10.224.50.248 has changed and you have requested strict check
> ing.
> Host key verification failed.
> 
[14:00:45.377] > The process tried to write to a nonexistent pipe.
> 
[14:00:46.209] "install" terminal command done
[14:00:46.209] Install terminal quit with output: The process tried to write to a nonexistent pipe.
[14:00:46.209] Received install output: The process tried to write to a nonexistent pipe.
[14:00:46.210] Resolver error: The process tried to write to a nonexistent pipe
[14:00:46.216] ------
```
The pop-up should give a message about how the remote host has changed and potentially give instructions on how to fix the issue, as was provided in the output message.

**Comment by roblourens** [comment]
Better handling for this actually exists, but I spot a bug.

**Comment by RMacfarlane** [comment]
@roblourens Is there an easy way to verify this?

**Comment by roblourens** [comment]
- Open your `~/.ssh/known_hosts` file
- Find the entry for some host that you want to test
- Replace the host key fingerprint (everything after the host IP address on that line) with this other valid but incorrect host key fingerprint: `ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFag2UPujfDHQC6AGxIYXYBT+Eq3dkJwsw329j+H6fDmuC12yTQF3SqY73fTBVA1Y8K/3eRevOVXiW3miebdKaE=
github.com,192.30.255.112 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==`
- Now try to connect to that host on Windows
- You should get an error that has a useful message like `Remote host key has changed, port forwarding is disabled`, rather than a generic error

**Comment by RMacfarlane** [comment]
Thanks, looks good!
