### ISSUE TITLE
Does not work if target is NixOS (reopen unresolved #649)

### ISSUE THREAD

**Issue by steeleprice** [microsoft/vscode-remote-release#3476]
- VSCode Version: 1.48.0-insider
- Local OS Version: Windows 10 - 20.04
- Remote OS Version: NixOS 20.03
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Remote-SSH: Connect to host that is NixOS (I have tried 19.03, 19.09 and 20.03)
2. let it fail
3. install nodejs
4. try again
5. read logs and punt:
![image](https://user-images.githubusercontent.com/88438/89471825-f449c280-d733-11ea-8113-9021327e85b7.png)

How else can I help? I am not a node expert.

**Comment by steeleprice** [comment]
Seems to be a dependency on node 12 now, not 10.
This will enable it to run in Remote SSH after failing:

1) ssh to remote NixOS box
2) nix-env -iA nixos.nodejs.12_x
3) discover the hashed directory installed in ~/.vscode-server-insiders/bin/
4) cd ~/.vscode-server-insiders/bin/d13d2fc56da7a2f8bcad4256212db0661fcbba45
5) rm -rf node
6) ln -s $(which node)
7) Retry VSCode Remote SSH

Hopefully this time it is a success for you, it's working on 3 machines for me.
this will replace the MS shipped node with a compatible running NixOS node

I'm leaving this open, because this should not be necessary as it's not in any other distro.

**Comment by sonowz** [comment]
Note that In #649, it is said that #103 will solve this issue, but unfortunately it is not resolved yet.

And also:

> 1. ssh to remote NixOS box
> 2. nix-env -iA nixos.nodejs.12_x
> 3. discover the hashed directory installed in ~/.vscode-server-insiders/bin/
> 4. cd ~/.vscode-server-insiders/bin/d13d2fc56da7a2f8bcad4256212db0661fcbba45
> 5. rm -rf node
> 6. ln -s $(which node)
> 7. Retry VSCode Remote SSH

This gets cumbersome because this process should be done every time vscode client gets updated.
I made a nix script to automate this. See just step 4 & 5 in this [vscode-remote-wsl-nixos](https://github.com/sonowz/vscode-remote-wsl-nixos) repo. This repo was intended for remote-wsl, but it also works for remote-ssh. For Insiders, `VSCODE_DIR` in the script should be changed.
