### ISSUE TITLE
can not connect ,but the password is right

### ISSUE THREAD

**Issue by Veng0923** [microsoft/vscode-remote-release#3484]

**Comment by behrens-cloud** [comment]
I "sort-of" saw something like this...however the issue was that the username was not correct.  vsCode kept defaulting to my windows user name instead of the name I provided in the config.  So, I ended up creating that new user on the remote device as a work-around.  Stilling trying to find a real solution.

**Comment by behrens-cloud** [comment]
> I "sort-of" saw something like this...however the issue was that the username was not correct. vsCode kept defaulting to my windows user name instead of the name I provided in the config. So, I ended up creating that new user on the remote device as a work-around. Stilling trying to find a real solution.

I got it working by placing the user name on the Host line as well, so now the line looks like this as an example:: **Host username@192.168.1.55**

**Comment by bamurtaugh** [comment]
Thanks for the insights @behrens-cloud. @Veng0923 are you still experiencing this? Do the comments above help your scenario?

**Comment by roblourens** [comment]
Please make sure the username is correct in your ssh config or was typed in
