### ISSUE TITLE
Migrate remote explorer contributed view to use Welcome views

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#3504]
We now have a better way to show welcome/getting started/empty content in a view with Welcome views. We should convert the remote extensions to use the better UX.

- [x] Containers
- [x] WSL
- [x] SSH

**Comment by alexr00** [comment]
For containers, when docker isn't running:
![recording (14)](https://user-images.githubusercontent.com/38270282/90031698-d2b18380-dcbd-11ea-8a16-091c3c7203fb.gif)
And when docker is running, but there are no containers (if no folder is open, the first button won't show).
![image](https://user-images.githubusercontent.com/38270282/90031731-dc3aeb80-dcbd-11ea-8ee6-25a7a3bed10b.png)

**Comment by alexr00** [comment]
Welcome views for WSL.

When WSL is not found:
![image](https://user-images.githubusercontent.com/38270282/90144936-b83fde80-dd7f-11ea-96f3-861258d60631.png)


When WSL is installed but there are no distros:
![image](https://user-images.githubusercontent.com/38270282/90144651-5f704600-dd7f-11ea-9c93-093bbef07804.png)

**Comment by alexr00** [comment]
For SSH:
![image](https://user-images.githubusercontent.com/38270282/90148421-98121e80-dd83-11ea-87e6-b14e837a7272.png)

**Comment by bamurtaugh** [comment]
This is a really great idea, thank you for implementing it! 

I wonder if we might want to adjust the wording when the WSL executable isn't found since users might not know what the "WSL executable" is and might think it's referring to the Remote WSL extension itself. Maybe something similar to the containers message, "Get started with Remote - WSL by installing the Windows Subsystem for Linux or by visiting the help section."

Or a couple other ideas: "WSL has not been installed..." "You haven't installed WSL on your machine..." or, "WSL executable not found. Get started by first installing the Windows Subsystem for Linux on your machine, or visit the help section to learn more."

Also, I recognize this issue is now closed, so I'm more than happy to discuss offline or in a new issue!

**Comment by alexr00** [comment]
@bamurtaugh feedback here is great! 

I've changed it to "Get started with WSL by installing the Windows Subsystem for Linux or by visiting the help view." As you say, it is more consistent with containers and a little more friendly.

**Comment by bamurtaugh** [comment]
@alexr00 That sounds great! Thanks for making this contribution, I think it will provide some really helpful insights to users.
