### ISSUE TITLE
Use the command what exchanges virtual environment like Anaconda on SSH connection

### ISSUE THREAD

**Issue by Bo0km4n** [microsoft/vscode-remote-release#357]
Currently, when using the ssh connection to remote host, we can't execute the command what exchanges environment: `conda activate hoge`. For example, pyenv, anaconda and more.
So I want to use the command line(bash) on VSCode's ssh connection.

**Comment by Bo0km4n** [comment]
Sorry my explanation is not enough. I indicate example case.

For example, I connect remote machine via SSH without VSCode, and use an Anaconda environment in this connection. In this connection, I can use the python libraries installed by Anaconda.
But, VSCode remote connection can't use Anaconda environment because can't use the Anaconda command or execute terminal. 

If using terminal is possible, I hope it.

**Comment by bkmagnetron** [comment]
@roblourens I think this is related to my issue.
I have created a conda environment for golang in WSL and added some custom variable in `env_vars.sh`, what it will do is that it will set the `GOPATH` and `GOBIN` whenever I activate the environment.
Assuming that I've activated the environment and also been able to `echo $GOPATH`, when I run `code .`, vscode opens in windows and connects to WSL vscode server but I can't install golang extension tools because it says `GOPATH` is not present.

**Comment by roblourens** [comment]
That's right, the remote environment will not be the same as your local environment. The right way to do this is to set these variables in your `.profile` or `.bashrc` or whatever, or to configure the extension without relying on environment variables. Assuming that's what this is about, I will close this issue.
