### ISSUE TITLE
Use WSL/bash ssh instead of openSSH

### ISSUE THREAD

**Issue by thkrishn** [microsoft/vscode-remote-release#359]
I was trying to set this up :
https://code.visualstudio.com/docs/remote/ssh#_getting-started

but Open ssh is not there on mu windows build; so is it possible to force vscode insiders to use WSL ssh (linux ssh)

Thanks

**Comment by pd93** [comment]
@thkrishn If you have WSL, then I assume you also have Windows 10. As long as you're running 1709 or later then you should be able to [follow these instructions](https://devblogs.microsoft.com/powershell/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709/) to install the OpenSSH optional feature. You can then use the `ssh` command via `cmd` or `Powershell` as you would in the WSL and use the Remote - SSH extension in VSCode.

**Comment by Chuxel** [comment]
@thkrishn WSL is also an emulation layer, so you perf may not be as good as using the native libraries.

**Comment by thkrishn** [comment]
@pd93  and @Chuxel Thanks
I still have the 1607 Version Once I get the update I shall try what you suggest

**Comment by pd93** [comment]
@thkrishn OpenSSH is definitely available in 1709. I couldn't find the official release notes for it, but there are [plenty of articles](https://www.ghacks.net/2017/12/14/windows-10-fall-creators-update-includes-openssh-client-and-server/) that reference its use in 1709. Plus the Microsoft blog post I already linked.

The documentation you linked is for Windows Server and only states that OpenSSH **is** present in Windows 10 1809, not that it wasn't present before that. The reason it uses 1809 as the example is because (until a few days ago) it was the latest release of Windows 10.

**Comment by Sumanai** [comment]
@pd93 
> OpenSSH
The problem with using OpenSSH is that you have to support two SSH client configurations — OpenSSH and ssh in the WSL.

**Comment by pd93** [comment]
@Sumanai Agreed. If you have requirement to use the WSL *and* Remote SSH then there is a config duplication problem. Much the same as the issue of two `.gitconfig`s for Git Bash and WSL. These is definitely a place for this feature. My point was just that you don't *need* the WSL to run Remote SSH if you're running 1709+.

**Comment by Chuxel** [comment]
Related to https://github.com/microsoft/vscode-remote-release/issues/448 which has implemented.

**Comment by nbdd0121** [comment]
I think this feature would be important, e.g. it's difficult if not impossible to use kerberos with Windows' ssh.

If you have admin access, you may compile and put the file under C:\Windows\System32\OpenSSH\ssh.exe as a workaround.
```C++
// SPDX-License-Identifier: WTFPL
#include <sstream>
#include <cstdlib>

int main(int argc, char** argv)
{
	std::stringstream builder;
	builder << "C:\\Windows\\Sysnative\\bash.exe -ic \"ssh ";
	for (int i = 1; i < argc; i++) {
		if (i != 1) builder << ' ';
		builder << "\\\"";
		for (char* v = argv[i]; *v; v++) {
			switch (*v) {
			case '&': builder << "^&"; break;
			default: builder << *v; break;
			}
		}
		builder << "\\\"";
	}
	builder << '"';
	return system(builder.str().c_str());
}
```

**Comment by jemerald** [comment]
Is it possible to use Git for Windows instead of Windows OpenSSH Client on Windows 10 machine?

Our company machine doesn't have option to install Windows OpenSSH Client. I have got Git for Windows installed, but looks like VS Code is hard-coded to use OpenSSH Client under Windows 10.

Is it possible to add a config to override the default ssh path?

**Comment by Chuxel** [comment]
@jemerald This is available in insiders and the SSH nightly extension.  You can set `remote.SSH.path` in settings.json to override the path.
