### ISSUE TITLE
Docker options - buildargs outdated after deleting .devcontainer folder and rerunning Add Config files

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#3618]
Testing #3603

- in an empty folder
- Run 'Add configuration files'
- Select 'Java'
- Select the Option 'Node'

-> the Buildargs in the Dockerfile are updated

- delete the .devcontainer folder
- Run 'Add configuration files'
- Select 'Java'
- Select the Option 'Maven'

The buildargs in the dockerfile is not updated and still has the Node option enabled

```
# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.138.0/containers/java/.devcontainer/base.Dockerfile
ARG VARIANT="14"
FROM mcr.microsoft.com/vscode/devcontainers/java:0-${VARIANT}

# [Option] Install Maven
ARG INSTALL_MAVEN="false"
ARG MAVEN_VERSION=""
# [Option] Install Gradle
ARG INSTALL_GRADLE="false"
ARG GRADLE_VERSION=""
RUN if [ "${INSTALL_MAVEN}" = "true" ]; then su vscode -c "source /usr/local/sdkman/bin/sdkman-init.sh && sdk install maven \"${MAVEN_VERSION}\""; fi \
    && if [ "${INSTALL_GRADLE}" = "true" ]; then su vscode -c "source /usr/local/sdkman/bin/sdkman-init.sh && sdk install gradle \"${GRADLE_VERSION}\""; fi

# [Option] Install Node.js
ARG INSTALL_NODE="true"
```

**Comment by chrmarti** [comment]
The `Dockerfile` is not modified only the `devcontainer.json`'s `"build"."args"` map is.

What is different with Option 'Node, is that its default in the `Dockerfile` is `true` and that is overridden by the `devcontainer.json` to be `false` initially and you then changed that with the UI. For Option 'Maven' the `Dockerfile` and `devcontainer.json` both initially agree it is `false`.

**Comment by Chuxel** [comment]
@chrmarti @egamma Yeah this is also a bit by design. Pre-built images ignore args in devcontainer.json. This allows us to do things like create a Python image with nvm, but no node in the image itself, but install whatever the latest lts version is when devcontainer.json is used. Developers that opt to use `base.Dockerfile` to fully customize their image will see the same behavior as they would using `Dockerfile`.

In this case, the defaults match mostly, but you'll note that the NODE_VERSION is "none" in the `base.Dockerfile` but "lts/*" in devcontainer.json. This allows developers to pick their preferred version given the Node install is quick and yarn is already in the image.

**Comment by egamma** [comment]
tsss, closing as a user error.
