### ISSUE TITLE
For empty folders: suggest all available container

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#3619]
Testing #3603

When running 'Add Configuration files on an empty folder' then we should suggest all dev container configs.

**Comment by RMacfarlane** [comment]
When running "Remote-Containers: Add Development Container Configuration Files..." on an empty folder I see a dialog saying to open a folder first. Is this expected now?

**Comment by rzhao271** [comment]
I don't get the dialog to tell me to open a folder first, but I wonder if I'm testing on a wrong version of the extension since "Show All Definitions..." still shows.

![devcontainerconfig](https://user-images.githubusercontent.com/7199958/101528186-d095c380-3943-11eb-9f6e-74d1274c8736.PNG)

@egamma can you provide some steps and expected output?
