### ISSUE TITLE
More verbose quick pick placeholder

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#3620]
Testing #3603

![image](https://user-images.githubusercontent.com/172399/91952509-38af8a80-ed01-11ea-9048-a250d17fa251.png)

'Select Features and Options'

- why mentioning both features and options? are these separate concepts? 

Suggest:

'Select the install options for the dev container'

Or we want to provide more context

'Select the install options for the 'Java' dev container'

Then the quick pick items do not have to repeat the 'Install' for each item or are there different verbs for an option?

![image](https://user-images.githubusercontent.com/172399/91954539-38fc5580-ed02-11ea-8446-d723ae32df11.png)

**Comment by chrmarti** [comment]
I chose the placeholder to be slightly more generic than just 'install' because I don't know what each item does. The items' labels then come from the Dockerfile.

Currently all options are installs (looking at the definitions). We could change the marker (currently [Option]) to [Feature] or [Install] and make the placeholder more specific. The only downside would be that we might end up with a second picker once we introduce options that are not installs.

/cc @Chuxel

**Comment by egamma** [comment]
@chrmarti is it intentional that the Option/Feature quick pick has no title? The Add Configuration Quick Pick has one and the title can provide more guidance

The Add configuration quick pick has a title:
![image](https://user-images.githubusercontent.com/172399/91964342-5126a180-ed0f-11ea-9a6d-3cc0f9f3147c.png)

**Comment by chrmarti** [comment]
An oversight, we should probably just keep the same one.

**Comment by chrmarti** [comment]
@Chuxel How about we use `[Install]` and drop the 'Install' from the label, e.g., `[Install] Azure CLI`, and keep `[Option]` unused for now (or I can already add a second picker for that). Having these tags/types in the Dockerfile will allow us to optimize the UI with one or two pickers depending on the feedback and experience we get.

**Comment by Chuxel** [comment]
@egamma @chrmarti Options may not always be about installing though - settings or defaults would also apply. There's actually one for docker-from-docker that is "ENABLE_NONROOT_DOCKER" that I plan to annotate. 

So, I kind of feel like we may want to leave `[Option]` as it is. If we did add an `[Install]` option, we'd want to look to see if an `[Option]` was also specified and prefix "Install" in that case.  I'd prefer not to have the two as separate drop downs.

**Comment by chrmarti** [comment]
I agree, updating to:

With only `[Install]` options (using Azure Terraform definition):
![image](https://user-images.githubusercontent.com/9205389/92095099-8a294980-edd5-11ea-81c8-64d3b92e26cd.png)

With one `[Option]` included:
![image](https://user-images.githubusercontent.com/9205389/92095757-5864b280-edd6-11ea-9331-20afec624b1a.png)

The order in the Dockerfile is preserved, not sure if that will always make sense since the order in the Dockerfile affects caching.

**Comment by chrmarti** [comment]
I see many definitions now have at least one option, there might be not much gain in adopting `[Install]` in this case except that `[Install]` might allow us to tweak the UI in the future (like having two pickers).

**Comment by chrmarti** [comment]
Also including the config name in the placeholder as this gives context. (As suggested.)

Closing with that.
