### ISSUE TITLE
Idea: Add README.md badge for devcontainer projects

### ISSUE THREAD

**Issue by NikiforovAll** [microsoft/vscode-remote-release#3641]
It would be great if a user could add a prominent badge that tells that the project supports devcontainer approach. 

Something like: https://github.com/conventional-commits/conventionalcommits.org/blob/master/README.md

---
Sorry if this issue doesn't belong to this repo. Please close it in this case.

**Comment by Chuxel** [comment]
Love the idea!  Fortunately I can transfer to the right repo.  😀

**Comment by lsorber** [comment]
Also, please attach a hyperlink to that badge that starts VS Code, clones the repo, and creates the Dev Container. That would make starting development only one click away!

**Comment by jjonescz** [comment]
[Open VS Code](https://open.vscode.dev/) supports remote containers.

If you want to mention "container" in the badge, you can do something like this:

```md
[![VS Code Container](https://img.shields.io/static/v1?label=VS+Code&message=Container&logo=visualstudiocode&color=007ACC&logoColor=007ACC&labelColor=2C2C32)](https://open.vscode.dev/microsoft/vscode)
```

Which results in:

[![VS Code Container](https://img.shields.io/static/v1?label=VS+Code&message=Container&logo=visualstudiocode&color=007ACC&logoColor=007ACC&labelColor=2C2C32)](https://open.vscode.dev/microsoft/vscode)

Unfortunately, GitHub Markdown link syntax doesn't seem to support scheme `vscode://`, otherwise the link could be set directly to `vscode://ms-vscode-remote.remote-containers/cloneInVolume?url=https://github.com/microsoft/vscode`.

**Comment by jyasskin** [comment]
https://code.visualstudio.com/docs/devcontainers/create-dev-container#_add-an-open-in-dev-container-badge now explains how to add this badge.

**Comment by Chuxel** [comment]
Good point! Closing as complete!
