### ISSUE TITLE
Can't open WSL Directory while connected to a Windows machine through SSH 

### ISSUE THREAD

**Issue by glekner** [microsoft/vscode-remote-release#3719]
- VSCode Version: 1.49.1
- OS Version: Windows 10 2004

Steps to Reproduce:

1. Connect to a Windows machine through VS Code Remote SSH
2. Try to open a folder inside a WSL OS

![image](https://user-images.githubusercontent.com/24938324/93948678-b89ca380-fd47-11ea-86cf-01e12209686c.png)

Use Case:
Working on my laptop and its screaming, so I thought why not run webpack on my gaming pc which is in the salon.
the gaming pc runs Windows, but my project runs completely fine inside WSL, so I'm wishing to VS Code ssh into it :)

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by kieferrm** [comment]
You're connecting to the Windows box. What you can do instead is to directly connect to SSH inside of WSL. I thought we have docs for this but I can't find it right now. @bamurtaugh?

**Comment by glekner** [comment]
Its really a pain with port forwarding and per-distro settings, is there any easy way to ssh directly to wsl? @kieferrm @bamurtaugh

**Comment by bamurtaugh** [comment]
The posts [here](https://www.hanselman.com/blog/THEEASYWAYHowToSSHIntoBashAndWSL2OnWindows10FromAnExternalMachine.aspx) and [here](https://www.hanselman.com/blog/HowToSSHIntoWSL2OnWindows10FromAnExternalMachine.aspx#:~:text=How%20to%20SSH%20into%20WSL2%20on%20Windows%2010,Open%20the%20Firewall.%205%20A%20scripted%20solution%3F) appear to correctly explain a couple ways to SSH into WSL2.

Let me know if these help.

**Comment by PavelSosin-320** [comment]
I really wonder what is the "Remote connection to WSL" ? WSL VM has no stable IP address and accessible only from the host machine by design." . To connect to WSL client running on another host has to connect to the WSL's host, i.e. Windows machine. The host really knows the WSL VM IP because WSL switch is a part of its network:
ipconfig:

Ethernet adapter vEthernet (WSL):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::784f:43dc:3965:cf2a%50
   IPv4 Address. . . . . . . . . . . : 172.22.64.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :
...
Unlike the Hyper-V VMs WSL VM's IP is not published but its ports are published to the Host and it gives processes running inside this VM to listen requests from outside using NIC teaming, i.e. on IP 0.0.0.0 = eth0 & lo.

**Comment by glekner** [comment]
> The posts [here](https://www.hanselman.com/blog/THEEASYWAYHowToSSHIntoBashAndWSL2OnWindows10FromAnExternalMachine.aspx) and [here](https://www.hanselman.com/blog/HowToSSHIntoWSL2OnWindows10FromAnExternalMachine.aspx#:~:text=How%20to%20SSH%20into%20WSL2%20on%20Windows%2010,Open%20the%20Firewall.%205%20A%20scripted%20solution%3F) appear to correctly explain a couple ways to SSH into WSL2.
> 
> Let me know if these help.

@bamurtaugh @kieferrm The second link did the trick. however its a pain to maintain because of WSL2 dynamic IP. 
I guess fixing this issue https://github.com/microsoft/WSL/issues/4210 would make things alot easier for a lot of people.

**Comment by glekner** [comment]
I wrote an article to help whichever is in need - https://medium.com/@gilad215/ssh-into-a-wsl2-host-remotely-and-reliabley-578a12c91a2

Including automation everytime Windows boots.

**Comment by bamurtaugh** [comment]
Thanks for the updates here @glekner. We added a link in our docs to some info about this scenario as well (in the linked PR above).
