### ISSUE TITLE
Set Remote-WSL as a default open window

### ISSUE THREAD

**Issue by ridhwaans** [microsoft/vscode-remote-release#3790]
Remote-WSL is a useful feature that allows vscode extensions to operate in a Linux subsystem environment. Currently there is no way to launch vscode as a remote-wsl window from anywhere unless it is opened from inside WSL.  
Create an default launch option that's already connected to a default WSL distro such as ubuntu

**Comment by 10220323658274153** [comment]
Haloe World

**Comment by 10220323658274153** [comment]
> Haloe World

**Comment by bamurtaugh** [comment]
Hey @ridhwaans, just to ensure we're on the same page, you can open a Remote-WSL window in a few ways, such as through the Command Palette:

![image](https://user-images.githubusercontent.com/25310137/97510083-2e94bb80-1941-11eb-82ed-60d08110f4a3.png)

The Remote Explorer, opening a project from the recent menu, and launching `code .` in the integrated terminal.

Also, we're currently tracking https://github.com/microsoft/vscode-remote-release/issues/120 for automatically connecting to a remote host (like WSL), and since that sounds like the main ask here (from `Create an default launch option`), I'm going to go ahead and close this issue. Please let me know if I might've misunderstood your ask or if you have any other feedback!
