### ISSUE TITLE
.vscode-server/bin/<uuid>/bin not added to PATH on some remote Linux installations

### ISSUE THREAD

**Issue by sjdv1982** [microsoft/vscode-remote-release#3806]
- VSCode Version:  Latest (installed October 3)
- Local OS Version: Linux
- Remote OS Version: Linux
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

.vscode-server/bin/\<uuid\>/bin was not added to PATH, so that "code" was not found in the remote terminal, i.e. files could not be opened from the command line.

This problem is clearly a mismatch between vscode-server and the client machine. With two different vscode-remote installs and two different remote clients, the problem happened consistently on client 1 (an older Linux Mint installation) but not client 2 (Ubuntu 18.04).

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by mrvkino** [comment]
I have a similar issue on a CentOS Linux release 7.8.2003 (Core). I have Remote.SSH: Use Local Server to disabled.

When I open a terminal in my VScode connected to the remote server I do not have the path of the .vscode-server/.../bin in my PATH variable.

There is a local VSCode install on the server, I dont't know if this cause the remote server to not be added in the PATH variable.

If you need more information I can always add some.

**Comment by roblourens** [comment]
This should be added automatically to every remote environment. It's likely that you have a bashrc/profile or something else that overwrites the PATH.

**Comment by mrvkino** [comment]
I understand, but my question is if I only append to path in a `.bashrc` and `.bash_profile` what could stop vscode to append its path?

At the start of my .bashrc, I am using the classic `source /etc/bashrc`, then I append some path, set some alias, etc ...

If vscode is starting a shell and then adds its path why is it not showing when I type `env`?
This happens if I do nothing on my shell and type `env` as the first command. I do not ask vscode to run a command after opening a shell on the remote server. So I don't know what I can do to solve this.
