### ISSUE TITLE
Host / Remote files are not synced when using "Attach to running container ..."

### ISSUE THREAD

**Issue by kalote** [microsoft/vscode-remote-release#3815]
- VSCode Version: 1.49.3
- Local OS Version: Mac Catalina 10.15.7
- Remote OS Version: php:7.2-apache
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Create a folder "src/index.php" with 'bla' in it.
2. Create a ./Dockerfile with the following:

```
FROM php:7.2-apache
COPY src/ /var/www/html/
```

3. from terminal, run:

```bash
$ cd the/folder/with/the/code
$ docker build -t test .
$ docker run --name test -d -p 8080:80 test:latest
```

4. in VSCode, click the green bottom left icon and "attach to a running container ..."
5. Select the "test" container that is running
6. a new VSCode window opens with "open a folder". Click, select the "/var/www/html/" folder.
7. All modifications done in the container will not be reflected on the host code

Does this issue occur when you try this locally?: NA
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
There is no syncing of files, but you can mount your local folder from the container to achieve what you are looking for.

The easiest way to do that is by adding a `.devcontainer.json` (or `.devcontainer/devcontainer.json`) to your project folder:
```json
{
	"image": "php:7.2-apache",
	"workspaceMount": "type=bind,source=${localWorkspaceFolder}/src,target=/var/www/html",
	"workspaceFolder": "/var/www/html"
}
```

And then use `F1` > `Remote-Containers: Reopen in Container` while having that folder open locally.

Instead of `"image"` you can also reference your own `Dockerfile`, see https://code.visualstudio.com/docs/remote/create-dev-container for more.
