### ISSUE TITLE
Exposed Ports not visible in UI unless other ports are forwarded

### ISSUE THREAD

**Issue by aNickzz** [microsoft/vscode-remote-release#3876]
- VSCode Version: 1.51.0-insider (user setup)
- Local OS Version: Windows_NT x64 10.0.19041
- Remote OS Version: WSL (`uname -a` -> `Linux T5 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`)
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Use a dev container with
    1. no port forwarding configured,
    2. docker compose
2. Expose a port with the docker-compose file

    ```yml
    services:
      dev:
        image: ...
        ports:
          - 80
    ```

3. Open the "Remote Explorer" tab and view the "Forwarded Ports" section

Does this issue occur when you try this locally?: n/a
Does this issue occur when you try this locally and all extensions are disabled?: n/a

The port exposed by docker is not visible until in the UI until either a port is forwarded by vscodes `Forward a Port` command, or clicking the "Forward a Port" button.

![image](https://user-images.githubusercontent.com/15243523/96547735-26f76600-12f4-11eb-9c86-d4d7cbcbefdd.png)

![image](https://user-images.githubusercontent.com/15243523/96547900-6a51d480-12f4-11eb-87f1-0c19cfe9d367.png)

**Comment by aNickzz** [comment]
Additionally, (I'm not sure if this is worth a whole issue) is there a way have the "Existing Tunnels" link open to `localhost` (or some other domain) rather than `0.0.0.0` when clicked? as the latter doesn't resolve to localhost.

**Comment by aNickzz** [comment]
For further clarification, the reason why I'm not just using the `"forwardPorts"` setting is that I want to avoid port collisions when opening multiple projects at once that would otherwise all bind to port 80.

**Comment by chrmarti** [comment]
@aNickzz `"forwardPorts"` should avoid collisions by picking a random port if the original port number is not available on localhost.

Showing the forwarding as going to `0.0.0.0` is correct as it stands for "all interfaces", maybe that should be replaced with localhost when opening in the browser. Which browser are you using?

**Comment by PavelSosin-320** [comment]
@chrmarti Port forwarding is a very misleading term because Docker networking doesn't do simple forwarding. As it is explicitly written in the Docker documentation ports are exposed on the surface of Host OS or VM network or overlay network surface by the certain Docker network driver, bridge, by the default but opens mapped ports in the Linux Kernel firewall. binding service running inside container to 0.0.0.0 assumes that Docker CNI provides several interfaces to the container, i.,e. A container is connected to several Docker networks and use NIC driver. There is no such driver exists for Docker by my knowledge and documentation. Service running inside the container should listen only port declared in the Dockerfile using EXPOSE. Docker networking has very strict rules because container communicates with orchestration infrastructure and load balancers. Client sending requests to Docker services must know the exact Service port declared by Service to reach Service implementation inside running container instance. Services are scaled on the container instance base. 
It is possible to run a standalone container on Docker but there is no Docker for standalone containers.

**Comment by aNickzz** [comment]
> "forwardPorts" should avoid collisions by picking a random port if the original port number is not available on localhost.

I couldn't find this information in the docs, but I do know docker will do this too which is why I was relying on the `ports` config in docker-compose.

> Which browser are you using?

Chrome

> Showing the forwarding as going to 0.0.0.0 is correct as it stands for "all interfaces", maybe that should be replaced with localhost when opening in the browser.

I'd like this to be configurable, as I tend to have 3rd party resources that require a particular domain to work (eg. recaptcha, fonts). Instead of adding localhost I tend to configure my `hosts` file to map `local.mycompany.com` to localhost so I get the benefit of our wildcard domain on the whitelist `*.mycompany.com`, it would be great if I could configure it to open the port on that domain instead.

A side note: is there a way to have vscode open the browser with this address automatically when opening the project? I remember seeing something like this somewhere but I couldn't find any information in the docs on how to do it.

@PavelSosin-320 I don't think "port forwarding" itself is misleading, its just that vscode and docker do two very different things to expose the ports. I don't know well how docker works (or the underlying -nix functionality) but i think its enough to know the two mechanisms are distinct.

**Comment by rzhao271** [comment]
Not sure how to verify this.
@aNickzz can you verify whether this issue is fixed now in the latest insiders build?
