### ISSUE TITLE
Git: Command `git.api.getRemoteSources` should still work without Git installed

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/vscode-remote-release#3881]
- VSCode Version: 1.49
- Local OS Version: Windows 10
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1.  Reset windows 10 to factory, install docker, install VS code & Remote: Containers
2.  Hit [f1], select 'Clone repository into container volume...'

Expected: Prompt to install Git?

Actual: After selecting this entry from the command palette, nothing appears.  (Normally, you would get a dialog asking for the repository to clone.)

(Minor issue I ran into this when setting up a new development PC.  When mostly working in WSL, it's easy to forget that VS code needs the Git tools on Windows too.)

**Comment by krotton** [comment]
Actually it should NOT need Git for Windows for anything (because it uses Linux Git within the container) and it hasn't before the most recent updates. I've just noticed that recently `Remote-Containers: Open Repository in Container` has been changed to `Remote-Containers: Clone Repository in Container Volume` that just silently fails for me. Before the update, I've been able to provide a repository URI, the docker volume name and a Git executable from within docker has been used to do the cloning (which is expected, as I do not need Windows Git for anything, as I'm not touching the repository files under Windows).

**Comment by krotton** [comment]
It works if I'm already executing the command from some other devcontainer instead of direcly from Windows. If I understand the logs correctly, cloning is done using Git installed in `vsc-volume-bootstrap`, but the extension checks for locally installed Git and fails silently in case it's missing. If so, the fix should be trivial: just don't check for locally installed Git.

**Comment by chrmarti** [comment]
The `git.api.getRemoteSources` command returns `undefined` when local `git` is not working. @joaomoreno Can this be made independent of a local Git install?

**Comment by joaomoreno** [comment]
> Can this be made independent of a local Git install?

Yeah good suggestion.

**Comment by joyceerhl** [comment]
@lszomoru This is resolved with the git-base extension, right?

**Comment by lszomoru** [comment]
@joyceerhl, yes, I believe that you are correct.
