### ISSUE TITLE
Port forwarding: when the local port is privileged, offer to elevate and use the privileged port if possible

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#3922]
Currently, if preferred local port is privileged, we just pick some other available port. Instead, we could offer to elevate and use the privileged port instead. This would allow users who rely on specific privileged port numbers to continue to develop as though everything is local more easily.

**Comment by PavelSosin-320** [comment]
@alexr The same is for Podman! Only rootfull containers ca map priviledged ports. Rootless can't publish priviledged containers:
[Podman networking ](https://podman.io/getting-started/network). The difference is that no priviledged containers. Only Rootfull and rootles. "Randomization" has to take it into account: it has to start from 1024 for rootless users. Only rootfull processes can listen priviledged ports connected to protocols. I afraid it is firewall restriction :( . It affects all my games with Podman. The pre-defined diapazone will be even better because new CNI firewall and portmapper plugins for bridge network driver support it - it is expected.
Please, don't forget to display mapping to user

**Comment by visini** [comment]
Temporary workaround (execute this on your laptop to relay port 32798):

```shell
brew install socat # if not already installed
sudo socat TCP-LISTEN:80,fork TCP:IP_OR_HOSTNAME_OF_REMOTE:32798 # 32798 corresponds to port on remote, which is tunneled to your laptop, e.g., via SSH Remote Explorer UI
curl localhost:80 # this will work now
```

Looking forward to this functionality!
