### ISSUE TITLE
Feature request: Support defining "initializeCommand" specific to an operating system

### ISSUE THREAD

**Issue by dslijepcevic** [microsoft/vscode-remote-release#3981]
Since `initializeCommand` in `devcontainer.json` is executed locally, to make a dev container fully portable please make it possible to define it for every operating system like we can currently do for tasks. For example:

```json
"windows": {
    "initializeCommand": "..."
},
"linux": {
    "initializeCommand": "..."
},
"osx": {
    "initializeCommand": "..."
}
```

**Comment by PavelSosin-320** [comment]
Dev-container is an OCI container. OCI container is always portable. It has no own OS, it is not a VM. Its OS is the Host machine OS. Of course, Container can't modify the Host OS or execute something on the Host OS because it shares it with all running containers. Only privileged containers may have limited access to the Host OS but working in such a mode is "security suicide".  The container is initialized by entry-point script or executable, not by Initialize command. It is defaulted by Dockerfile and configured by --entry-point option. There is no way to know which OS is used as a base image of the running container - it is not a part of the container's metadata. The image OS is known only inside Dockerfile - it has FROM term in the 1st line. The only exception is Windows Containers that can be run only by Docker-for-Win - hardcode. 
**The Initialize command is executed on the local machine and has nothing with container portability.**

**Comment by dslijepcevic** [comment]
> Dev-container is an OCI container. OCI container is always portable. It has no own OS, it is not a VM. Its OS is the Host machine OS. Of course, Container can't modify the Host OS or execute something on the Host OS because it shares it with all running containers. Only privileged containers may have limited access to the Host OS but working in such a mode is "security suicide". The container is initialized by entry-point script or executable, not by Initialize command. It is defaulted by Dockerfile and configured by --entry-point option. There is no way to know which OS is used as a base image of the running container - it is not a part of the container's metadata. The image OS is known only inside Dockerfile - it has FROM term in the 1st line. The only exception is Windows Containers that can be run only by Docker-for-Win - hardcode.
> **The Initialize command is executed on the local machine and has nothing with container portability.**
> Do you mean devcontainer.json portability?

Of course Docker container itself is portable, but I meant the whole VSCode's `.devcontainer.json` thing. Initialize command that is being run on the local machine is *also a part* of providing that portable environment. In particular, we use initialize command to fight the shortcomings of Remote Containers extension to provide a unique project name for Docker-compose based projects (see [this](https://github.com/microsoft/vscode-remote-release/issues/4059)), so we need to run different local scripts to generate the appropriate `.env` file on Linux, Windows and macOS. It cannot be a single shell script command because of Windows where you might not have WSL installed. We don't want to introduce external dependencies like Python, especially not for Windows. To do that in a *clean and portable way* we need OS overloads for initialize command just like tasks have them to execute a command on a local machine. Initialize command is no different than a local task in that regard. I'm just saying it's a real problem that has already been solved in VSCode and Remote Containers can just mirror it.

**Comment by jesec** [comment]
I use something like this.

```
"source=${localEnv:HOME}/.docker,target=/home/vscode/.docker,type=bind",
"source=${localEnv:HOME}/.gnupg,target=/home/vscode/.gnupg,type=bind",
"source=${localEnv:HOME}/.ssh,target=/home/vscode/.ssh,type=bind",
"source=${localEnv:HOME}/.git-credentials,target=/home/vscode/.git-credentials,type=bind",
"source=${localEnv:HOME}/.npmrc,target=/home/vscode/.npmrc,type=bind",
"source=${localEnv:HOME}/.zsh_history,target=/home/vscode/.zsh_history,type=bind"
```

However, another user/machine may not have the folders/files, and the mount will fail. So I use `initializeCommand` to create them if necessary: 

`umask 077 && mkdir -p ~/.docker ~/.gnupg ~/.ssh && umask 177 && touch ~/.git-credentials ~/.npmrc ~/.zsh_history`

Obviously this will not work well on Windows.
