### ISSUE TITLE
There will be support for FTP remote development?

### ISSUE THREAD

**Issue by g4b0** [microsoft/vscode-remote-release#407]
As in the subject, will be FTP an option in the future?

**Comment by egamma** [comment]
@g4b0 can you please describe the feature request in more details. How should FTP be supported?

**Comment by WSLUser** [comment]
This should be under the SSH extension and using SCP or SFTP, of which there is already a request in the tracker here (please up vote by giving a thumbs up). I suppose the ability would also be useful in the other remote extensions but the remote SSH extension requires this feature more than the others at this time (IMO).

**Comment by g4b0** [comment]
@egamma I would like to work to a project on a remote server, accessible just through FTP(S), and not via SFTP/SSH. Actually I'm using NetDrive, that allow me to mount an FTP share in a Windows drive, but it would be nice to have this funcionality working native in vscode.

The only editor I used that permit to work in this manner is Aptana, but it's a quite abandoned project.

I tried https://github.com/mkloubert/vscode-remote-workspace, but it doesn't work well with FTP.

**Comment by WSLUser** [comment]
> accessible just through FTP(S), and not via SFTP/SSH

Is there an issue with using known secure protocols that work quickly and efficiently? What in your workflow could possibly not support using such connections? Not [NetDrive](http://www.netdrive.net), it explicitly advertises using SFTP/SSH. I hope this request is not considered.

**Comment by g4b0** [comment]
@WSLUser Sometimes developer tends to oversimplify the world around them, and your reply is a proof of that.  There's lot of FTP out there, and sometime I have to handle such situations. I'm happy with NetDrive on the MS side, and I work with fuse on Linux side, but my suggestion was intended to improve the workflow integrating the solution directly into the IDE.

"I hope this request is not considered" is not a polite reply, I can't understand in which way this request can hurt your workflow

**Comment by egamma** [comment]
@g4b0 thanks for the additional information. However, this request is not in the scope of the VS Code Remote extensions. There are other extensions for SSH based development, e.g., https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs and we do not want to duplicate this functionality.

**Comment by WSLUser** [comment]
> we do not want to duplicate this functionality.

There's actually a bit of functionality in SSHFS extension that I'd like to see in the remote SSH extension. The main benefit to the remote SSH extension is that other extensions can work so linting, debugging, etc. will still function on the remote server. If the SSHFS extension had that functionality, I'd say it's perfect for needs of most developers that develop on a remote server. The fact it doesn't means this extension needs to step up and get the functionality going. As I already said, there's already an issue open for the main functionality that's missing (and somewhat discussed here). 

@g4b0 I do apologize if I offended you but as a security developer, I look at security of the tools that best suit my workflow as much as the usefulness of the tool. I wouldn't want insecurities introduced just because of a few use-cases of using FTP. There may be a lot of FTP out there but the fix isn't supporting it, it's replacing it with a secure version (SFTP or SCP, or where really needed, but should be a last resort FTP-S). Understand you can't make that call but most orgs follow some general security guidance and discouraging the use of FTP should be among those.

**Comment by egamma** [comment]
@WSLUser 

>There's actually a bit of functionality in SSHFS extension that I'd like to see in the remote SSH extension. 

What is included in this 'bit of functionality' I don't fully understand the wish yet.

>As I already said, there's already an issue open for the main functionality that's missing (and somewhat discussed here).

What is issue#?

**Comment by WSLUser** [comment]
I actually wrote the issue: https://github.com/microsoft/vscode-remote-release/issues/73
