### ISSUE TITLE
Node debugger ports are forwarded

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#4117]
Testing #4094

- Start debugging in the node sample container
- Get a notification that node's debug port is forwarded

These never need to be forwarded, but I don't know how to identify them, especially since the same process can open a port that should be forwarded. Only js-debug knows which port is the debug port. I really don't need a notification every time I start debugging, and it could confuse the user.

**Comment by PavelSosin-320** [comment]
@roblourens Relax, it is very simple! Every debug protocol has its own default port. It is necessary to avoid port conflicts. It is always protected by the firewall's configuration at the computer level and LAN/WAN/Cloud network level to be accessible only from certain clients, 127.0.0.1, [::1], private network, etc. 
Nodejs inspector, Chrome use 9229, JDWP uses 80000 by default.
**Such ports are never opened automatically** or without superuser privileges for any purpose except for **debugging. from the localhost**.   But is done by the firewall using DROP rule and the client may not care about it.
P.S. In **Windows --> WSL scenario no need for checks**.

**Comment by alexr00** [comment]
@roblourens I couldn't find a way to distinguish these ports either. The solution we are going with is to add "ignore" ports/ranges: https://github.com/microsoft/vscode-remote-release/issues/4046

**Comment by PavelSosin-320** [comment]
@alexr00 Black lists are discussed too. It will never work because network configuration in not a part of application - too many players between client and server or service:
Client firewall, reverse proxy, router with port forwarding, proxy, Server firewall with default ruls.
Client can **claim** which ports it needs. Server can **expose** ports which it serves. But any participent between client and server has to be configured manually using its tools. Docker simply provides  ["basic documentation about Docker and firewall"](https://docs.docker.com/network/iptables/)

**Comment by roblourens** [comment]
The node debugger uses a random port free every time
