### ISSUE TITLE
Remote WSL fails to start 

### ISSUE THREAD

**Issue by gorilla-1** [microsoft/vscode-remote-release#4119]
Basically I mentioned it at another issue (which was for Mac so I decided to open it). I used my caveman skills like uninstalling and installing everything (as you expect it didn't solve the problem and couldn't find it anywhere)
![Screenshot 2020-12-01 225107](https://user-images.githubusercontent.com/57768528/100789743-ec6f0600-3427-11eb-84bf-57f803b20187.png)

Windows: 19042.630
Ubuntu: 20.04 (wsl2)
VS Code: 1.51.1

**Comment by gorilla-1** [comment]
@ microsoft/vscode-remote-release#4096

**Comment by gorilla-1** [comment]
#4069 is the other issue for people interested.

**Comment by PavelSosin-320** [comment]
This WSL issue appears in other scenarios unrelated to VSCode, like DockerDesktop. My analysis points to some Hyper- V worker related issue in the Microsoft Windows software. The Event viewer shows "'Virtual Machine' was reset because an unrecoverable error occurred on a virtual processor that caused a triple fault. If the problem persists, contact Product Support. (Virtual machine ID E7CB94AD-2AB3-45C8-BC02-8403F187756F)" in the log every time when WSL fails to start.
It triggers error data collection and submitting it to MS. Hopefully, it will be patched soon.

**Comment by PavelSosin-320** [comment]
@gorilla-1 Please, provide your version information for Windows, WSL distro, and VSCode as it is required for Bugs.

**Comment by gorilla-1** [comment]
> 
> 
> @gorilla-1 Please, provide your version information for Windows, WSL distro, and VSCode as it is required for Bugs.

Windows: 19042.630
Ubuntu: 20.04 (wsl2)
VS Code: 1.51.1

**Comment by aeschli** [comment]
The log shows that the windows build version was reported as 9200. That happens when VSCode is started in compatibility mode. See https://github.com/microsoft/vscode-remote-release/issues/3243.

Can you check this: https://github.com/microsoft/vscode-remote-release/issues/3243#issuecomment-655431647 ?

**Comment by gorilla-1** [comment]
@aeschli  It's working with Insiders right now. Thx for showing compatibility troubleshooter.

**Comment by aeschli** [comment]
@gorilla-1 Thanks for reporting back. If you see this again, then we need to dig deeper and find out how VSCode was started in a different mode.

**Comment by bamurtaugh** [comment]
Thanks for the discussion here. Going to close out this thread since it looks like the issue was resolved, but certainly report back if you face any additional trouble.
