### ISSUE TITLE
Remote-SSH - Switch Hosts

### ISSUE THREAD

**Issue by sachit-menon** [microsoft/vscode-remote-release#4235]
Hi and thanks for the great work! Perhaps there is already an easy way to do this that I just don't know. I do remote work on a cluster of many machines; the Remote-SSH plugin is great for using one machine, but often if a particular machine is under high usage by others, I need to switch to a different machine on the cluster to do the same work (they share memory, the files are the same).

I currently have each machine configured separately, and when I need to switch I connect to the new host, then open everything I had open previously, but this is kind of time consuming to do repeatedly. What would be great is a simple 'Switch Hosts' command that would let me keep everything as is but switch machines - that is, in one click switch machines and open everything up to the same state I was in on the original machine.

This sounds like it would be straightforward given what's already built in, and I'm sure many users have multiple machines sharing memory in this cluster-like setup! It would save a lot of time in the long run. Thank you for your consideration and please let me know if anything is unclear.

(I created an issue in the base VSCode repository before realizing this might be a better place for this, I'm happy to delete one of them if it's in the wrong place.)

**Comment by roblourens** [comment]
It sounds like you want to open the same folder path and keep the same workspace state on a different host. This is tricky for us because usually we would assume that a different host is an entirely different machine. But you could "trick" VS Code into doing this by editing your ssh config to have the same `Host` pointing at a different `HostName`. In that case we wouldn't know that it's a different target IP address/hostname. Then you could just reload the window to open the same folder on the new host. Does something like that help you?

**Comment by sachit-menon** [comment]
Hi, thanks for the pointer! You're right about what I'm hoping to do, but I'm not sure I follow your solution - could you give some more details on how I could try this out to see if it works? I am a bit confused given this https://stackoverflow.com/questions/56413458/ssh-config-multiple-hostname-to-the-same-host/56413679 . Thanks!

**Comment by PavelSosin-320** [comment]
This is built-in functionality in Docker if NTFS is used for Docker volumes instead of bind volumes. if you have NAS storage or storage server and know how to run NTFS server on it you can do it today following Docker documentation. Docker dev-container is not restricted to do it:
1. Run NTFS server on your NAS machine
2. Create Docker context per every Docker engine
3. Configure your workspace as "remote volume" located on the NAS IP or DNS name
[Discussed in Docker storage documentation](https://docs.docker.com/storage/volumes/)
Docker context use switches between Docker engines

**Comment by roblourens** [comment]
@PavelSosin-320 sorry I don't see how that is relevant here. I don't think Docker is involved in this scenario.

@sachit-menon I just mean have this in your ssh config

```
Host myHost
    HostName <IP_or_hostname_1>
```

and connect to myHost. Then to switch, edit it to 

```
Host myHost
    HostName <IP_or_hostname_2>
```

so keeping the same Host but a different HostName. Reconnect and vscode will not know that myHost is pointing at a different HostName.

**Comment by sachit-menon** [comment]
Ah, I see. Would this require manually editing the config every time? I tried changing it manually in the ssh config, but upon reconnecting the workspace starts blank - so same situation as before. Perhaps I'm misunderstanding something?

**Comment by roblourens** [comment]
Yes, but that's the best I can do, sorry. 

> but upon reconnecting the workspace starts blank

I don't know why that would happen. I tested it and it worked for me. Maybe you could share a screenshot or recording of exactly what steps you took?

**Comment by PavelSosin-320** [comment]
@roblourens I mean that the solution for dev-container running by Docker engine already "packed" inside Docker engine. The container doesn't know where it is running and doesn't know where the mounted volume is located physically. Unless workspace is mounted as "bind" volume all data about volume location is supplied as "volume mount options" when the container is run. It can be the same machine where the Docker engine is running or 3rd machine running the NTFS server. The Docker host machine can be switched using Docker context and no other way. The host where Workspace is located can be switched passing Host IP as NFS volume option (volume-opt=type=nfs,volume-opt=device=<nfs-server>:<nfs-path>) and no other way. The Docker Host and Workspace Host can be switched independently. If Workspace path can be passed to Docker in the format <nfs-server>:<nfs-path> the requested feature doesn't require too much effort. On the server-side: sudo apt -y install nfs-kernel-server.
