### ISSUE TITLE
Cannot attach to a container if a container with the same name is already opened using an other docker context

### ISSUE THREAD

**Issue by remss** [microsoft/vscode-remote-release#4266]
- VSCode Version: 1.52.1
- Local OS Version: Windows 10 version 20H2
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH with Docker contexts

## Steps to Reproduce:

* From 2 remote servers (remoteA and remoteB), start a container using the same container name

          remoteA# docker run -ti --name test-ubuntu ubuntu:20.04 bash
          remoteB# docker run -ti --name test-ubuntu ubuntu:20.04 bash
	
* From the Local Workstation

	* Open VSCode, in Docker panel, use context remoteActx
	* Right click on running container "test-ubuntu" > "Attach Visual Studio Code"
	* Once the second VSCode window is opened and attached to remoteA, go to File > Open Folder and select "/var/log"
	* Back to the first VSCode window, in Docker panel, use context remoteBctx
	* Right click on running container "test-ubuntu" > "Attach Visual Studio Code"
	* 💥 The second VSCode window is focused (attached to remoteA) instead of opening a third VSCode window attached to remoteB.

## Notes:

Does this issue occur when you try this locally?: Cannot do that, issue is about multiple remote docker contexts
Does this issue occur when you try this locally and all extensions are disabled?: Yes

If I use different containers names on each remote, like "test-ubuntuA" and "test-ubuntuB", then it works as expected, the second Attach opens a third VSCode window.

**Comment by bwateratmsft** [comment]
To add some notes from microsoft/vscode-docker#2589, I think that this is occurring because the command line assembled to launch VSCode remotely is the same. The Docker context is different, so the meaning of the command is ultimately different, but the command line does not contain this context information so VSCode does not know it isn't identical. It's possible this could be solved by including the `--context` parameter with the name of the current Docker context.

**Comment by chrmarti** [comment]
Maybe related: https://github.com/microsoft/vscode-remote-release/issues/4196
