### ISSUE TITLE
SSH connection fails when password has special characters

### ISSUE THREAD

**Issue by slwr4thales** [microsoft/vscode-remote-release#4335]
SSH connection fails when password has special characters from Windows to Linux systems.
I did a dirty hack to fix my issue - it may helps to find a proper solution.

I just added `chcp 65001 & `.

Changed in Line from: 
```
`o=e.sendText?"":k?`/c (${i}) & exit /b 0`:["-c",i+"\nexit 0"],e.cwd&&u.debug("Using cwd: "+e.cwd);`
```

to: 

```
`o=e.sendText?"":k?` /c chcp 65001 & (${i}) & exit /b 0`:["-c",i+"\nexit 0"],e.cwd&&u.debug("Using cwd: "+e.cwd);`
```

Change as patch of %USERPROFILE%\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js
[extension.js.patch.txt](https://github.com/microsoft/vscode-remote-release/files/5848313/extension.js.patch.txt)

**Comment by roblourens** [comment]
Can you tell me whether it works if you set `"remote.SSH.useLocalServer": true`?

**Comment by slwr2** [comment]
@roblourens 
Neither `"remote.SSH.useLocalServer": true` nor `"remote.SSH.useLocalServer": false` changes something.
Also `"remote.SSH.localServerDownload": "always"` doesn't change something.

Output:
```
[11:03:09.420] Showing password prompt
[11:03:20.925] Got password response
[11:03:20.926] "install" wrote data to terminal: "****************"
[11:03:20.954] > 
> 
[11:03:25.149] > Permission denied, please try again.
```

**Comment by roblourens** [comment]
Thanks for trying it, thanks confusing, will take some investigation

**Comment by roblourens** [comment]
Old issue, let me know if this is still a problem

**Comment by 4wk-** [comment]
Hello. 
This is an old issue but it happened to me today.
If someone have the same issue and read this, do not investigate just now. **Just reboot the whole PC first**. 
This is, as I see it, **an issue definitely related to VSC and/or Remote SSH extension** (see below), but restarting the PC seems to fix it.

----

**Background:**
It happens on only 1 of the 6 Windows 10 PC connecting to the same Linux Remote Server with VSC, after booting it up.

I spend multiple hours trying to understand and narrow the issue down:
- everything was identical between all PC (OS version, language version, time, VSC version, VSC settings, etc) ;
- the PC with "bugged" VSC was working fine yesterday (VSC was able to connect to the Linux server just fine) ; 
- the password of the Linus server didn't changed recently ;
- copy/pasting the password or writing it entirely didn't change a thing ;
- connecting to the Linux server with other tools like PuTTY with the same password was working just fine.

 **=> The Linux server password had special chars in it (`²` and `µ`).**

Changing the password to `FOOBAR123` allowed VSC on the bugged PC to connect fine. Changing the password to `FOOBAR123²` makes VSC unable to connect again.

What give me clues was using this online tool: https://www.soscisurvey.de/tools/view-chars.php
@roblourens fill the text area with `Testing²VSCµ123` and click on "Show me". There is no invisible chararacter, of course, but the tool will show:
> 15 characters, 17 bytes

(which is right I presume, because of `²` and `µ`)

---- 

**=> So as I see it**, this issue occurs **after** I write the password into VSC **but before** the remote Linux server get the password, and something is messing up with multi bytes characters.
