### ISSUE TITLE
Windows password prompt doesn't specify what it's asking for.

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-remote-release#4398]
ref https://github.com/microsoft/vscode-remote-release/issues/4366

![image](https://user-images.githubusercontent.com/8586769/106341069-cc559a80-6250-11eb-822a-88b1a77685b2.png)

**Comment by chrmarti** [comment]
This is https://github.com/PowerShell/Win32-OpenSSH/issues/1152. I'll just fall back to 'Enter password' when no prompt is given to the SSH_ASKPASS command. This will not match other cases like 'Enter passphrase for ...'.

Remote-SSH seems to be using a terminal to run ssh on Windows to extract the prompt. That approach would be more difficult to apply here because it is the Docker CLI that is calling ssh.

/cc @roblourens In case you have additional insights.

**Comment by roblourens** [comment]
Yeah, this is part of why we disable the "local ssh server" option by default on windows. I also try to use a git SSH by default if I can find it, which doesn't have this but, but that has caused other issues in the past. The default prompt is not great like if the user will have to enter a key passphrase + password but I would leave it. The ssh fix will come down the pipeline some day...

**Comment by chrmarti** [comment]
Updates seem to be slow: My VM shows OpenSSH for Windows 7.7 released mid-2018 as the installed version. (And the fix for this issue hasn't made it into a release yet.)
