### ISSUE TITLE
Permission Denied every time the extension is updated

### ISSUE THREAD

**Issue by dan1994** [microsoft/vscode-remote-release#4469]
- VSCode Version: 1.53.2
- Local OS Version: Windows 10 Home 20H2 19042.804
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Install/update the extension version
2. Type `code` in WSL terminal
3. Get `/mnt/c/Users/<username>/AppData/Local/Programs/Microsoft VS Code/bin/code: 52: /mnt/c/Users/<username>/.vscode/extensions/ms-vscode-remote.remote-wsl-0.53.4/scripts/wslCode.sh: Permission denied`

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

The issue is quite simple, as every time a new version is installed it is put in a new directory, and all files in scripts get no execution permission. I can (and have many times) `chmod +x` on them to solve the issue, but am hoping for a more permanent fix.

I wonder if it's related to WSL configuration in some way...

**Comment by snolan-uturn** [comment]
I'm guessing you have these options or similar configured in your /etc/wsl.conf

options = "metadata,umask=022,fmask=111"

That fmask will cause the default Linux permissions to exclude execute (the extension files written in Windows have no Linux permissions so the default is used). As you've found, you can add the execute permission and it gets stored in the Linux file metadata so that the scripts are then able to run. I've seen solutions which have you change the fmask to 002 but that isn't very Linux friendly and grants execute on all files by default.

Ideally the extension installer needs to set the Linux execute permission when it adds the files.

**Comment by dan1994** [comment]
Thanks for your reply. I'll try playing with the mask to see if it works.

**Comment by dan1994** [comment]
This works :)
