### ISSUE TITLE
Ports view: Set Label command polish

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#4624]
- Combine the two Set Label actions into a single one
- Provide the Set Label action as a inline action in the port#/label column
- Support double clicking to edit a label

**Comment by alexr00** [comment]
Some additional polish feedback from @isidorn:
1. Add port button looks funky since it does not take the full cell. Did you experiment with making it take the whole cell?
2. Vertical lines look too strong, I feel like I am in excel instead of looking at a cool port UI which just happens to be nicely aligned. (@joaomoreno would you consider making the lines less strong?)
3. Row with Add Port button looks taller.
4. It does not make a difference if I click on the Add Port button or next to it.

**Comment by joaomoreno** [comment]
> Add port button looks funky since it does not take the full cell. Did you experiment with making it take the whole cell?

Wouldn't that just look awful when in the panel?

> Vertical lines look too strong, I feel like I am in excel instead of looking at a cool port UI which just happens to be nicely aligned. (@joaomoreno would you consider making the lines less strong?)

Absolutely. That's why they go away when you're not hovering over the table. I think you're overthinking this @isidorn.

**Comment by isidorn** [comment]
1. I do not mean the whole row, just the whole cell. I personally do not think it would be awful and is worth a try. I do not see how this changes if the table is in the panel
2. Okey. But it is highly likely that my mouse is over the table (since it is large), so most of the time we do render the lines. I am just saying they do not look nice in my opinion

**Comment by joaomoreno** [comment]
> just the whole cell

That could work, but what if the user stretches the cell width?

**Comment by alexr00** [comment]
Example with the Add Port button taking the full column width:

![image](https://user-images.githubusercontent.com/38270282/111481625-6efba700-8733-11eb-91b6-9990fbaf1a8a.png)

Example with existing button width behavior (matches settings):

![image](https://user-images.githubusercontent.com/38270282/111481715-88045800-8733-11eb-9ad9-912dd4bd9f94.png)

I still prefer the existing behavior.

**Comment by isidorn** [comment]
If you prefer the existing behavour feel free to stick to that. I just found it ugly in this particular case (though it looks like an unrelated bug that the focus border is weirdly rendered)
![Screenshot 2021-03-17 at 15 38 02](https://user-images.githubusercontent.com/1926584/111485282-c8b1a080-8736-11eb-8c47-9af4773ef63e.png)

**Comment by isidorn** [comment]
Thanks a lot!
