### ISSUE TITLE
Remote dev: Local images in hovers aren't loading properly

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-remote-release#465]
Issue Type: <b>Bug</b>

Originally reported: https://github.com/eamodio/vscode-gitlens/issues/734#issuecomment-492055255

In GitLens, I am loading an svg image off disk (installed with the GitLens vsix) for the presence indicator dot, which works fine normally, but when used with remote dev it shows as a broken image: (the _You are offline_ part is the alt-text of the image)
![image](https://user-images.githubusercontent.com/641685/58275519-35d69380-7d63-11e9-9ef9-ceb92b2acfeb.png)

Here is the code I'm currently using for it.
https://github.com/eamodio/vscode-gitlens/blob/d8654c6cd1465da8f5290bd9b5bb6e775cc6f679/src/git/formatters/commitFormatter.ts#L137-L140

Is this something I can change/fix somehow?

VS Code version: Code - Insiders 1.35.0-insider (94f7de61ece171f4390ece488a220d22cbb0fddd, 2019-05-23T05:19:33.101Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sandy081** [comment]
@jrieken Hover providers have file URIs which are not valid in remote set up. Lets discuss what to do on this in next milestone.

**Comment by jrieken** [comment]
We actually do have a mechanism for that - we preflight the markdown while serialising it and extract all uris so that we know where they are pointing to: https://github.com/microsoft/vscode/blob/b81b3cd58eff69504746afb86157ede376e17798/src/vs/workbench/api/common/extHostTypeConverters.ts#L240-L250. This also looks for images but something seems to get lost here

**Comment by jrieken** [comment]
The problem here is that uris are formed like this `file:/// + context.asAbsolutePath(foo)`. That will lead to an uri (on Nix systems) with four slashes, e.g `file:////images/foo.js`. There is a preflight-pass on the markdown source to detect (and transform) uris before sending them to the main but in this case our uri fails to parse the value (due to four slashes). 

@eamodio Using `vscode.Uri.file(path).toString()` should help you but I believe you have migrated onto data-uris by now.
