### ISSUE TITLE
How to use a .devcontainer while using ssh-remote to a ec2 instance ?

### ISSUE THREAD

**Issue by tchaton** [microsoft/vscode-remote-release#4663]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code or for GitHub Codespaces https://github.community/c/codespaces-beta

**Comment by bamurtaugh** [comment]
Hey @tchaton, transferring this issue since it relates to the remote development experiences in VS Code rather than an issue with a specific dev container definition.

If you've successfully used Remote-SSH to connect to your remote host, I think this would be an appropriate next resource: https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host.
