### ISSUE TITLE
"Cannot reconnect. Please reload the window." after waking computer from sleep

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode-remote-release#4686]
Issue Type: <b>Bug</b>

Since a couple of days, whenever I wake my computer from sleep, all VS Code instances will show an error message saying "Cannot reconnect. Please reload the window.".

All instances in question are connected to a WSL remote.

Previously, my VS Code instances would work without interruption after waking from sleep.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042
Fetching remote diagnostics for 'WSL: Ubuntu' failed: Canceled
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Fetching remote diagnostics for 'WSL: Ubuntu' failed: Canceled
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.87GB (25.31GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/oliver/fairmanager/fairmanager/core-web3 --remote=wsl+Ubuntu --crash-reporter-id 05565d81-cfc4-40de-88df-1c479bbe1bcd|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu' failed: Canceled

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (16.17GB free)|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu' failed: Canceled

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (16.17GB free)|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
eslint-disable-snippets|drK|1.3.0
tsl-problem-matcher|eam|0.4.0
output-colorizer|IBM|0.1.2
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.5
vscode-remote-extensionpack|ms-|0.20.0
vscode-icons|vsc|11.2.0
vscode-zipfs|arc|2.2.2
vsc-prolog|art|0.8.23
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.19
xml|Dot|2.5.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.3.0
generateuuid|Fir|0.0.5
shell-format|fox|7.0.1
vscode-graphql|Gra|0.3.15
terraform|has|2.8.2
vscode-esformatter|how|1.6.0
output-colorizer|IBM|0.1.2
template-string-converter|meg|0.4.7
vscode-docker|ms-|1.11.0
vscode-paste-image|mus|1.0.4
monolit|Oli|0.0.27
vscode-yaml|red|0.16.0
docker|vsc|1.0.0
yaml|vsc|1.0.0

(2 theme extensions excluded)

</details>

**Comment by timothyfroehlich** [comment]
This happens with me too, using remote-ssh to connect to my Ubuntu box from my Windows 10 box.

**Comment by bamurtaugh** [comment]
Thanks for opening @oliversalzburg. It sounds like this could be https://github.com/microsoft/vscode-remote-release/issues/3454.

> This happens with me too, using remote-ssh to connect to my Ubuntu box from my Windows 10 box.

@timothyfroehlich Connectivity for WSL and SSH would likely be different underlying issues; if you have any logs or greater info, it'd be great if you could open a separate info, or search for existing SSH connection issues and see if you might be experiencing any of those.

**Comment by oliversalzburg** [comment]
> Thanks for opening @oliversalzburg. It sounds like this could be #3454.

It does sound very related. However, I have my doubts if it's the same root cause. I'm not exactly familiar with "Modern Standby". I do know of "Hybrid Sleep" though and assume it refers to the same technology. Unless I'm mistaken, it's not enabled for my workstation:

![image](https://user-images.githubusercontent.com/1658949/112118197-67695180-8bbc-11eb-9522-bbc7af254c70.png)

Additionally, as #3454 was opened so long ago, I would have expected to experience this earlier myself. I have been going through this sleep-wakeup-routine with this workstation for a couple of months now 😄

**Comment by tebeco** [comment]
https://github.com/microsoft/vscode-remote-release/issues/3126#issuecomment-836255588

**Comment by iamwwc** [comment]
disable hibernate seems fix problem

**Comment by tebeco** [comment]
> disable hibernate seems fix problem

Well you don't need to and some don't want to.

Take a look at the comment posted just above about that, it's more likely about the clock not in Sync rather than the hibernate itself.

**Comment by iamwwc** [comment]
> > disable hibernate seems fix problem
> 
> You don't need to and some don't want to.
> 
> Take a look at the comment posted just above about that, it's more likely about the clock not in Sync rather than the hibernate itself.

I have update kernel to 5.x which said have fixed clock issue, but I still have it.

https://github.com/microsoft/vscode-remote-release/issues/3126#issuecomment-829077902

**Comment by tebeco** [comment]
Sorry I just saw
> Everytime I waked from sleep, I have to reconnect vscode wsl2 all the time, which causes losing everything I already have ;(

the comment you linked is from someone else.

I'm only also on 5.x as it appear, and just re-synching the click fixes it 100% of the time
![image](https://user-images.githubusercontent.com/2266487/119457132-6683a600-bd4c-11eb-9d23-b21dba97de68.png)

Though, If i may have a good news:
> which causes losing everything I already have

Good thing is that you're not loosing anything with `hwclock`
Just let `VsCode` disconnected, open a Term, in that Term open `wsl2`, resync that, go to VsCode => reconnect, done
Unless something changed, I did not loose anything yet.

I truly think this issue should be close because, well, it's not a bug of `vscode-remote-release` but rather on the WSL team to make sure the clock does not drift away

**Comment by oliversalzburg** [comment]
> I truly think this issue should be close because, well, it's not a bug of vscode-remote-release but rather on the WSL team to make sure the clock does not drift away

While that may be true, given that the symptom is commonly seen in Code, it makes sense to track a possible upstream issue here.

That being said, when I wake my computer from sleep, go into a WSL terminal and execute `date`, I get the current, correct time. So either there was no drift, or the clocks have already been synced (I would assume the latter).

So it appears to me that changing the timing of the reconnection approach might also have a positive impact on this behavior. Especially if this behavior can be assumed to be consistent.

**Comment by iamwwc** [comment]
> Sorry I just saw
> 
> > Everytime I waked from sleep, I have to reconnect vscode wsl2 all the time, which causes losing everything I already have ;(
> 
> the comment you linked is from someone else.
> 
> I'm only also on 5.x as it appear, and just re-synching the click fixes it 100% of the time
> ![image](https://user-images.githubusercontent.com/2266487/119457132-6683a600-bd4c-11eb-9d23-b21dba97de68.png)
> 
> Though, If i may have a good news:
> 
> > which causes losing everything I already have
> 
> Good thing is that you're not loosing anything with `hwclock`
> 
> * Just let `VsCode` disconnected with the message "Hey i'm disconnected want to retry ?"
> * open a Term
> * in that Term open `wsl2`
> * resync that
> * go to VsCode
> * click reconnect
> * should be done
> 
> Unless something changed, I did not loose anything yet when it happened.
> 
> I truly think this issue should be close because, well, it's not a bug of `vscode-remote-release` but rather on the WSL team to make sure the clock does not drift away

What does  "just re-synching the click"  means? 

Did you do anything else except just update kernel to 5.0?

**Comment by oliversalzburg** [comment]
@iamwwc That may be in relation to https://github.com/microsoft/WSL/issues/5324#issuecomment-821421563

**Comment by iamwwc** [comment]
> From the information I took from the WSL-related tickets, I ran `sudo hwclock -s` yesterday and my Code instances were still connected after waking from sleep today. So that's nice.

Should I run `sudo hwclock -s` before every sleep or just once?

**Comment by oliversalzburg** [comment]
@iamwwc I've only ran it once, hours before sending the machine to sleep. I wasn't able to verify today, because I'm in a different office 😑

**Comment by tebeco** [comment]
I'm not sure i understand the issue the same way as you @iamwwc 

issue as i understand it is that
* the "connection" between both side can't be established due to security issue.
* because it look like it rely on TLS to make it secure
* that TLS require both side to have clock relatively synched to avoid people toying with clock / time attack
* your wsl2 clock drifted due to hybrid + possible bug in wsl
* vscode don't care about all of that because it's on windows side
* when it try to reconnect it fail
* every time the wsl2 clock is wrong you will need to make it right. like changing battery in your watch every time the battery die 
* this DOES NOT ONLY IMPACT VSCODE, likely most of TLS1.x like https or apt update/upgrade
* once you resynch that wrong clock on wsl2 tell vscode to retry with the "retry/reconnect" button

as you are using vscode, i'm tempted to believe you might find a solution to automate that in wsl with a cron or an alias

you could even try to see if you can create a PR inside this project just to make that gc lock possible on retry (issue being the root/sudo maybe)

good luck

**Comment by tebeco** [comment]
Don't try to reproduce when it happen just by playing with sleep mode, it's not every time because it's not like a Video player with play/pause button on the click.

As you can see, it's completely unrelated to VsCode or the extension, in my opinion, as said, if we all want this to be addressed  this issue should be closed and raised on the right team (WSL repo)

this is a relevant issue related to this bug and that could be addressed for this repo:
https://github.com/microsoft/vscode/issues/110062
Because it try to fix something related to this extensions: the remote workspace and it content (not the clock and the underlying connection)

You don't ask car seller to repair your seat because sometime it hurts your back, when in fact you hit a big rock that was not supposed to be on the road, cleaning the road would be more targeted and efficient. Tweaking your seats are just going to provide a "extra comfort", but you're still going to take the hit every time

**Comment by garciaarmando** [comment]
In my case, the problem was caused for the extension [Live Sass Compiler](https://marketplace.visualstudio.com/items?itemName=ritwickdey.live-sass), specifically when I use sass import function.

**Comment by ArudoPE** [comment]
> In my case, the problem was caused for the extension [Live Sass Compiler](https://marketplace.visualstudio.com/items?itemName=ritwickdey.live-sass), specifically when I use sass import function.

Yes, after I disabled this extension, now I don't have this problem anymore.

**Comment by oliversalzburg** [comment]
Hasn't happened for me in several weeks. No idea what changed.

**Comment by lod61** [comment]
> Hasn't happened for me in several weeks. No idea what changed.

When i delete extensions, it work to me. ```rm -rf /root/.vscode-server/extensions``` 
After delete folder extensions, it can't install exteensions. so i mkdir a empty folder ```mkdir /root/.vscode-server/extensions```
I think mabye can't install some special extension, i am not sure what is that one.
:smile:

**Comment by xiaojueguan** [comment]
> > In my case, the problem was caused for the extension [Live Sass Compiler](https://marketplace.visualstudio.com/items?itemName=ritwickdey.live-sass), specifically when I use sass import function.
> 
> Yes, after I disabled this extension, now I don't have this problem anymore.

I have the same issue, but the plugin Live Sass Compiler is not installed

**Comment by aeschli** [comment]
duplicate of #3158
