### ISSUE TITLE
VSCode Server (SSH) does not support `??` and `?.`

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode-remote-release#4692]
- VSCode Version: 1.53.2
- Local OS Version: Win 8.1
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Extension will not activate on the remote OS with the error: `Unexpected character ?`

In a recent update of my extension I have used:

* Nullish coalescing operator (`??`)
* Optional chaining (`?.`)

Replacing these operators with equivalent code makes the extension work with Remote SSH.

Is VSCode Server SSH running a different version of Node.js ?

Does this issue occur when you try this locally?: No

**Comment by roblourens** [comment]
Remote node: `v8: '7.8.279.23-node.39'`

Frontend node: `v8: "8.7.220.31-electron.0"`

This surprised me a little but maybe this is just the update pace. Do you know when the remote version will be updated @deepak1556?

**Comment by deepak1556** [comment]
Yeah this is unfortunate from how we related node versions on the remote to the desktop, please see https://vscodeteam.slack.com/archives/GA6BE00BX/p1607061057018600 . The v8 versions on desktop are always gonna be on the latest stable because of chromium but not the remote. Also, to support remote on apple silicon devices we need node > 15 https://github.com/microsoft/vscode-remote-release/issues/4069 . 

Do you think we should revisit the decision of node version choice on remote ? I think we have more than one compelling use case now that outweigh the disadvantages of choosing newer versions. @roblourens can you ping in the channel again if you feel strongly about this ?

**Comment by deepak1556** [comment]
v8 version in remote has been updated to `8.6` which supports `??`, this is available in today's insider and will be available with next stable release `1.56` of vscode.
