### ISSUE TITLE
Port label jumps to the left on double click

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-remote-release#4729]
Testing #4718

Linux, connect to dev container.

1. Forward a port
2. Double click on a port to set a label
3. The whole part jumps to the left 🐛 

Do the rename file in Explorer. Notice how there is less jumping.
I believe there is some minor css polish to be done

**Comment by alexr00** [comment]
This is by design because of https://github.com/microsoft/vscode/issues/117386

The left padding when the input box is not shown looks nice:
![image](https://user-images.githubusercontent.com/38270282/112134057-9be50980-8bcc-11eb-8bc4-dcd9bf35ee55.png)

The input box looks nice when it fills the whole cell (https://github.com/microsoft/vscode/issues/117386):
![image](https://user-images.githubusercontent.com/38270282/112134117-abfce900-8bcc-11eb-939c-f25b1a21a500.png)

Current behavior with the shift (option 0):
![recording (50)](https://user-images.githubusercontent.com/38270282/112136133-dfd90e00-8bce-11eb-9c27-084b4dd3c129.gif)


If I changed it to keep the text in place it would look like this (option 1):
![recording (48)](https://user-images.githubusercontent.com/38270282/112135241-df8c4300-8bcd-11eb-945a-ae8617694dc1.gif)

Alternatively, I could put extra space inside the input box (options 2):
![recording (49)](https://user-images.githubusercontent.com/38270282/112135821-81139480-8bce-11eb-8647-2259a2625363.gif)

**Comment by alexr00** [comment]
@misolori of the above options do you have a favorite?

**Comment by misolori** [comment]
I like option 1 since it doesn't change too much from what we have.

**Comment by joaomoreno** [comment]
Actually option 2 looks much better to me 😃

It makes it look like a nicely aligned spreadsheet with proper padding, while option 1 looks strange with that left margin in the input box.

**Comment by isidorn** [comment]
There is still a bit of jump up, but better than before -> verified
