### ISSUE TITLE
Test: "docker.host" setting

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#474]
https://github.com/microsoft/vscode-remote-release/issues/171

- [x] Windows @rebornix
- [x] anyOS @joaomoreno
- [x] Windows @RMacfarlane 

Complexity: 4

- Install Docker extension to get the `"docker.host"` setting.
- Set `"docker.host"` to a remote docker daemon (possibly tunneled) and test:
  - Attaching to an existing container.
  - Launching a new container with a devcontainer.json.
  - Launching a new Docker Compose set of containers with a devcontainer.json.
- When connected to the container, try a few things like dynamic forwarding, etc.

To get an initial devcontainer.json you can use the `Create Container Configuration File...` command in an empty folder (or with some sample code).

To get a remote Docker daemon you can use Docker Machine, e.g. (replace the `<subscription-id>` and `<region>`):
```
docker-machine create --driver azure --azure-ssh-user chrmarti --azure-subscription-id <subscription-id> --azure-location <region> --azure-resource-group <resource-group-name> --azure-size Standard_D2s_v3 <machine-name>
docker-machine ssh <machine-name> -L 12345:/var/run/docker.sock
```

Then in the SSH session (restart session after adding group with `usermod`):
```
sudo usermod -aG docker $USER
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

Use `"workspaceMount"` and `"workspaceFolder"` options in the devcontainer.json to control mount point (single container case) and folder to open (single container and Docker Compose case).

**Comment by joaomoreno** [comment]
This setting doesn't work at all for the Docker extension:

![image](https://user-images.githubusercontent.com/22350/58546355-73c13500-8205-11e9-9c44-54bb012e7698.png)

**Comment by joaomoreno** [comment]
Filed issue: https://github.com/microsoft/vscode-docker/issues/962

**Comment by joaomoreno** [comment]
@chrmarti 

> When connected to the container, try a few things like dynamic forwarding, etc.

Care to elaborate? Not sure what I should do once connected.

**Comment by joaomoreno** [comment]
Here's my setup:

1. Get a Ubuntu VM running, install Docker in it.
2. Follow [this guide](https://www.ivankrizsan.se/2016/05/18/enabling-docker-remote-api-on-ubuntu-16-04/) to get Docker running on a TCP port instead of a UNIX socket
3. Use something like `DOCKER_HOST=tcp://192.168.56.101:4243 docker ps` to test the connection to the guest VM dockerd
4. Use `192.168.56.101:4243` as the `docker.host` setting in VS Code (without the protocol due to https://github.com/microsoft/vscode-docker/issues/962)

I tested attachment and port forwarding by running:

```
DOCKER_HOST=tcp://192.168.56.101:4243 docker run -it python python -m http.server 8000
```

This starts a container with an HTTP server on port 8000. I tested I could attach to it. I then tested dynamic port forwarding of 8000. Everything worked. :clap:

**Comment by Chuxel** [comment]
@stevencl @chrmarti FYI - On Windows, `docker.host` works, but remote mounting via a Dockerfile fails due to the volume mount of the `.gitconfig` file.  See #489.

**Comment by rebornix** [comment]
Attaching to remote docker instances, and forwarding ports work as expected, awesome work!

For opening existing dev container project, I still have trouble with folder mounting as described in https://github.com/microsoft/vscode-remote-release/issues/509.
