### ISSUE TITLE
Auto install all extensions on remote container option

### ISSUE THREAD

**Issue by leighmcculloch** [microsoft/vscode-remote-release#4856]
It would be very convenient if it would be possible to have a setting that if set to true causes all extensions on new remotes  containers.

The setting `remote.containers.defaultExtensions` exists and allows me to list all my extensions that meets essentially the same goal, but every time I add a new extension or remove an extension in the UI I have to manually go to my settings and add or remove the extension from the list.

The command `Remote: Install Local Extensions in 'Remote'` (`workbench.extensions.installLocalExtensions`) is also convenient, but it requires manual action every time I start a new container, which is often.

This issue was previously reported in #873 and then rolled into #157 because at the time it was considered a duplicate issue. However, this issue was not completely addressed by #157 because #157 introduced a manual way to install extensions into the remote container.

**Comment by leighmcculloch** [comment]
It should be possible to develop this feature as a separate extension, if there is an activation event that gets triggered when a new container is started and connected to. I can't find a list of activation events for the remote extension. Is there a list of activation events for the remote extension somewhere?

**Comment by chrmarti** [comment]
There are no additional activation events for when a remote connection is established. You could probably activate on `"*"` or `"onStartupFinished"` and check `vscode.env.remoteName` to decide if want to tigger `workbench.extensions.installLocalExtensions`. If you do that with a workspace extension using `"remote.containers.defaultExtensions"` to install itself, you could place a marker file in the container to avoid triggering that command more than once for the same container (if that turns out to be a problem).
