### ISSUE TITLE
sourceFileMap not working when using WSL

### ISSUE THREAD

**Issue by trogne** [microsoft/vscode-remote-release#4929]
When debugging using gdb, on WSL ubuntu, I get this error :

Unable to open 'ioputs.c': Unable to read file 'vscode-remote://wsl+ubuntu/build/glibc-eX1tMB/glibc-2.31/libio/ioputs.c' (Error: Unable to resolve non-existing file 'vscode-remote://wsl+ubuntu/build/glibc-eX1tMB/glibc-2.31/libio/ioputs.c').

I get this error even with sourceFileMap defined below.

I can make debugging work if I make a symlink from "/build/glibc-eX1tMB" "/usr/src/glibc".

So it seems that the "sourceFileMap" does not work here.

I first add an issue for the C/C++ extension, but a comment mentioned that it could be an issue with vscode remote : 
https://github.com/microsoft/vscode-cpptools/issues/7389

      {
        "name": "(gdb) Launch",
        "type": "cppdbg",
        "request": "launch",
        "program": "${workspaceFolder}//${fileBasenameNoExtension}",
        "stopAtEntry": false,
        "cwd": "${workspaceFolder}",
        "environment": [],
        "externalConsole": false,
        "MIMode": "gdb",
        "miDebuggerPath": "/usr/bin/gdb",
        "setupCommands": [
          {
            "description": "Enable pretty-printing for gdb",
            "text": "-enable-pretty-printing",
            "ignoreFailures": true
          }
        ],
        "sourceFileMap": {
          "/build/glibc-eX1tMB": "/usr/src/glibc"
        },
      },

    OS and Version: Windows 10
    VS Code Version: 1.55.2
    C/C++ Extension Version: v1.3.0

**Comment by weinand** [comment]
I'm not convinced that this is a VS Code issue. Please see https://github.com/microsoft/vscode-cpptools/issues/7389#issuecomment-824922480

**Comment by IsraelCohen54** [comment]
Probably the same, but I didnt see there any simple way to solve it... thanks anyway, guess I will manage :)

**Comment by i-am-david-fernandez** [comment]
For what it's worth, I seem to be having the same problem (or at least, the same symptom) trying to debug a python app in a container via remote-ssh (i.e., Windows VSCode -> Linux VM via remote-ssh -> python app in docker container).

I get this:

> Unable to open 'views.py': Unable to read file 'vscode-remote://ssh-remote+vm-hostname/a/b/health/views.py'
> (Error: Unable to resolve nonexistent file 'vscode-remote://ssh-remote+vm-hostname/a/b/health/views.py').

I realise I'm using a completely different debugger (`debugpy`), and a different remote mechanism (`ssh`) but the symptoms suggest a common root cause. I cannot get path mappings to have any effect (I've tried using both `pathMappings` and `sourceFileMap`), but if I create an appropriate symlink within the VM (such that the absolute path to `views.py` in the container matches that within the VM, via the symlink), then things seem to work fine.

(I've posted this in the linked `cpptools` ticket as well as that seems active).

**Comment by weinand** [comment]
@i-am-david-fernandez please note that "path/source mappings" like the `"sourceFileMap"` property in the launch config from [above](https://github.com/microsoft/vscode-remote-release/issues/4929#issue-864821347) are **private properties** of the debugger you are using. VS Code knows nothing about them, and even if they have similar names for different debuggers, their implementation is totally unrelated. A property `"sourceFileMap"` for the gdb debugger does not mean that the Python debugger provides the same. If you see squigglies in the launch.json, then this means that the use of the property has a problem.

**Comment by i-am-david-fernandez** [comment]
@weinand Thank-you for such a rapid response.

I must admit that I did (do) not understand how the different parts (pydebug, remote-ssh, python extension) worked together, and somewhat assumed that the remote extension was, as a kind-of middle-man, responsible for the translation. I'm still not certain whether you mean the "application-end" debugger (`pydebug` in my case) or the "code-end" debugger (the VS Code [python extension](https://github.com/microsoft/vscode-python)) performs the mapping.

Whichever, you've clarified that my problem does not lie with the remote extension.

Edit: @weinand Thanks to your comment, I've found what I think is the root cause of my problem: https://github.com/microsoft/vscode-python/issues/14820 Thank-you for helping me find it!
