### ISSUE TITLE
Duplicated debug entries when using WSL remote with any Language server

### ISSUE THREAD

**Issue by Fubuchi** [microsoft/vscode-remote-release#4954]
Initially, I thought it was a extensions' issue when they work with the WSL remote extension, so I created an issue here: microsoft/vscode-java-debug#976

But now, It happens with other language servers too.

- VSCode Version: 1.55.2 (user setup)
- Local OS Version: Windows 10 pro 1909 build 18363.1198
- Remote OS Version: Void Linux
- Remote Extension/Connection Type: WSL

Steps to Reproduce:

1. Install a language server (tested with Scala metals, redhat's java language server and rust analyzer)
2. Create a simple project for the corresponding language.
3. Open the project and create a launch.json file with some entries.
4. Close the project and open it again, one of the entries will be duplicated
  ![image](https://user-images.githubusercontent.com/42483897/116193200-2cc57c80-a759-11eb-8cc1-9d3008fcccd4.png)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No 

Additional information: I notice that VS Code create 2 folders with the same hash name in `C:\Users\<user name>\AppData\Roaming\Code\User\workspaceStorage` and `\\wsl$\<distro>\home\<user name>\.vscode-server\data\User\workspaceStorage`

When I deleted the folder on Windows, the duplicate entry was removed, but it appeared again when I closed and reopened the project.

I didn't have any issue with rust and Scala extensions in WSL months ago, so there must be a recent change that cause the issue

Sample java project: 
[test.zip](https://github.com/microsoft/vscode-remote-release/files/6382235/test.zip)

**Comment by bamurtaugh** [comment]
Thanks for the details and sample project @Fubuchi.

cc @aeschli (and @isidorn @connor4312 for any debug input) - looks like I'm able to repro when I use the Test1 app attached in the zip above, create a Java launch config, close the folder, and then reopen. I also previously created a Chrome launch config and it has since been deleted, but it still shows up:
![image](https://user-images.githubusercontent.com/25310137/116321819-ac5e4600-a76f-11eb-90b5-3742ca079b3a.png)

When I reopen in Windows, the duplicate "Launch Current File" entry and the previously deleted Chrome entry disappear:
![image](https://user-images.githubusercontent.com/25310137/116322232-7a011880-a770-11eb-9579-5911877bd735.png)

WSL logs:

[2021-04-27 22:45:29.638] Resolving wsl+ubuntu-18.04, resolveAttempt: 1
[2021-04-27 22:45:29.724] Starting VS Code Server inside WSL (Ubuntu-18.04)
[2021-04-27 22:45:29.724] Extension version: 0.56.1, Windows build: 19042. Multi distro support: available. WSL path support: enabled
[2021-04-27 22:45:29.725] No shell environment set or found for current distro.
[2021-04-27 22:45:29.886] Connecting to daemon started by other Remote-WSL window... 5.4.72-microsoft-standard-WSL2 Ubuntu-18.04
[2021-04-27 22:45:29.892] Pinging 172.22.101.119:36047...
[2021-04-27 22:45:29.898] 172.22.101.119:36047 responded
[2021-04-27 22:45:29.898] WSL resolver response: 172.22.101.119:36047
[2021-04-27 22:45:29.898] To debug connection issues, open a local browser on http://172.22.101.119:36047/version

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/121148
