### ISSUE TITLE
add context specification to k8s-container remote URIs

### ISSUE THREAD

**Issue by emcake** [microsoft/vscode-remote-release#4975]
(requested in #4684)

Currently the vscode-remote URIs (which drive the 'open recent' list, and various people's attempts to open code into k8s from a CLI) don't specify the context to use, and so will use the default kubeconfig context.

For multi-context environments, users might swap their default context around depending on different activities, and this can change outside VSCode as it's global per-user. This means the 'Open Recent' links will fail, and it's not possible to easily specify a direct link to code in k8s.

Quick fix is to add the context as another parameter into the remote URI (like namespace or container name) and then use the `--context` flag on the `kubectl` command line. One thing to watch for is that in certain environments (e.g AWS) it's common to have special characters like `:` or `/` in the context name, so it may need url-escaping.

**Comment by PavelSosin-320** [comment]
Is it a good idea? The Docker's context makes Containers and hosts, clusters where they are running completely independent, i.e. serverless. The only place where the Server address and its properties are stored is the tiny file in the User's home directory - context. Docker context commands don't affect any images or containers.  Serverless is Docker's fundamental concept.

**Comment by emcake** [comment]
This isn’t about docker context, this is about Kubernetes context. It’s already in use, it’s just not currently tracked in the remote URI, which means ‘Open Recent’ links break if the user changes their global context.

**Comment by kwlzn** [comment]
this would be huge for us to support unlocking https://github.com/microsoft/vscode-remote-release/issues/4684

**Comment by PavelSosin-320** [comment]
If VSCode uses docker client then docker context ~/.docker defines all ens points: Standalone docker servers, Swarm cluster, Kubernetes cluster.  If VSCode uses Kubectl then Kubernetes context ~ ./kube defines Cluster end-point. But it can't use docker. Kubectl cluster may support Docker API. but not wise versa. The container image is always the same OCI container image, there is nothing specific in Kubernetes containers. The phrase "Open in container phrase is misleading because its meaning is a composition of many totally independent steps: build container, run container interactively, and open mounted workspace. User may build container locally using buildah, docker or buildkit, Then run it in Podman, remote Swarm, or Kubernetes cluster without explicit passing of end-point.  This concept is the result of mutual agreement of all Container software providers and perfectly works until somebody will break it. Context switch can be done only via Docker or Kubectl config commands intentionally and can break nothing if the client correctly processes API errors and reconnect to the desired end-point when user wants it. What developer can do If the Cluster's operator will take the cluster down or the customer will migrate to another infrastructure?

**Comment by emcake** [comment]
I’m specifically talking about changing the `vscode-remote` uri generated when you use the ‘attach vscode to pod’ option against a kubectl cluster.

If it’s unspecified in the URI it’ll use the default cluster.

**Comment by PavelSosin-320** [comment]
@emcake It's always true: if o context is specified the default is used. This is the client standard behavior intended to simplify maintenance and allow IT automation. Imagine a situation when a team of 5-6 developers is working on the same project and supporting multiple customers. It is very common in big, globally deployed cloud application development. They need to share not only code but also configuration. Context configuration (deployment end-point, security, orchestration) is in the DevOps area and developers are happy not to take it into account at all.

**Comment by emcake** [comment]
I don’t understand what you’re trying to say. Are you saying it is a bad idea to use the `--context` argument in kubectl to target a given cluster? Because the vscode-remote URI already encodes the pod name, which is specific to that cluster. I am not proposing to set the user’s default context, I’m proposing to use that context for commands for attaching to that pod. 

The ‘Open Recent’ link doesn’t work if you change your default context. This would make the link always work if you change your context.

**Comment by PavelSosin-320** [comment]
I would like to say a simple thing: every docker and kubectl create resource command creates optionally cid / pid files in the user workspace to reuse them for the subsequential "recent" commands. Saving context doesn't help too much because context can be changed by kubectl config command without changing its name. The same context will point to the different Kubernetes cluster. IT automation can do it unattended. 
In any case Pod itself is not persisted object. Nothing can keep the connection between client session and Pod instance except the built-in affinity mechanism. All stateful Cloud applications use it without a single additional line of code.

**Comment by emcake** [comment]
While I think this is true, it’s irrelevant to the proposal at hand. The remote URIs are already encoding a bunch of context about how they are run, including the pod name and the container name within the pod to connect to. 

The URIs are quite fragile and will break if a deployment restarts (we actually use StatefulSet to help with this); the only difference from this proposal is that we allow encoding one extra potentially fragile piece of information. For people (like me, and @kwlzn ) who have no plans for changing these things via automation I can use it to address a given pod for longer; for those with automation, it doesn’t really change anything since messing with their context under the hood would _already_ break their ‘Open Recent’ links and still would.

**Comment by PavelSosin-320** [comment]
@emcake The comprehensive solution for pure Kubernetes-based Cloud development environment is Eclipse/Che with all its plugins and extensibility by VSCode plugins. You need only Web browser for trial. VSCode is essentially a Client-server solution.

**Comment by chrmarti** [comment]
I will use `kubectl config current-context` to read the current context's name and will pass that along with the URI. If the Kubernetes extension ever supports navigating pods from two different clusters (as opposed to just the 'current' cluster), we will need to find a way to get at the context a pod object belongs to in the 'Attach Visual Studio Code' command.

**Comment by PavelSosin-320** [comment]
Kubernetes provides a fully qualifies Pod Id via kubectl get pod --wide. If
Pod name is stored at the client-side or Pod is labeled and the label is
stored at the client side, sp, what is the problem? But The problem is that
neither Windows nor VSCode has no session scope mechanism comparable with
the simplest Linux via /run/ folder or Chrome browser. In the Cloud
environment when Client-Server synchronization is broken user is asked to
reload browser and it doesn't erase session's cookies used by affinity.

**Comment by chrmarti** [comment]
@emcake Could you verify this is working with VS Code Insiders and the latest Remote-Containers?

**Comment by rzhao271** [comment]
@kwlzn can you try verifying this issue using [VS Code Insiders](https://code.visualstudio.com/insiders/) and the latest Remote-Containers extension?

**Comment by chrmarti** [comment]
Verification involves having two Kubernetes clusters available and checking that changing the 'current' cluster does not break 'recent folder' entries.

**Comment by emcake** [comment]
Confirmed this works for me on code-insiders.
