### ISSUE TITLE
Docker compose remote container project name issue

### ISSUE THREAD

**Issue by Lokiem** [microsoft/vscode-remote-release#498]
I know what this issue is, what causes it, and what is required to fix it, though this issue does relate to Docker Toolbox it appears to be a relatively minor change.

I believe recently a change was made to the Remote Container extension, somewhere in the last week or two that added an underscore to the project name on docker-compose.

On Windows, Docker Toolbox installs version 1.20.1 of docker-compose, and in this version the only characters supported in the project name are alphanumerics. The extension appears to use the project name of the current directory + "_devcontainer" e.g. "currentdirectory_devcontainer", which causes the process that creates the container to wait forever after creating the container, the "Creating ContainerName ... done" bit.

It's waiting for an event from the project name specified earlier, "currentdirectory_devcontainer" but any unsupported characters are stripped out of the project name, so this event never comes, what does come however is an event for "currentdirectorydevcontainer".

The fix is to remove the underscore, though as the code isn't open source, I can't speak of the impact this might have for anything else. If the underscore was added for nothing functional, there is a minor win for Docker Toolbox users.

A workaround temporarily is to allow the process to hang after creating the container, close the code-insider window, open another code-insider window and instead attach to the running container.

This would probably happen regardless of OS, version of insiders, specifics of the project, etc. The key players would be the docker-compose version (1.20.1~) and likely anything after version 0.53.0 / 0.54.0 of the Remote - Containers extension.

Hopefully there is enough information here to assist anyone currently experiencing this issue, and to pinpoint the exact location / version this issue came from.

**Comment by chrmarti** [comment]
The problem we were fixing here is that if the devcontainer.json is in the `.devcontainer` folder, the project name would always be `devcontainer` which is not unique and resulted in conflicts when you tried to work on two compose projects.

We could add a config option for the project name to the devcontainer.json or look into letting `COMPOSE_PROJECT_NAME` pass through from a `.env` file.

I'd like to avoid Toolbox-specific fixes since that is not supported.

**Comment by Lokiem** [comment]
More configuration options is definitely a winner, being able to set the project name in the devcontainer.json would be great.

**Comment by chrmarti** [comment]
You have some indirect control over it: As a workaround you could move your docker-compose.yml to a subfolder (or the main folder). We only add the `_devcontainer` when the docker-comopse.yml is in the .devcontainer folder.

**Comment by rawtaz** [comment]
Got bitten by this too right now. Two completely separate projects, each with their `docker-compose.yaml` file in the `source/` folder in the project. Docker Compose doesn't have a problem with this because in each of those folders is a `.env` file with `COMPOSE_PROJECT_NAME=foo` where "foo" is different in the two projects. This makes Docker Compose treat these as separate projects, and there aren't any conflicts with image/network/volume/container names at all.

However, the Remote Container extension doesn't pay attention to the .env file and the COMPOSE_PROJECT_NAME environment variable, so it fires both projects up with the project name "source". After that, things go downhill right away - e.g. in the file explorer both project windows show the same content, and both project windows are obviously attached to the same project's container, instead of separate containers.

The Remote Containers really has to take into account the configured project names, otherwise it's pretty unusuable without ugly workarounds like moving `docker-compose.yaml` into differently named folders. Not really workable when you have lots of projects :)

**Comment by chrmarti** [comment]
Fixing with #222
