### ISSUE TITLE
Merge `PATH` environment variable when probing the user environment

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#5032]
Related:
- Environment variables are not always set when SSHing into container https://github.com/microsoft/vscode-remote-release/issues/4781
- Set "userEnvProbe": "interactiveShell" by default https://github.com/microsoft/vscode-dev-containers/pull/848

**Comment by chrmarti** [comment]
Published 0.179.0 with `"userEnvProbe": "loginInteractiveShell"` as the default. (Only for Insiders.)

@Chuxel Should we remove the `/etc/profile.d/00-restore-env.sh` workaround to fully test this? It might be good to do this soon to collect feedback before the milestone goes into endgame.

/fyi @bamurtaugh

**Comment by Chuxel** [comment]
@chrmarti PR is up for a general solution for SSH: https://github.com/microsoft/vscode-dev-containers/pull/871

I ended up having to tackle a number of scenarios to get it to work because where the base path that everything builds up from even varies between `debian` and `ubuntu` let alone zsh to sh/bash.  This is pretty easy to do for your own image, but making it generic took some real work.

**Comment by chrmarti** [comment]
@Chuxel Thanks! I was trying to come up with a way to do this in the extension:

Couldn't we split the problem into 'container environment variables are missing in ssh' and 'PATH is overwritten in /etc/profile'? With that a general solution could be:
- Add container environment variables to `/etc/environment`. (As you proposed elsewhere.)
- Update /etc/profile if it unconditionally sets PATH.

A `sed` for updating /etc/profile appears to be:
```
sed -i -E 's/((^|\s)PATH=)([^\$]*)$/\1${PATH:-\3}/g' /etc/profile
```

This will change any `PATH=...` lines to the conditional `PATH=${PATH:-...}` if the original value does not contain a `$` (the heuristic for detecting when PATH is not overwritten unconditionally). We will need to test this against the various cases we know. So far it looks promising.

**Comment by Chuxel** [comment]
That seems to work as well - here's a revised version of these SSH scripts and the container test that uses that model: https://github.com/Chuxel/ssh-env-fix-test

Alpine does hard code in /etc/profile and does not have an /etc/environment by default. centos didn't seem to do any hardcoding on first glance.  For alpine and centos, zsh sources /etc/profile (while debian and ubuntu do not).

So, it looks like on the surface that this logic would work there too. Right now the SSH script in that repo is using an ENTRYPOINT still because of where it happens in the lifecycle... but if the devcontainer CLI/extension did this, that wouldn't be required I think.  

Restoring the rest of the env vars might also be possible to do via /etc/environment... I think the trick there is making sure that we don't set things that would cause problems because they are user specific.  I almost wonder if keeping that and secrets handling as a profile.d script is better since that can safely assume anything already set is right, and only set env vars that are missing.

**Comment by chrmarti** [comment]
Would updating /etc/profile while setting up the container be soon enough? I assume any ssh session would come after that, but sshd might already be running.

The default for /etc/environment entries is to preserve any existing value. E.g., Ubuntu sets the PATH in /etc/environment, but we don't see that overwrite the container's PATH when there is one.

**Comment by Chuxel** [comment]
> Would updating /etc/profile while setting up the container be soon enough? I assume any ssh session would come after that, but sshd might already be running.
>
> The default for /etc/environment entries is to preserve any existing value. E.g., Ubuntu sets the PATH in /etc/environment, but we don't see that overwrite the container's PATH when there is one.

The ENTRYPOINT that does the updates is the one that starts the SSH server, so for that part we're good.  For `/etc/profile.d`, each SSH session gets a brand new interactive login shell so really any of the files would take care of it.  The goal is just to set variables not already set.  If they are set, then they came from the rc/profile files and therefore would not be missing... its just the Dockerfile driven ones that are a problem.

I can see if `/etc/environment` covers it.

**Comment by Chuxel** [comment]
Oh - one question here. One of the things the ENTRYPOINT does not have access to is the path to VS Code server to wire in the `code` command along with the `BROWSER` env file.

Is there a way that we could set these that you can think of? Technically multiple vscode server instances running - I might be able to extract it from `ps -ef`, but that seems clunky.  I wonder if we could set a symlink to "current" for whatever the last running vscode server is.

**Comment by chrmarti** [comment]
I would like to update /etc/profile from the extension. That could be after sshd started, but before any login shell. I see this as a potential fix for the PATH issue.

For ssh we also need a fix for the container env variables. Maybe /etc/environment also covers the zsh case. I need to investigate some more myself too. 

Adding a symlink for code sounds good. Not sure about BROWSER, that is set by VS Code.

**Comment by Chuxel** [comment]
@chrmarti Yeah I did some further looking. `/etc/environment` does handle zsh as well, but it can overwrite things that should not be overwritten.  e.g. if HOME is set to /does/not/exist, that is used.

So, it has to filter out things sh/bash/zsh set that are user or process specific.  This appears to do the trick from the ENTRYPOINT:

```bash
if [ ! -f /usr/local/etc/vscode-dev-containers/env-restored ]; then
    # Remove user/context specific default vars:
    # - https://ss64.com/bash/syntax-variables.html#:~:text=Default%20Shell%20Variables
    # - https://zsh.sourceforge.io/Doc/Release/Parameters.html
    VARS_TO_FILTER_OUT='USER|USERNAME|GROUPS|HOME|SHELL|SHELLOPTS|HOST|HOSTNAME|IFS|FUNCNAME|FUNCNEST|OPTARG|OPTIND|OPTERR|OSTYPE|MACHTYPE|CPUTYPE|PPID|TTY|TTYIDLE|TRY_BLOCK_ERROR|TRY_BLOCK_INTERRUPT|PIPESTATUS|RANDOM|SECONDS|COMP_WORDS|COMP_CWORD|COMP_LINE|COMP_POINT|COMPREPLY|DIRSTACK|PWD|OLDPWD|TERM|TERMINFO|TERMINFO_DIRS|TERM_PROGRAM|TERM_PROGRAM_VERSION|COLORTERM|SHLVL|LOGNAME|MAIL|MAILPATH|MAILCHECK|BASH|BASH_ENV|BASH_VERSION|BASH_VERSINFO|UID|GID|EUID|EGID|LINENO|CDPATH|VENDOR|ZSH|ZSH_ARGZERO|ZSH_EXECUTION_STRING|ZSH_NAME|ZSH_PATCHLEVEL|ZSH_SCRIPT|ZSH_SUBSHELL|ZSH_VERSION|ENV'
    BASE_ENV_VARS="$(declare -x +r +f | grep -vE "(${VARS_TO_FILTER_OUT})="| grep -oP '(declare\s+-x\s+)?\K.*=.*')"
    ETC_ENV_VARS="$(cat /etc/environment 2>/dev/null || echo '')"
    # Augment BASE_ENV_VARs with anything in ETC_ENV_VARS
    while IFS= read -r variable_line; do
        VAR_NAME="${variable_line%%=*}"
        if [ "${VAR_NAME}" != "" ] && ! echo "${BASE_ENV_VARS}" | grep "${VAR_NAME}=" > /dev/null 2>&1; then
                BASE_ENV_VARS="$variable_line\n${BASE_ENV_VARS}"
            fi
        fi
    done <<< "${ETC_ENV_VARS}"
    echo -e "${BASE_ENV_VARS}" | sudoIf tee /etc/environment
    sudoIf touch /usr/local/etc/vscode-dev-containers/env-restored
fi
```

Codespaces secrets then require an additional step - right now I kept this in `/etc/profile.d` to avoid saving secrets to in an unmounted spot and reference it from `/etc/zsh/zlogin`

Same repo has this in it - along with the PATH workaround near term: https://github.com/Chuxel/ssh-env-fix-test

**Comment by Chuxel** [comment]
@chrmarti Nope. I overrode it in the script for paranoia sake.  Helps if someone does `env -i zsh` but that's the only time I see it getting hit.

**Comment by chrmarti** [comment]
Publishing Remote-Containers 0.180.0 with the patching of /etc/profile. (Attaching to a container will merge paths instead, because we don't create/own the container.)

I still need to explore adding environment variables to /etc/environment. That might help fix #4781.

**Comment by Chuxel** [comment]
@chrmarti Yeah it appears to do it like I mentioned above with that ENTRYPOINT code above.  The remaining bit is codespaces secrets.  This I have covered with an /etc/profile.d script:

```bash
#!/bin/sh
# If not codespaces, already run, or secrets already in environment, so return
if [ "${CODESPACES}" != "true" ] || [ "${VSCDC_FIXED_SECRETS}" = "true" ] || [ ! -z "${GITHUB_CODESPACES_TOKEN}" ] || [ ! -f /workspaces/.codespaces/shared/.user-secrets.json ]; then
    return
fi
$(cat /workspaces/.codespaces/shared/.user-secrets.json | jq -r '.[] | select (.type=="EnvironmentVariable") | "export "+.name+"=\""+.value+"\""')
export VSCDC_FIXED_SECRETS=true
```

I didn't want to persist them in the container itself since they can be user specified secrets that shouldn't be so I just parse the mounted json file.  @jkeech - Would it make sense to instead have Codespaces output a `.env` file in the same location Codespaces generates we can just source instead?  This code adds about 40ms to startup due to the `jq` command.

**Comment by jkeech** [comment]
> @jkeech - Would it make sense to instead have Codespaces output a `.env` file in the same location Codespaces generates we can just source instead? This code adds about 40ms to startup due to the `jq` command.

Yes, I think so. We've already talked about this for direct SSH support, but now that the userEnvProbe also has it on the critical path for container creation/startup, I think we should do this. The current file was never meant for consumption in a terminal in the container or intended to be an official contract, so moving to a `.env` file as a more formal contract is better anyway in addition to the perf gains and removal of the dependency on `jq`.

**Comment by chrmarti** [comment]
Closing this as the planitem for the `PATH` issue. I'll continue work on the SSH environment variables in #4781.
