### ISSUE TITLE
Remote-SSH : BUG: Cannot Reconnect after Disconnected

### ISSUE THREAD

**Issue by preethamraj27** [microsoft/vscode-remote-release#5037]
Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:06:21.189Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1.Start VS-Code with Remote-SSH
2. Create a new file, dont save.
3. Disconnect from the network , wait for all the 'Reload window' dialog boxes to time out. 
4. Now, You cannot connect back to the same host. 

At this point your forced to close the session/window & open a new one. 
OR you can 'Connect current window to Host' , that will also reload the entire window & your open files/terminals layout all is lost. 

It would be really nice, if from the disconnected state , if we could just reconnect (I am probably over simplifying the problem). 

Pls let me know how I can help.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aronchick** [comment]
@roblourens  if you're internal to microsoft, you can repro the behavior yourself.

- Connect to a VNET VPN (required because MSFT IT blocks 22)
- Connect to a VM that is enabled only via VNet via VSCode
- Begin working, including in a terminal
- Disconnect the VNET VPN
- Observe that VSCode is unhappy
- Reconnect the VPN
- Observe that VSCode recovers "badly" - refreshes the entire window, drops all your terminal windows, etc. 

I found that intermittent connections for SSH directly (where you didn't lose the IP address, but you lost connect) were handled much more elegantly.

**Comment by roblourens** [comment]
I can't repro the scenario you are talking about but I think you are just describing what happens when we fail to reconnect and have to reload the window. If you lost the IP address that would probably happen. OP seems resolved, closing
