### ISSUE TITLE
Open Workspace in Container...  disappeared

### ISSUE THREAD

**Issue by rubensa** [microsoft/vscode-remote-release#5185]
After the last update the option to "Open Workspace in Container..." disappeared from the list of Remote-Container menu options.  Now you must "Open Folder in Container..."  and wait for VSCode realizes there is a workspace file in the folder and ask you to open it.

**NOTE**:  With a bit more of examination, looks like the option did not fully disappeared but now it's only accesible if you show all commands (F1 or Ctrlf+Shift+P) but not if you click on the lower left green Dev Container icon.

- VSCode Version: 1.57.0
- Local OS Version: Ubuntu 20.04.2
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Docker

**Comment by chrmarti** [comment]
That's intentional. We noticed there were too many commands in the remote menu when you have Remote-Containers installed with Remote-SSH and may Remote-WSL and decided to remove those that we felt were used less often. They are still available in the command palette, as you noticed. Closing with that, thanks.

**Comment by rubensa** [comment]
Thanks for your answer @chrmarti 

Shouldn't things like this be added to the release notes so anyone, like me, using a feature knows about the change?
