### ISSUE TITLE
[WSL] Valid Linux file names flagged as invalid on rename operation

### ISSUE THREAD

**Issue by mmacy** [microsoft/vscode-remote-release#519]
- VSCode Version: `1.35.0-insider (user setup)`
- Local OS Version: `Microsoft Windows [Version 10.0.17763.503]`
- Remote OS Version:
  ```
  Distributor ID: Ubuntu
  Description:    Ubuntu 18.04.2 LTS
  Release:        18.04
  Codename:       bionic
  ```
- Remote Extension/Connection Type: **WSL**

Steps to Reproduce:

1. In remote OS, create a file with an invalid Windows file name: `touch blarg??.txt`
1. In VS Code, open the directory containing the file: `code-insiders .`
1. In the Explorer, right-click on the file, then select **Rename**
1. The following error is displayed, which is incorrect as the remote OS supports the `?` character in filenames:

"The name **blarg??.txt** is not valid as a file or folder name. Please choose a different name."

![image](https://user-images.githubusercontent.com/13394541/58648517-bc88f480-82be-11e9-9641-6b7cbb079acd.png)

Does this issue occur when you try this locally?: Unable to perform same repro as Windows prevents creation of file name with invalid (in Windows) characters.
Does this issue occur when you try this locally and all extensions are disabled?: See previous.

Additional info:

A separate but related bug exists in which opening the `blarg??.txt` file directly with `code-insiders blarg??.txt` opens VS Code with a blank "blarg" tab (note truncated file name) and bonus empty `.vscode-insiders` file tab:

```console
mmacy@marsma-win:~$ echo "This is the blarg??.txt file" >> blarg??.txt
mmacy@marsma-win:~$ cat blarg??.txt
This is the blarg??.txt file
mmacy@marsma-win:~$ code-insiders blarg??.txt
```

![image](https://user-images.githubusercontent.com/13394541/58649220-65841f00-82c0-11e9-9075-e12c234dcacf.png)

(Let me know if you'd like a separate issue on that one.)

**Comment by aeschli** [comment]
@isidorn Shouldn't that be an easy fix to loosen the validation rules when on a remote URL?

**Comment by isidorn** [comment]
The issue is [here](https://github.com/Microsoft/vscode/blob/cd16f82b83b7b6e6f0fdb25ab18ca7dba7c6a932/src/vs/workbench/contrib/files/browser/fileActions.ts#L772)
When we call [isValidBasename](https://github.com/Microsoft/vscode/blob/cd16f82b83b7b6e6f0fdb25ab18ca7dba7c6a932/src/vs/base/common/extpath.ts#L145) the isWindows is checked based on the renderer preference, it should be checked based on the extension host platform
What is the best way to get the EH platform, looking at what service?

**Comment by aeschli** [comment]
@isidorn `IRemoteAgentService.getEnvironment()`

**Comment by aeschli** [comment]
@isidorn  For URIs with scheme `vscode-remote` the platform is defined by `IRemoteAgentService.getEnvironment()`.
But there can be potentially also also more file system providers with file name rules that we don't know.

To keep it simple, I would suggest: just check against the UNIX_INVALID_FILE_CHARS for all non-file URIs. In case it turns out that the underlying file system is more restrictive, the user will get an error on the actual rename.

**Comment by isidorn** [comment]
@aeschli thanks for the suggestion. This makes sense to me and I have just pushed it.
