### ISSUE TITLE
xdg-open creates automatic port forward in Remote SSH despite remote.autoForwardPorts being false

### ISSUE THREAD

**Issue by dezsiszabi** [microsoft/vscode-remote-release#5236]
- VSCode Version: 1.58.0-insider (commit: 6afedfdad59d1f1ba4b614341d21c67775e158a9)
- Local OS Version: Windows 10 Version 21H1 (19043.1055)
- Remote OS Version: Ubuntu 20.04.2 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Set `remote.autoForwardPorts` to `false`.
2. Run `xdg-open "http://localhost:4092"` in integrated terminal.
3. External browser opens and an automatic port forward is set up.

My expectation is that VSCode shouldn't set up the automatic port forward since the `remote.autoForwardPorts` settings is set to `false`. I understand why this happens and I do see there are some references to this behavior here and there (related to `vscode.env.openExternal` API), but I still find it counter-intuitive.

Either change the behavior of `remote.autoForwardPorts` or create a new setting which prevents the creation of the automatic port forward in this scenario as well.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bamurtaugh** [comment]
cc @alexr00 do you have any thoughts here?

**Comment by alexr00** [comment]
> External browser opens and an automatic port forward is set up.

If we don't forward the port when an extension calls `openExternalUri` then you'd get an error when you tried to connect to 4092 from your browser.  `openExternalUri` is an _explicit_ port forward (an extension has decided you need to access that port locally). Whereas an automatic port forward happens when VS Code looks for ports to forward, either by watching terminal/debug output or by looking at your proc filesystem. 

I can understand where the confusion comes from though. I'm adding this to the description of `remote.autoForwardPorts`: "Disabling this setting will not prevent all ports from being forwarded. Even when disabled, extensions will still be able to cause ports to be forwarded, and opening some URLs will still cause ports to forwarded.".
