### ISSUE TITLE
Allow specifying array in workspaceMount so multiple paths can be mounted on container running on remote host

### ISSUE THREAD

**Issue by Ldcabansay** [microsoft/vscode-remote-release#5254]
Hello,

I've been unable to figure out how to configure a `devcontainer.json` to bind _multiple_ existing paths on a remote host to a container that is also running on that host. 

I've successfully configured a setup to use a local `devcontainer.json` and `dockerfile` to build, run, and connect to a container environment on a remote host and can use `workspaceMount` to bind a single existing path on that host to my container. 

However I cannot seem to find a way to specify multiple paths. Putting the paths on the same tree is not a viable option for my use case, so I would really appreciate being able to specify an array in `workspaceMount` so it would more closely resemble the functionality of `mounts` when binding paths to containers running locally.

My current workaround is to kick-off the container manually on the remote host with all mounts specified in the run command then attaching to that running container manually, but ideally this would be specified directly in the `devcontainer.json`.

**Comment by PavelSosin-320** [comment]
@Ldcabansay Multiple paths or multiple workspaces? Multiple workspaces in parallel is a really cool feature but rarely found in the real world because the workspace normally contains some unique configuration files in its root, like devcontainer.json. multiple source dir, lib, obj, build paths are defined in the workspace configuration. In this case, used tools have to understand such lists. Please, clarify your use case in more precise terms than "not an option". The possibility to add multiple VOLUME directives to the Dockerfile is expected from the development environment with persistent storage defined during the docker run. Really, missed feature.

**Comment by chrmarti** [comment]
Couldn't you use the `"mounts"` property for the additional mount points?

**Comment by Ldcabansay** [comment]
Hi yes, realized this just a bit ago and finally got it working. Seems I was getting a failure internally because one of the mount paths on the host needed to be created beforehand. I missed that --mount doesn't create a non-existent path for you like -v does. The error made me think it was referring to trying to mount something on my local machine, not the remote host.

**Comment by chrmarti** [comment]
Thanks, closing.
