### ISSUE TITLE
vagrant

### ISSUE THREAD

**Issue by jphilip** [microsoft/vscode-remote-release#529]
Remote development with Vagrant boxes in addition to Docker containers

**Comment by Chuxel** [comment]
@jphilip Thanks for the feature request! Out of curiosity, does the Remote - SSH extension meet some of your needs here?  Given Vagrant provisions VMs often via SSH, are you looking for streamlining or is there something about your Vagrant workflow that is blocking you?  Just trying to get a sense of what might be needed.

**Comment by jphilip** [comment]
Hi,
Would that work for editing code on the host and debugging on the VM, as
Vagrant synchronizes the 2?
Thanks.

**Comment by Chuxel** [comment]
@jphilip I don't know your exact Vagrant setup, but yes it should work (assuming the VM is Linux since we don't support Windows quite yet).  The Remote - SSH extension allows you to use VS Code locally to edit code in the VM.  Depending on your vagrant setup, if you have a local file mount setup these files can come from your local filesystem.  One other tip: Even without Vagrant, you can [use SSHFS](https://code.visualstudio.com/docs/remote/troubleshooting#_using-sshfs-to-access-files-on-your-remote-host) or [rsync](https://code.visualstudio.com/docs/remote/troubleshooting#_using-rsync-to-maintain-a-local-copy-of-your-source-code) to make the remote files available locally or vice versa.  I'd be interested to hear if any of these work for you.

**Comment by cmeans** [comment]
@jphilip It's working fine with Vagrant for me, but it does depend on your version of key dependencies (as are listed in the docs).

**Comment by madeddie** [comment]
Remote - SSH works fine with Vagrant, would be cool if we could use Vagrant as SSH configuration input too, since the IP addresses of the created VMs are dynamic by default (a new one per created VM).

**Comment by J-M0** [comment]
I've been experimenting with the Remote - SSH extension and it will work for Vagrant, but needs just a few tweaks to be really great.

The biggest problem is not being able to have per-workspace SSH configs which makes it difficult to work with these ephemeral machines. Since their ports and authentication keys can change at any time, VS Code should have a workspace-level setting that pulls the SSH config settings from `vagrant ssh-config`. This is the minimum change needed to make working with VS Code and Vagrant viable.

Some nice-to-haves would be some options that are similar to the Remote - Containers extension:

#### Reopen in Vagrant
Run `vagrant up` and then SSH directly to the `/vagrant` directory on the VM

#### Use ForwardAgent
Make sure that ForwardAgent is always used when connecting to a Vagrant VM from VS Code

#### Copy ~/.gitconfig

Copy the user's `.gitconfig` into the VM

#### Specify extensions to install on the VM
Just like in `devcontainer.json`, allow the user to specify extensions that should be installed in the VM

#### Close Remote Connection
Close the remote connection, switch back to the local directory, and optionally shutdown the Vagrant VM

**Comment by Tebro** [comment]
We just started using the combination of Vagrant + Remote SSH and it works quite well. Though some extra automation for the `vagrant ssh-config` part would be nice, could it be automatically generated by the extension and saved in the .vscode directory? 

We also added some port forwards to the SSH config so even if it is automated it would be nice to have it somewhere where it can be modified easily.

**Comment by roblourens** [comment]
It seems that this works with the correct configuration- we don't plan to have any vagrant-specific support built-in, but maybe another extension could do it
