### ISSUE TITLE
Improve discoverability of secondary dev container configurations

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#5434]
Secondary dev container configurations are not that easy to discover by users:
- users have to select 'Show All Configurations' from the quick pick and this entry can appear at the bottom of the list
- users cannot easily find a configuration by typing. When typing a config name on the first page it isn't found

Ideas:
- Show the 'Show All Configurations' command at the top of the list
- Show the configurations in a single list, but in two or more sections 'primary', 'secondary' (needs better names). Can we use quick pick categories (see screenshot) for this? 
![image](https://user-images.githubusercontent.com/172399/128843468-4b68ce28-cdc1-4a90-800d-cc39e77ba8e5.png)

//CC @Chuxel @bamurtaugh

**Comment by chrmarti** [comment]
The separators (or categories) are currently not in the API. Feature request: https://github.com/microsoft/vscode/issues/74967.

**Comment by bamurtaugh** [comment]
> Show the 'Show All Configurations' command at the top of the list

This resonates with me. Moving it above/below "Learn More:"

![image](https://user-images.githubusercontent.com/25310137/128906690-86307788-62d1-494b-a8e4-fa97d3864e03.png)

> Show the configurations in a single list, but in two or more sections 'primary', 'secondary' (needs better names). Can we use quick pick categories (see screenshot) for this?

I feel this could be the next step after selecting "Show All Configurations."

I might not want all of the definitions to begin with, but when I do click "Show All Configurations," having quick pick categories to help navigate them more effectively seems quite beneficial too.

**Comment by Chuxel** [comment]
To some extent, if we've got the list sorted properly, and community definitions include (Community), we may not even need the categories near term (given its not yet available). 

I think the ideal is someone should be able to type "Node" in the input box, and get a sorted list of Node definitions even if we didn't detect Node since the repository is empty (or nearly empty).  If I play this forward to this list coming from a data source rather than pre-packaged definitions, I suspect that needs to almost work like like a search experience.

I suppose "show all definitions" could be more "find more definitions" or something like that to give a hint.

**Comment by Chuxel** [comment]
Also //cc @2percentsilk given she's talking w/GH on the marketplace topic.

**Comment by chrmarti** [comment]
Going with 'Show All' at the top for now. This also works well because we preselect the first entry and 'Select All' seems likely to be the most frequent choice:
![image](https://user-images.githubusercontent.com/9205389/128998895-bb7cf219-1f5b-4622-a5b4-903154bd16ad.png)

I also tried keeping the filter text, so when you have typed 'Azure' and then hit enter on 'Show All', 'Azure' would stay in the input box and the list would be filtered to that, but that doesn't work well when there is no match in the full list of definitions because then the list shows empty.
