### ISSUE TITLE
Misleading documentation on outbound connectivity requirements

### ISSUE THREAD

**Issue by rbagd** [microsoft/vscode-remote-release#547]
We are trying to setup VS Code Remote on a server behind a corporate firewall, in the spirit of #15. We have some limited leeway with firewall settings and as per [documentation](https://code.visualstudio.com/docs/remote/ssh), were allowed to open the firewall for the two URLs below.

> What are the connectivity requirements for the VS Code Server when it is running on a remote machine / VM?
> 
> The VS Code Server requires outbound HTTPS (port 443) connectivity to update.code.visualstudio.com and marketplace.visualstudio.com. All other communication between the server and the VS Code client is accomplished through an authenticated, secure, SSH tunnel.

The problem is that this doesn't really help. As an example, Remote SSH would try to [download this](https://update.code.visualstudio.com/commit:e83e24a0c9225becd7341e56952177a20d5d4629/server-linux-x64/insider) which is actually HTTP 302 redirected to an Azure instance on a different IP and then gets blocked by the firewall. Same thing for anything in the marketplace.

Any advise on minimal firewall settings needed to ensure VS Code outbound connectivity would be appreciated.

**Comment by Chuxel** [comment]
@rbagd Ahh this is likely due to the content distribution network. The 302 is to the Azure CDN at *.vo.msecnd.net.  

These should cover the remote server:
- update.code.visualstudio.com
- marketplace.visualstudio.com
- vscode.blob.core.windows.net
- *.gallerycdn.vsassets.io
- *.vo.msecnd.net

VS Code itself has [additional requirements](https://code.visualstudio.com/docs/setup/network#_common-hostnames) but most of these are for marketplace visuals, welcome pages, etc that will not be on the server.

Note that other extensions may require additional connections. For example, VS Live Share extension requires:
download.microsoft.com
*.liveshare.vsengsaas.visualstudio.com
*.servicebus.windows.net

We can tighten this up in docs.
