### ISSUE TITLE
Allow remote ssh extension to utilize wsl distro ssh client

### ISSUE THREAD

**Issue by oatovar** [microsoft/vscode-remote-release#5511]
I'm working on a project using okteto and we're planning to use vscode on wsl2. The okteto extension launches the ssh extension to connect to the created container. However, the ssh extension will only utilize the ssh client and config on the host and will ignore the ssh client and config within the wsl distro.  This causes the ssh connection to fail since okteto writes all of the ssh configuration to the wsl2 config file found in `~/.ssh/config`. Would it be possible to have the ssh extension use the wsl distro's ssh client instead?

**Comment by bamurtaugh** [comment]
Thanks for opening @oatovar. We can't speak to the Okteto extension since it's not Microsoft managed or supported. 

I believe this issue would cover the aspect for using the WSL version of SSH: https://github.com/microsoft/vscode-remote-release/issues/937. 

With these in mind, going to close out this issue, but please let us know if you have anything else specific to the Remote Development extensions in VS Code.
