### ISSUE TITLE
Dev container dockerfiles copy default remote settings to .vscode-remote

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#553]
https://github.com/microsoft/vscode-remote-try-rust/blob/95138e484a82809d256ebf1569f50fa9529009b8/.devcontainer/Dockerfile#L9

This is ok because the container extension still migrates .vscode-remote to .vscode-server, but in the future somehow the dockerfile will have to know whether settings should be copied to .vscode-server or .vscode-server-insiders

**Comment by Chuxel** [comment]
@roblourens Yeah I was planning to do a pass once the "settings" feature was available in Remote - Containers for a bit.  I think I can do that now.

**Comment by Chuxel** [comment]
Resolved with https://github.com/microsoft/vscode-remote-try-rust/commit/ca0ad479a08eb7c67a5273359e7e8405fe3a29ec

**Comment by chrmarti** [comment]
We will keep copying `.vscode-remote` for a while because we have copied these Dockerfiles to user's projects during preview. It is also partly a feature, because the Dockerfile does not need to populate multiple folders (and couldn't anticipate us introducing an additional flavor in the future). If we were to make this an official feature (which we maybe should) we could think about making `.vscode-remote` legacy and instead use `.vscode-server-template` or similar.
