### ISSUE TITLE
Podman support

### ISSUE THREAD

**Issue by drk-mtr** [microsoft/vscode-remote-release#5570]
This is a duplicate of https://github.com/microsoft/vscode-remote-release/issues/116, so apologies - however I don't understand the outcome at the end of the thread and can't ask there as it's locked.

Is this meant to work with Podman? If so are there any instructions for getting this working?

EDIT:
It appears this is already a supported feature. Steps for me were as follows, but I don't understand symlinks or linux, so they may be wrong. I suspect some of these steps were specifically applicable for me because I had a previous docker install that was removed, then installed podman.

1. Delete docker.sock:
`sudo rm -rf /var/run/docker.sock`

2. Create a symlink from podman.sock to docker.sock:
`sudo ln -s /run/podman/podman.sock /var/run/docker.sock `

3. Give the current user permissions for the `docker` group:
`sudo usermod -aG docker $USER`

**Comment by PavelSosin-320** [comment]
@derekbekoe Please, provide more context! How do you run Podman service? The Podman service responsible for Docker 1.40 REST API can run as root or completely in the userspace. The podman. soc is created in different places for the root and rootless user, i.e. regular Linux workstation session: $XDG_RUNTIME_DIR/ for rootless users and /run/podman for root by the default. Under the /run/ in any case, i.e. has very limited lifespan. Since Podman assumes SELinux enabled, group permission maybe not enough without some SELinux tricks like SELinux disable or label disable. Podman running in the userspace has to be very strickt in the sockets access.
