### ISSUE TITLE
Cannot clone GitHub repository in VS Code Remote SSH Terminal

### ISSUE THREAD

**Issue by AndreaPi** [microsoft/vscode-remote-release#5581]
Issue Type: <b>Bug</b>

test

Extension version: 0.65.7
VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.42GB free)|
|Process Argv|--crash-reporter-id df4f7917-f728-4290-9500-a3632318c3e7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dgx-01|
|OS|Linux x64 5.4.0-52-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz (80 x 2455)|
|Memory (System)|503.78GB (484.39GB free)|
|VM|0%|
</details>

**Comment by andreap-bh** [comment]
I thought I could edit the issue in GitHub, but it looks like I can't, so I'll comment here. I connect to a remote host using the Remote SSH extension, and from the VS Code Terminal I try to clone a private GitHub repository. The `git clone` command fails:

```
andrea@...:$ git clone https://github.com/....git
Cloning into ...
remote: Repository not found.
fatal: repository 'https://github.com/....git/' not found
```

However, if I connect to the same remote host using iTerm2, I can clone flawlessly:

```
andrea@...:$ git clone https://github.com/....git
Cloning into ...
Username for 'https://github.com': xxxxx
Password for 'https://xxxxx@github.com':
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 10 (delta 0), reused 10 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), 3.17 KiB | 1.59 MiB/s, done.
```

Since in the iTerm2 window I'm asked my git credentials, but not in the VS Code Remote Terminal, I suspect that VS Code is somehow storing my git credentials, and it's clearly storing the wrong ones. As a matter of fact, if I look at the environment variables which exist in the VS Code Remote Terminal window, but not in the iTerm2 window, I find:

```
VSCODE_GIT_ASKPASS_MAIN=/home/andrea/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/extensions/git/dist/askpass-main.js
VSCODE_GIT_IPC_HANDLE=/run/user/1001/vscode-git-0b59a3353d.sock
VSCODE_GIT_ASKPASS_MAIN=/home/andrea/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/extensions/git/dist/askpass-main.js
GIT_ASKPASS=/home/andrea/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/extensions/git/dist/askpass.sh
```

Somehow, the wrong git credentials must have stored by VS Code. How can I fix this?
