### ISSUE TITLE
Special Notes

### ISSUE THREAD

**Issue by Amber-Sarno** [microsoft/vscode-remote-release#5650]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Feature Request</b>

Hello. I'm new to this so this won't be a very technical question. I'm looking for a feature which would allow me to make Project Notes or even just Special Notes that stand out and remain at the top no matter how long my document becomes. 

To explain, I tend to think of things while I'm working, brilliant ideas or tutorials for features that I want to add. I can note them someplace else or comment the idea out, but unless I remember to come back to those comments or look at my notes, I'll never see them again, especially if it's a long page of code. I know I could, but the issue is that in reality, I won't!

The feature I'd like is something which allows me to add a tag with a bright color, something that could be referenced in the thumbnail overview on the right, something where all my Special Notes show up in one place no matter how long my code gets. Maybe even project centered? 

What I mean by project centered is, f.e., now I am working on a project which is using html, css and javascript at the same time, so I have all three files open in VS. I'd like that all three could be linked in some way in a project and then any Project Notes that I make to myself in the html files are visible even if I don't switch to that tab for three days.

Hope that was clear.
TIA!

Extension version: 0.58.2
VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by bamurtaugh** [comment]
Thanks for opening @Amber-Sarno.

A couple of thoughts:

- This repo is for specific features and bugs related to the VS Code [Remote Development extensions](https://code.visualstudio.com/docs/remote/remote-overview). I don't think this request sounds specific to remote development, but if I'm missing something and you're currently using dev containers, WSL, and/or SSH, please let me know.
- This sounds like it could be a great idea for an extension, or perhaps customizable through a theme. Have you explored the [extension marketplace](https://marketplace.visualstudio.com/vscode)? Or, have you considered [creating your own](https://code.visualstudio.com/api/get-started/your-first-extension)?
     - For instance, [CodeTour](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.codetour) or [GistPad](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.gistfs) sound relevant
- When filing issues in the future, if you notice the issue mentions "We have written the needed data into your clipboard because it was too large to send. Please paste," you may need to edit the issue and update with the clipboard info.

With this in mind, it doesn't sound like this issue is applicable to this repo, so I'm going to close out this issue. Please let me know if you have any questions or I might've missed any part of your request. Thanks!
