### ISSUE TITLE
Changes in documents are not registred in the Source Control tab

### ISSUE THREAD

**Issue by allinws** [microsoft/vscode-remote-release#5712]
VSCode Version: 1.55.2
Local OS Version: MacOS Cataline 10.15.7
Remote OS Version: Ubuntu 18.04.5 LTS
Remote Extension/Connection Type: SSH
Logs:
Steps to Reproduce:

Make a change to a file
See if it's updated in source control or not

Issue:
This recently popped up. Have to run "git status"  and "git add ."  in the terminal for the files to appear in the tab.

**Comment by lszomoru** [comment]
@allinws, are you able to reproduce the same issue with the latest version of VS Code?
Also, when you open the workspace, did you choose to trust the workspace? Thank you!

**Comment by LozanoMatheus** [comment]
@lszomoru I'm having the same problem, it happens when I try to `Open Folder in WSL...` and the git files/directories are under a folder which is a symbolic link.

```text
. ## vscode start here
└── Repos -> /mnt/<redacted>
    ├── .vscode
    ├── test001
    |   ├── Dockerfile
    |   ├── .git
    |   └── README.md
    └── test002
        ├── .git
        ├── Dockerfile
        └── README.md
```

I don't have this problem when the directory isn't a symbolic link.

An odd thing, I can't see the symbolic link when doing it via `Open Folder in WSL...`, but I can see when I do it via `New WSL Window` -> `Open Folder` (in the Explorer menu).

In my case, I map a directory from Windows to the WSL 2, create a symbolic link from `/mnt/...` to `~/`, and try to open the window `Open Folder in WSL...`.

This is what I get from vscode output console:

```text
Opening repository for path='/home/myuser/Repos/test001' failed; ex=Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any parent up to mount point /mnt)\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n"
}
> git rev-parse --git-dir
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/master refs/remotes/master
```

I don't get the error below if I do it via `New WSL Window` -> `Open Folder` (in the Explorer menu) -> symbolic link/repo directory (e.g. Repos/test001), but I still can't see the highlights on changed/created/deleted files.

**Comment by lszomoru** [comment]
@LozanoMatheus, apologies for not getting back to you on this until now. The list of changes in the "Source Control" viewlet are being refreshed based on file system events received by VS Code. There is a known issue with WSL where file system events for file changes on the Windows file system (ex: `/mnt/...`) are not being propagated correctly. This is one of the reasons why the general guidance when using WSL is to keep the files in the Linux file system.

**Comment by zachsiegel-capsida** [comment]
@lszomoru I do not store any of my code in the Windows file system (`/mnt/c/...`). I keep it all in `\\wsl$\Ubuntu\home\<user>\` (which, when using this extension, correctly displays as `~/...`). I still have this reloading issue.


I left a comment on [the extension page](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl&ssr=false#review-details) describing my issue.

**Comment by lszomoru** [comment]
@zachsiegel-capsida, got it. Could you please up the steps on [this wiki page](https://github.com/microsoft/vscode/wiki/Git-&-SCM-Issues#log-level-setting) to enable `trace` logging for the git extension. After that reload the window, and make a change to one or more files. Then please share the contents of [the git output window](https://code.visualstudio.com/docs/editor/versioncontrol#_git-output-window). Thanks!
