### ISSUE TITLE
Support for wildcards with `Include` in config files

### ISSUE THREAD

**Issue by frankli0324** [microsoft/vscode-remote-release#5758]
As is shown in ssh_config(5), `Include` configurations supports glob(7) wildcards. I've been using this feature to manage different types of shells I have. However this is not yet supported in ssh remote.

![image](https://user-images.githubusercontent.com/20221896/138569712-58c2807c-bfa0-4610-bfea-e57bc6df55c7.png)

Wish this plugin parses wildcards correctly.

**Comment by yogendra** [comment]
I ran into similar problem. Although I did not get the error about, but my (existing) files were ignored. As a result I could not see my hosts (in the subconfig file, example ~/.ssh/configs/private) in VSCode Connect dialog. 

But my problem was due to a "*" Host entry. Example:

```
Host *
  Compression yes
  ForwardAgent yes
```
I move the parametes outside the `Host *` and it worked. I am able to see my hosts defined in the subconfig.

Environment:

```bash
> uname -a
Darwin #########.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64 arm64 MacBookPro18,4 Darwin

> code --version
1.63.0
7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
arm64
```

Hope this helps others.

Tagging: #2446, #65

**Comment by tanhakabir** [comment]
@yogendra are you on the latest version of the extension? (0.68.0)

> I move the parametes outside the Host * and it worked. I am able to see my hosts defined in the subconfig.

What does you config look like when you do this?

**Comment by yogendra** [comment]
Extension Version: 
- Remote - SSH v0.68.0
- Remote - SSH: Editing Configuration Files v0.68.0
- Remote Development  v0.21.0


And the cofig file  info

Before:
```
Host *
  Compression yes
  ForwardAgent yes

Include configs/*
```

After:

```
Compression yes
ForwardAgent yes

Include configs/*

```

**Comment by tanhakabir** [comment]
@biyiklioglu and @yogendra https://github.com/microsoft/vscode-remote-release/issues/5933
