### ISSUE TITLE
Docs: .vscode-server vs .vscode-remote

### ISSUE THREAD

**Issue by max-sixty** [microsoft/vscode-remote-release#586]
This [page](https://code.visualstudio.com/docs/remote/containers-advanced) references `.vscode-remote`

![image](https://user-images.githubusercontent.com/5635139/59065785-8aa5fe00-887b-11e9-93c8-d9c6c59b20e8.png)

But the path on stable seems to be `.vscode-server`, and is referenced elsewhere: https://code.visualstudio.com/docs/remote/troubleshooting `Once you are connected, run rm -rf ~/.vscode-server/extensions to remove all extensions.`

Is that an old reference or am I missing something?

**Comment by Chuxel** [comment]
@max-sixty You are correct - that's a doc bug.  Wil lfix.

**Comment by max-sixty** [comment]
Thanks! Lightening fast response time...

**Comment by max-sixty** [comment]
Another: should [this](https://code.visualstudio.com/docs/remote/containers#_using-an-existing-container-image) be `.devcontainer.json` or `.devcontainer/devcontainer.json`? 

<img width="731" alt="image" src="https://user-images.githubusercontent.com/5635139/59066531-4ca9d980-887d-11e9-971d-724cf39287d1.png">

I can't get my workspace folder to not be `/` and maybe this is causing it...

**Comment by Chuxel** [comment]
@max-sixty Both locations are supported. What is in the json file?

**Comment by max-sixty** [comment]
Thanks @Chuxel . If you have any bright ideas; otherwise no need to use this as my support forum. 

`.devcontianer.json`:

```json
// See https://aka.ms/vscode-remote/devcontainer.json for format details.
{
	"dockerComposeFile": "docker-compose-vscode.yml",
	"service": "dev",
	"workspaceFolder": "/src",
	"extensions": []
}
```

But this suggests that it's looking at `\` as the root, and `Cmd+P` can't find any files...

![image](https://user-images.githubusercontent.com/5635139/59067838-9b0ca780-8880-11e9-8df7-47ea8341917b.png)

**Comment by Chuxel** [comment]
@max-sixty Yeah the location of the file would not cause that.  Check your volume mount in your docker-compose.yml to be sure you're not mounting ".." to src or something like that.  Also note that bind mounts do not work on remote docker hosts if you're trying to do that.  

Also, remember that if you use File > Open, VS Code will stay in that locaiton if you reload the window.  The workspaceFolder is just the default when you reopen folder in container.  It's possible you'd opened up `/`.  Search won't work from the root because there are too many files in the tree.

**Comment by max-sixty** [comment]
Ah - I just needed to do `File > Open > src` and it works! Thanks @Chuxel !
