### ISSUE TITLE
Remote SSH credential Storing

### ISSUE THREAD

**Issue by d4rk-lucif3r** [microsoft/vscode-remote-release#5880]
Hey
A question came into my mind. If we use remote ssh and login to a remote VM and install any extension which requires authentication, let's take an example of GitHub Copilot. We login with GitHub and provide token it gets authenticated and we are able to use it.
Now i logout and If any other user use remote ssh for same VM will he be able to use copilot or any other authenticated (By Previous User ofc) extension??

**Comment by tanhakabir** [comment]
Hey! Good question! From my understanding no a separate machine that is logged into the same remote won't have access to your authenticated status unless they are also authenticated in your account. 

I did a quick test on my end to verify this (1 machine authenticated and ssh'd into a remote, second machine not signed into any GitHub and authenticated into same remote) but let me know if you see otherwise!
