### ISSUE TITLE
Relative and absolute path of the same file open from SCM(Git)

### ISSUE THREAD

**Issue by mkilivan** [microsoft/vscode-remote-release#5895]
- VSCode Version: 1.62.1
- Local OS Version: Windows 10
- Remote OS Version: CentOs 7
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Click on 'Explorer' and open any file
2. Modify file and save
3. Click on the 'Open File' icon in the SCM changes list

After all steps are completed and if the issue has been replicated, there should be 2 tabs open:

Relative path to file (from steps 1 and 2)
Absolute path to file (from step 3)
The issue is that there is a relative and absolute path of the same file opened. I believe VS Code should regain focus on the relative path tab after step 3. Please note that this issue only occurs when using a remote SSH connection.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by tanhakabir** [comment]
Hey! Do you see this issue if you update VS Code to version 1.62.2?

**Comment by mkilivan** [comment]
> Hey! Do you see this issue if you update VS Code to version 1.62.2?

Hi, yes, the issue still occurs after I update VS Code to version 1.62.2.

**Comment by mkilivan** [comment]
Hi, I noticed that this issue happens if the opened folder is a symlink.

**Comment by lszomoru** [comment]
@mkilivan, apologies for not getting back to you on this until now. Your observation is correct, this error condition occurs when the repository has a symbolic link on its path. The issue is caused by the fact that VS Code respects the symbolic link, while `git.exe` "expands" it. Due to this behaviour there is a disconnect, hence the two editors are opened as the resources have different URIs. At the moment VS Code does not support repositories with symbolic links (https://github.com/microsoft/vscode/issues/5970). Please feel free to subscribe to the linked issue to be notified when the work is prioritised.
