### ISSUE TITLE
docker-compose examples do not complete

### ISSUE THREAD

**Issue by millerick** [microsoft/vscode-remote-release#593]
- VSCode Version: 1.35.0-insider (1.35.0-insider) 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
- Local OS Version: OS X 10.14 Mojave
- Name of Dev Container Definition with Issue: https://github.com/microsoft/vscode-dev-containers/tree/master/containers/javascript-node-lts-mongo

Steps to Reproduce:

1. Follow the instructions in the README on how to test the definition: https://github.com/microsoft/vscode-dev-containers/tree/master/containers/javascript-node-lts-mongo#testing-the-definition
2. Observe that step 4 hangs at `Run: docker-compose --project-name javascript-node-lts-mongo_devcontainer -f /src/vscode-dev-containers/containers/javascript-node-lts-mongo/.devcontainer/docker-compose.yml up -d --build`
![image](https://user-images.githubusercontent.com/26394493/59076118-36097f80-8889-11e9-8f76-476f9eab71fe.png)

Even after waiting for nearly half an hour, the command never completes, and the workspace never becomes visible inside of VS Code.  The examples that only use a `Dockerfile` and do not use `docker-compose` work fine.

**Comment by Chuxel** [comment]
@millerick Transferring to vscode-remote-release. This is unlikely a problem with the definition since I just cleaned out docker and retried with a similar config (macOS Mojave 10.14.5).

A few things:
1. VS Code Insiders is now on 1.36, so you might want to update insiders and the extensions and see if the problem persists. (The remote extensions now also work with 1.35 in stable.)
2. Have you bounced Docker itself?  It can sometimes have troubles.
3. What channel are you on for Docker desktop? (About Docker Desktop will tell you).  I'm unable to reproduce on Stable, but if you are on experimental, it's possible there's a docker bug.

**Comment by millerick** [comment]
Thanks, I wasn't sure which of the repositories was the better places for the issue.
1. I just updated to 1.36.  That did not resolve the issue.
2. I have restarted Docker several times.
3. I was using `17.12.0-ce-mac49` it was marked as stable.  I updated to `2.0.0.3 (31259)` and this resolved the issue.
