### ISSUE TITLE
Git credentials and SSH agent not forwarded when connected through SSH

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#5977]
I have been doing some initial testing and things are mostly working for me. Really nice job on this. I have one issue with git credentials. When running a devcontainer locally it will pick up the git credentials from the local OS if a credentials manager is configured (https://code.visualstudio.com/docs/remote/containers#_using-a-credential-helper). That does not appear to be happening when opening the container from a remote SSH connection. @chrmarti, Any guidance on this?

_Originally posted by @hansenms in https://github.com/microsoft/vscode-remote-release/issues/2994#issuecomment-983054619_

**Comment by chrmarti** [comment]
/fyi @felipecrs for the SSH agent forwarding.

**Comment by zweiter** [comment]
The same is happening for me when using Remote SSH into any Linux system. I need to set `SSH_AUTH_SOCK` as explained in the linked issue that has been closed last year.

**Comment by chrmarti** [comment]
@zweiter This is about the Remote-Containers extension. Could you open a new issue for the problem with Remote-SSH?

**Comment by felipecrs** [comment]
@chrmarti why was it closed?

**Comment by chrmarti** [comment]
It will use the SSH server's Git credential helper if there is one. I have a fix ready that will make it consult localhost's credential helper if the one on the SSH server fails.

Similarly for the ssh-agent, if the SSH server does not have SSH_AUTH_SOCK set, the fix will check for it on localhost.

**Comment by interpeix** [comment]
I'm in the same situation.
My laptop (Windows machine with Git installed and GCM) and GCM is not forwarded to Remote-SSH Host.

Scenario 1:
My Laptop => Remote-SSH to linux host, trying to clone a repo that have the credentials saved on the windows machine fails.
`$ git config --get credential.helper` empty reply

Scenario 2:
Manually upload the content of the repository to the SSH Host, because there is a .devcontainer that I want to run.
My Laptop => Remote-SSH to linux host => Reopen folder remote container works without issues.
`$ git config --get credential.helper` Returns 
`!f() { /root/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/node /tmp/vscode-remote-containers-673b0b90a3ad4447008f875661559991d7fdb747.js $*; }; f`

Is there any workaround to be able to forward de GCM to the Remote-SSH host?

**Comment by chrmarti** [comment]
Created https://github.com/microsoft/vscode-remote-release/issues/6168 for @interpeix 's request.
