### ISSUE TITLE
Fix use of "remote.containers.executeInWSL", "remote.SSH.configFile" and "remote.SSH.path"

### ISSUE THREAD

**Issue by ricardosantos9521** [microsoft/vscode-remote-release#6021]
Issue Type: <b>Bug</b>

Open a folder with remote ssh
Try to Reopen the folder in remote-containers
Not logs are shown

Extension version: 0.209.3
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux arm64 5.10.0-9-arm64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.80GB free)|
|Process Argv|--crash-reporter-id cd0756e5-34a8-4d1b-abf8-1475c043359c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: raspberrypi4|
|OS|Linux arm64 5.10.0-9-arm64|
|CPUs|unknown (4 x 1500)|
|Memory (System)|7.63GB (3.67GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932cf:30408637
vscop804cf:30404767
vs360cf:30404996
vsrem710:30405998
vscexrecpromp3t3:30407764

```

</details>

**Comment by chrmarti** [comment]
Have you checked the container log? (`F1` > `Remote-Containers: Show Container Log`)

**Comment by ricardosantos9521** [comment]
Yes @chrmarti i checked the logs
![image](https://user-images.githubusercontent.com/20097801/145692347-e9943a22-88db-4208-8098-ccb53bb60cf8.png)

**Comment by chrmarti** [comment]
As a workaround, you could add your ssh server to your local `~/.ssh/config` where you can also specify a user name. E.g.:
```
Host raspberrypi4
    User ricardo
```

**Comment by chrmarti** [comment]
Where do you specify the username `ricardo` for Remote-SSH?

**Comment by Clockwork-Muse** [comment]
Not working for me either, in a slightly different flavor;

I'm on windows 11, connected to a remote Ubuntu machine.  I'm ssh'd into the machine, and can open folders that way, and it picks up the `.devcontainer`, but for some reason it seems to want to run things on WSL:

```shell
[8582 ms] Remote-Containers 0.209.5 in VS Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e).
[8582 ms] Start: Run: wsl -l -v
[8611 ms] Start: Run: wsl -d Ubuntu -e ssh slipstream /bin/sh -c /bin/sh
[8613 ms] Start: Run in host: id -un
# process stuck here for some reason
```
... except the docker cli in Windows has a context pointing it to the remote machine (verified as both the cli and the docker extension properly reflect the remote machine).
WSL doesn't have docker installed, although it does have podman installed and aliased for docker.

**Comment by ricardosantos9521** [comment]
> Where do you specify the username `ricardo` for Remote-SSH?

In my case i have a setting in settings.json
![image](https://user-images.githubusercontent.com/20097801/145892687-d28b7cbc-3f7d-45d4-85fd-2a727a1a881e.png)

that file contains this
![image](https://user-images.githubusercontent.com/20097801/145892910-e1364e75-07e1-432f-a33a-a45196e193a7.png)

i parsed this file for https://github.com/Tyriar/vscode-windows-terminal when added support for ssh and other things
Here https://github.com/Tyriar/vscode-windows-terminal/blob/master/src/ssh.ts

**Comment by alkatar21** [comment]
I think my problem is quite related to this issue, maybe it is even the same.
It tries to use the default ssh-client on my computer, although I specified another one in the remote SSH extension. Since I did not have an SSH client installed on the computer, first the extension failed with an error in the runtime status `Uncaught Errors: write EPIPE`. Then I installed as a test the OpenSSH client in the Windows Optional features. Then I also get this problem, because the actually should not be used, it is not set up and thus can not connect.

Currently I used the following [workaround](https://github.com/microsoft/vscode-remote-release/issues/937#issuecomment-980509520) for Remote-SSH , to use a WSL ssh. However, I also did not use the default distro.

**Comment by chrmarti** [comment]
@alkatar21 There is a setting to let Remote-Containers run all commands in WSL, maybe that can help working around the issue:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/9205389/146144529-95962329-ed5c-44e8-9dc1-3cab01f2e73b.png">

**Comment by alkatar21** [comment]
Unfortunately this does not help, it leads to the same behavior as in # 6053.
The problem is that the setting uses the default WSL, which for me is a WSL1. For the setting to work you would have to be able to select a WSL, or at least it would have to use one that is specified in Docker Settings.
I tried to describe the issue in # 6061.
(I didn't reference the issues again, as they are already referenced right above here).

**Comment by ricardosantos9521** [comment]
Other problem i found. Remote-containers is using the "Host" value from "remote.ssh.configFile" as the ip to connect to the ssh machine.
![image](https://user-images.githubusercontent.com/20097801/146232156-625275b9-f0fe-484c-8e4b-81a9bd23bd23.png)
![image](https://user-images.githubusercontent.com/20097801/146232225-df6e12cc-0184-46f8-9458-8ee89f01bd7b.png)

**Comment by alkatar21** [comment]
@ricardosantos9521 This is an ssh feature, which is used there. You can use `ssh <host>` for a host that is stored in the config, normally `~/.ssh/config` (here the "remote.ssh.configFile" file) and ssh will resolve that to what is in the config. In this case `raspberrypi4-ricar` equals `ricar@192.168.1.140`.
It is also mentioned in the [docs](https://code.visualstudio.com/docs/remote/ssh#_remember-hosts-and-advanced-settings).

**Comment by ricardosantos9521** [comment]
Remote containers should use the configurations that are stored for Remote SSH. When we have vscode connect to a ssh machine and try to reopen a container in that machine. Otherwise we have to configure per SSH machine how remote containers should work.

**Comment by alkatar21** [comment]
I meant by my comment that the part of the command you mentioned is correct.
Otherwise that is exactly the problem. In this and I think all cases where SSH is used in the remote containers extension, depending on what `"remote.containers.executeInWSL"` is set to, either the SSH of the own machine, or the ssh of the default WSL is used.
But in fact the one configured via the remote SSH extension should be used.

**Comment by chrmarti** [comment]
To summarize: When you are connected with Remote-SSH we should ignore `"remote.containers.executeInWSL"` (because Remote-SSH does not use WSL to connect) and use `"remote.ssh.configFile"` and `"remote.SSH.path"` if set.

**Comment by chrmarti** [comment]
Now available with VS Code Insiders and Remote-Containers 0.210.0.
