### ISSUE TITLE
'Remote-Containers: Reopen in Container' resulted in an error

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#6045]
I just get a path not found error

```
Command 'Remote-Containers: Reopen in Container' resulted in an error (Shell server terminated (code: 1, signal: null)

Le chemin d'acc�s sp�cifi� est introuvable.
)
```

No logs in the dev console.
Dev container logs:
```
[185215 ms] Remote-Containers 0.209.3 in VS Code 1.63.0-insider (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e).
[185214 ms] Start: Run: ssh localhost /bin/sh -c /bin/sh
[185418 ms] Start: Run in host: id -un
[318013 ms] Start: Run: ssh localhost /bin/sh -c /bin/sh
[318211 ms] Start: Run in host: id -un
[331947 ms] Start: Run: ssh localhost /bin/sh -c /bin/sh
[331964 ms] Start: Run in host: id -un
```

_Originally posted by @rzhao271 in https://github.com/microsoft/vscode-remote-release/issues/5996#issuecomment-989104283_

**Comment by chrmarti** [comment]
What do you get when you enter these commands in a local terminal:
```sh
ssh localhost /bin/sh -c /bin/sh
id -un
```

Does `/bin/sh` terminate after running `id -un`?

**Comment by rzhao271** [comment]
The first line doesn't work, because I'm connecting to a Windows machine, so I'm guessing there's no `/bin/sh`. `ssh localhost` is fine. Also, I'm using the vscode-docs repository to repro this issue (https://github.com/microsoft/vscode-docs/blob/258a90bf0f3e08004d04fc187da968f2f70b2374/.devcontainer). Reopening the local repository in a container works fine, but local -> SSH (Windows) -> Container doesn't seem to be working.

**Comment by chrmarti** [comment]
Ack, Window SSH servers are not supported yet. Opening a separate issue for that.

**Comment by chrmarti** [comment]
Closing this one in favor of the shorter #6055. :)
