### ISSUE TITLE
Restart to Update needs to be run twice to actually update, when using Remote SSH

### ISSUE THREAD

**Issue by leifwalsh** [microsoft/vscode-remote-release#6058]
- VSCode Version: Latest Insiders, but I've observed this for months, across probably over 100 updates
- Local OS Version: Windows 10
- Remote OS Version: Debian 9
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. Have a VS Code instance running and connected to a Remote SSH session
2. Wait for an update to be available
3. Click "Restart to Update"

VS Code appears to update itself locally, but when it reconnects to the remote, it downloads a new copy of vscode-server, but then still shows that I need to Restart to Update. After waiting for the first upgrade, then clicking that, then waiting for the second upgrade, it stops prompting to update.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by joaomoreno** [comment]
This is a special case:

- Your local instance received an update and showed an update notification.
- While that notification was pending, there was a new update released. We can't just ignore the first update, since it's already partially applied, waiting for you to complete it.
- So, when you finally accept the update notification's prompt to restart, VS Code comes uip and sees the new update and the flow starts again.

We have no plans to improve this, since it really only happens to Insider users, in practice.
