### ISSUE TITLE
Windows WSL2 Ubuntu 20.04 devcontainer pops up Docker Compose Required window

### ISSUE THREAD

**Issue by jjpepper** [microsoft/vscode-remote-release#6111]
- VSCode Version: 1.63.2
- Local OS Version: 19042.1415
- Docker version: 20.10.11, build dea9396 (via docker --version from windows powershell, and in WSL2)
- Docker version 20.10.7, build 20.10.7-0ubuntu1~20.04.2 (from inside devcontainer when terminal accessed via docker desktop GUI)
- Remote OS Version: Ubuntu 20.04 WSL2
- Remote Extension/Connection Type: Unsure, but I think WSL2
- Logs:
```
[2390469 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd ; readlink /proc/$pid/ns/mnt ; cat /proc/$pid/stat | tr "
[2390903 ms] userEnvProbe is taking longer than 2 seconds. Process tree:
  9593: /bin/bash -lic '/home/jesse/.vscode-remote-containers/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/node' -p '"a44f34aa12351f1ac0dd88a4be41368d" + JSON.stringify(process.env) + "a44f34aa12351f1ac0dd88a4be41368d"'
    9608: ssh-add /home/jesse/.ssh/id_rsa
[2398462 ms] userEnvProbe is taking longer than 10 seconds. Avoid waiting for user input in your shell's startup scripts. Continuing.
[2398543 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[2398645 ms] 1.41
```
Then a dialog pops up saying "Docker Compose Required".  I'm pretty sure this is triggered by vscode running `docker-compose version --short` inside the devcontainer.

Steps to Reproduce:
1. install docker desktop for windows
2. run "Reopen in container" from vscode connection selector.

![image](https://user-images.githubusercontent.com/10545251/147645600-d323cbc5-8599-4b41-be9e-70752660e419.png)

Note that I have tried turning on the "Use Docker Compose V2" setting in Docker Desktop and this does not seem to have any effect.
The root cause seems to be that docker-compose is not available inside the container.  Note that this has been working for a year and has stopped either with an update to VSCode or to docker-desktop or both.

The root cause seems to be that `docker-compose` is not found inside the dev container:

From inside WSL2 Ubuntu 20.04
```
>  docker version --format {{.Server.APIVersion}}
1.41
> docker-compose version --short
1.29.2
```

From inside devcontainer docker cli (accessed via docker desktop gui):
```
# docker version --format {{.Server.APIVersion}}
1.41
# docker-compose version --short
/bin/sh: 4: docker-compose: not found
```

Does this issue occur when you try this locally?: -
Does this issue occur when you try this locally and all extensions are disabled?: -

**Comment by chrmarti** [comment]
Could you try commenting out `ssh-add` from your `~/.bashrc` in your WSL distro? It looks like that is waiting for user input when Remote-Containers tries to probe for the environment variables with a temporary bash session. This probably results in `PATH` being incomplete.

What has changed recently is that we run the probe for environment variables with an _interactive_ login shell instead of just a login shell. Overall that should improve the probe's results.

If commenting out `ssh-add` helps, try wrapping it in a check like the one suggested for executing the fish shell in https://github.com/microsoft/vscode-remote-release/issues/6032#issuecomment-992286952.
