### ISSUE TITLE
doc suggestion: add doc or example for how to get X software running in docker containers

### ISSUE THREAD

**Issue by ericblade** [microsoft/vscode-remote-release#616]
If you run Docker on Windows and use Linux containers, you can access make use of X apps by installing an X server on Windows, and doing "export DISPLAY=host.docker.internal:0" .  

I don't see any obvious ability to add this to like devcontainer.json or something, and the actual documentation for devcontainer.json seems to consist mostly of a very large page of examples, without any actual reference to what all you can do with it.  (i'd presume setting environment variables would be there somewhere, but I'm not seeing it)

**Comment by Chuxel** [comment]
@ericblade Interesting suggestion.  Part of the reason for the examples is we are using the [vscode-dev-containers](https://github.com/Microsoft/vscode-dev-containers) repository for more concrete and complete examples given the sheer volume of what you can do.  Anything you can do with `docker run` can be passed into the `runArgs` property in `devcontainer.json` and Docker Compose has similar flexibilities. 

Setting environment variables is then just...

`"runArgs": [ "-e", "DISPLAY=host.docker.internal:0"]`

...using the [CLI argument](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file). 

For example: 
```json
{
    "image": "x11docker/xfce",
    "runArgs": [
        "-e", "DISPLAY=host.docker.internal:0",
        "-e", "SHELL=/bin/bash"
    ]
}
```
...and pop up an internal terminal and type "thunar" to pull up the XFCE file explorer.

It requires a bit more setup with Xquartz on macOS since you have to disable "authenticate connections" and enable "allow connections from network clients", but VcSrv on Windows appears to be setup this way to begin with.

**Comment by ericblade** [comment]
````
{
	"dockerFile": "Dockerfile",
	"extensions": [
		"dbaeumer.vscode-eslint"
	],
	"appPort": [3000],
        "runArgs": [ "-e", "DISPLAY=host.docker.internal:0"]
}
````
should work then?  that'd be great.  then just to figure out how to add a few common GUI utilities to always install as well.  I suppose I could make a separate Dockerfile-dev configuration, but I'm trying to not have to maintain multiple build scripts.

That addition of "host.docker.internal" in relatively recent versions of Docker is a total blessing -- adding X forwarding support to a Linux container in Windows used to be a total mess, when I first started using Docker a couple of years ago.  Now it's a breeze.  Between that, and this new VScode functionality, it makes using Docker a lot more useful proposition.

I'm using it with MobaXterm, and it works great.  Glad I could be of help :)  And thank you for yours!

**Comment by Chuxel** [comment]
@ericblade Awesome!  Yes that should work.  To install additional utilities without modifying the base image, you could use the "postCreateCommand".  For example:

```json
"postCreateCommand": "apt-get update && apt-get install -y x11-apps"
```

Its run when the container is first created and intended for this kind of thing (or running a package manager to install dependencies).

**Comment by Chuxel** [comment]
Merging this with #550 which was raised first as a part of issue cleanup.
