### ISSUE TITLE
Back slashes are not saved in User field when adding a new connection

### ISSUE THREAD

**Issue by byamagata** [microsoft/vscode-remote-release#6172]
- VSCode Version: 1.63.2
- Local OS Version: 10.0.19042
- Remote OS Version: 10.0.2294
- Remote Extension/Connection Type: SSH/Docker/WSL
- Logs:

Steps to Reproduce:

1. Open Command Palette
2. Select `Remote SSH: Add New SSH Host`
3. When prompted to enter your ssh connection command, enter a username that contains a backslash.  (For instance, I added my username: nv\byamagata)
4. Save to any config
5. Open Config and backslash is missing from the User field of the newly created connection

![image](https://user-images.githubusercontent.com/26102991/149593218-14aecdd5-3535-4ae9-bc6d-b6ba9e1054c8.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by tanhakabir** [comment]
No sorry I haven't, I wanted to investigate SSH man first to verify what characters are and aren't permitted.

But afterwards it just requires a PR of a fix in one of our dependencies.

**Comment by eleanorjboyd** [comment]
Hello! Upon further evaluation we have determined that this will no longer be a plan item we implement. In order to keep our parsing from the `Add New SSH Host` command straightforward, these commands must follow bash parsing rules. Feel free to look into bash escape characters and use them to get a slash into your config file. Thanks!
