### ISSUE TITLE
Are there any plans to support disabling strictHostKeyChecking for remote-ssh?

### ISSUE THREAD

**Issue by jimmyjayp** [microsoft/vscode-remote-release#6209]
I have an ssh config which disables StrictHostKeyChecking for all hosts.  While VSC ssh remote seems to apply that to ip's, it does not apply it to hostnames.  Every time I open an ssh connection to user@host (instead of user@ip) it asks for a hosts file to use or indicates a host key mismatch, which for me is common to our cloud environment in which we replace hosts regularly. Thx

**Comment by bamurtaugh** [comment]
cc @roblourens for thoughts. Seems related to https://github.com/microsoft/vscode-remote-release/issues/2626, https://github.com/microsoft/vscode-remote-release/issues/976, but wanted to get your thoughts (i.e. would disabling `remote.SSH.useLocalServer` make a difference?).

**Comment by tanhakabir** [comment]
Unfortunately we can't support StrictHostKeyChecking because ssh turns off port forwarding for security reasons. And currently the Remote-SSH experience works only with port forwarding enabled. There's a longstanding feature request for an alternative: https://github.com/microsoft/vscode-remote-release/issues/92
