### ISSUE TITLE
Opening a terminal on a remote host should not require trusting files on that remote source

### ISSUE THREAD

**Issue by fulldecent** [microsoft/vscode-remote-release#6391]
Issue Type: <b>Bug</b>

1. Install Remote—SSH extension
2. Click CONNECT TO HOST on left sidebar
3. Select a host, assuming Debian
4. Connect
5. Open ~ folder on remote
6. Open a terminal (Command ~)

Expected outcome:

A terminal on the remote host is opened

Actual outcome:

A warning is shown that "Creating a terminal process requires executing code" and linking to a article which generall discusses workspace trust.

Discussion:

A major feature of containers is that they keep my workstation computer secure. I can run Debian on Azure (as in this example) and I should be sure that anything I do on that server (even if it's viruses and it's malicious, and people are out to get me) there can be no way it will infect my local workstation computer.

Ideally VS Code can work in no-trust mode and allow me to still access terminal on the remote server.

Or if there is some fundamental thing I don't understand here, it would be helpful if that error message were updated to clearly explain where I'm wrong.

Extension version: 0.74.0
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:56.651Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: Yes
Remote OS version: Linux x64 5.10.0-11-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|--crash-reporter-id 887f8733-a96a-44f8-b91e-d4df21ec6bd3|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 199.195.254.120|
|OS|Linux x64 5.10.0-11-amd64|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (1 x 3792)|
|Memory (System)|0.95GB (0.53GB free)|
|VM|0%|
</details>

**Comment by fulldecent** [comment]
<img width="1334" alt="Screen Shot 2022-02-25 at 11 37 03" src="https://user-images.githubusercontent.com/382183/155753793-9495ef5b-78f6-4a54-b818-229edf4ca2cf.png">

**Comment by sbatten** [comment]
cc @lszomoru for workspace trust and @chrmarti for containers and @Tyriar for terminal

@fulldecent am i correct in understanding that your remote a container that you use ssh to connect to?

**Comment by fulldecent** [comment]
@sbatten In this instance the remote is a Linux VPS that I SSH to. I have not tried doing this into a Docker container.

**Comment by jeffs** [comment]
This even seems weird on a local host.  Why does opening a terminal require trusting code from its working directory?  Happy to read the rationale behind this, if someone can point me in the right direction.

**Comment by Tyriar** [comment]
The reason we require workspace trust for the terminal is because a malicious repository could run code on shell startup which is exactly the type of attack vector workspace trust protects the user from. This is by design from my perspective.

**Comment by jeffs** [comment]
Thanks for replying @Tyriar .  A repository cannot run code merely by being the working directory of a terminal.  (How did you get that impression?)

Whether the shell in the terminal sources scripts in its working directory is up to that shell, not the terminal.  Most modern shells do not source files from their working directory by default, though they [do source][1] global and user-specific files.

This design, however well intentioned, means I can't even run the VS Code built-in terminal without granting broad trust to the entire directory.  I almost always _do_ want to allow a terminal to open, but _do not_ want to "trust" the directory.  Can you suggest any way to achieve that configuration?

[1]: https://medium.com/@rajsek/zsh-bash-startup-files-loading-order-bashrc-zshrc-etc-e30045652f2e

**Comment by Tyriar** [comment]
@jeffs it depends on your shell and how you have configured it but you can do some very sneaky things, some examples are if envdir is installed you can set critical environment variable which can trigger remote code execution, or using repo git config files to run code on git commands that are commonly part of shell prompts.

Could you open an "empty window" on the remote without a folder and use the terminal that way as a workaround? It's inconvenient but changing how this works back would be a security regression that I don't think we can or should do. The purpose of workspace trust is to protect users from exactly this sort of thing where a user could unwittingly do something that could make them vulnerable, it could have even protected you in these cases as you may not have been aware of the sneaky things above.

If I remember right there may be an issue tracking opening the `$HOME` folder in this case instead of blocking the terminal outright. I can't seem to find it after a cursory search though.

**Comment by jeffs** [comment]
@Tyriar If somebody installs an inherently unsafe shell extension, or blindly sources local files from their shell startup, then VS Code can't save them.  If we can't run the terminal in VS Code, then we have only two alternatives:

1. Trust the directory completely.  This is worse, and the user would have been safer had they simply been allowed to opn the terminal.
2. Run a separate terminal, outside of VS Code.  This is, at best, no more secure than running the terminal in VS code.  Additionally, it entails a third-party terminal emulator (with its own attendant security holes).  This is what I'm currently doing, but it's a vastly inferior experience to Vim/Tmux or most IDEs, buying (at best) no additional security.

This doesn't seem like something that should be controversial.  If folks can't run terminals without trusting the entire directory, then they'll end up granting far broader permissions for the directory than they should have to.  That's clearly a bad thing.  Or, they'll give up on VS Code, which is also not ideal.

Again, I'd love to see the original discussion and rationale, rather than Monday morning quarterbacking.  Links appreciated, if you happen to know how to find them.

**Comment by Tyriar** [comment]
> If somebody installs an inherently unsafe shell extension

@jeffs a huge amount of programmers show git status in their prompts and would have no idea this could be a problem, some would use git index commands which may be safe (I'm no expert) but others will use git status directly. Saying it's their fault if they get compromised isn't very fair. We're doing the very least where we say this could be dangerous if you don't trust the folder, that way at least it's the user's fault since they opted in.

> If folks can't run terminals without trusting the entire directory, then they'll end up granting far broader permissions for the directory than they should have to.

I understand your point, but going back to what I wrote above at least the blame is then on the user. Having workspace trust cover everything except for this one thing that we don't mention.

> Again, I'd love to see the original discussion and rationale

I think all discussions regarding design of workspace trust and the terminal decision are internal as they were security related. These decisions were not made quickly, we were discussing workspace trust for many months before it rolled out. The main outcomes relevant to this issue if I remember right were:

- Workspace trust will have 2 states to avoid complicating things as explaining the idea is already complicated enough
- It should protect users as best we can
- If the user does something that _could_ cause a compromise, show the dialog

@sbatten @lszomoru do you have thoughts on this?

**Comment by jeffs** [comment]
> I understand your point, but going back to what I wrote above at least the blame is then on the user.

A wise person once told me: "Saying it's their fault if they get compromised isn't very fair."  If somebody has an unsafe shell extension, then they already opted into that.  It has nothing to do with VS Code, and VS Code shouldn't be blocking every terminal just in case the user has an unsafely configured shell profile.

> The main outcomes relevant to this issue if I remember right were: ...

Thanks for the insight.  Totally agreed than Code has to draw the line somewhere.  Both the developer experience and the overall security would be greatly improved if opening a terminal were allowed on the other side of that line.

**Comment by fulldecent** [comment]
Overall, these sneaky things need to be documented in error messages and warnings inside VS Code.

Not buried inside a GitHub Issues discussion (which will be archived after some period of time) unlocalized, on some discussion about usability.

---

And then, separately (outside scope of this issue), these highly visible error messages and INFORMATIVE warnings should spawn new questions, like "well WHY can doing seemingly innocuous thing X result in somebody emptying out all my retirements funds?, can't somebody fit that?"

**Comment by Tyriar** [comment]
> If somebody has an unsafe shell extension, then they already opted into that. It has nothing to do with VS Code, and VS Code shouldn't be blocking every attempt to Create New Terminal just in case the user has an unsafely configured shell profile.

@jeffs we disagree on that. Eventually I would want to allow opening terminals in `$HOME` and writing a warning to the terminal explaining why. Adding additional features to restricted mode isn't a particular priority though. In the meantime there are workarounds: open an empty workspace and use the terminal, open another trusted folder and open the terminal.

> Overall, these sneaky things need to be documented in error messages and warnings inside VS Code.

@fulldecent workspace trust and its purpose is documented on https://code.visualstudio.com/docs/editor/workspace-trust, we need to draw the line somewhere at @jeffs says. Is it our duty to document every single possible thing that could happen? We don't go to that extreme, instead we use a blanket recommendation of essentially: don't click this if you don't trust the origin or bad things could happen.

> "well WHY can doing seemingly innocuous thing X result in somebody emptying out all my retirements funds?, can't somebody fit that?"

Right, you're welcome to work on that if you're passionate but these problems are out of the scope of VS Code. Our responsibility ends at protecting users until they explicitly enter trusted mode.

**Comment by fulldecent** [comment]
Thank you, I really appreciate all the discussion on these. VS Code is important to me.

Let's agree on some basic points:

1. Many people use VS Code to open random repos on GitHub (supported, safe mode)
2. Many people "trust" their own code when they have not audited upstream dependencies (unsafe)
3. Developing software properly requires running test cases (unsafe if local)
4. Microsoft/GitHub sells Codespaces and Microsoft/VS Code supports Podman/Docker
5. VMs like Codespaces and containers like Podman can isolate security risks
6. Most people are not using VMs/containers yet

If we agree on that, then most VS Code customers are sitting ducks to be [compromised and added to botnets](https://arstechnica.com/information-technology/2022/03/sabotage-code-added-to-popular-npm-package-wiped-files-in-russia-and-belarus/).

**It would be nice if using the paid GitHub Codespaces services gave people improved experiences, like, doing things everybody does becomes safe instead of dangerous.** And that means **opening a terminal on a remote host should be safe**.

---

The current situation with VS Code feels like Internet Explorer in the 90s. You browsed any website (HTTP) and got a nag error that this is dangerous. To do anything you need to click "turn off warnings". You are responsible now for your own actions. You visit your bank website on HTTP, enter your password and login (fail!).

Compare that to modern browsers. You visit an HTTP website. If possible the browser upgrades your security to HTTPS automatically. Browsing HTTP is fine but you get a red bar. When you try to enter your password on a form it warns "this specific thing you are doing is a bad idea" and people find it informative and helpful.

Applying that here. Basically we are now in the 1990s web browsing of software development. Everything most people is wrong and exposing huge risks. People think pasting `curl XYZ | bash` is a good way to install software on production machines. We can promote safe practices by encouraging people to run processes in VMs/containers and show that is safe/isolated; encourage extensions to work without running user-defined code and show those as safe; and inform customers along the way.

**Comment by Tyriar** [comment]
> It would be nice if using the paid GitHub Codespaces services gave people improved experiences, like, doing things everybody does becomes safe instead of dangerous.
> ...
> We can promote safe practices by encouraging people to run processes in VMs/containers and show that is safe/isolated

Feels like we already do this as we encourage the use of the [remote - containers extension](https://code.visualstudio.com/docs/remote/containers) and Codespaces which uses containers. Containers are great for isolation as well as ease of setup.

> And that means opening a terminal on a remote host should be safe.

The philosophy I've been applying to the integrated terminal since it's inception was to have the user's shell work just like an external terminal, which included not touching your shell or prompt. If we overwrote the shell many people wouldn't use it as it would be unfamiliar. This is a design decision that was made long before we thought about the idea of workspace trust and I stand by it.

Making opening a terminal as the user configured it to be safe is simply impossible without building a shell that has security built-in and forcing them to use it. I have certainly thought about building a shell since I've been involved with terminals for years, but that would be a different project and a lot of effort, all of which might end up being for nothing if people don't end up using since it's not as "hackable" as alternatives.

**Comment by fulldecent** [comment]
Maybe we are talking past each other in terms of what is "safe" and what is "not safe".

If I use remote-controlled robotic arms to perform surgery on my stuffed animal bear, the bear can be destroyed, not me.

If I send my source code (one way) to a virtual machine, container or contaminated remote host for testing, that VM/container/test host could be destroyed, not my local machine.

If I login with SSH/SFTP to edit and run files on a remote VM/container/testing host, I may destroy anything on that remote, but there should be no way to mess up anything locally.

I consider all these scenarios approximately as "safe" or more precisely "safe for your local machine, but you may mess up your VM/container/testing host". This is exactly the same threat scenario as logging in with SSH.

**Comment by Tyriar** [comment]
@fulldecent messing up your remote machine is definitely not safe in my eyes, with enough creativity I believe a targeted attack via an untrusted repository could manage to mess up your local machine. We can strive to make that as hard as possible to do but workspace trust is another layer of protection which if it's working right should make it not possible to mess up your local machine.

**Comment by jeremyn** [comment]
I've had some related discussions about Remote-* extension security in issues https://github.com/microsoft/vscode-remote-release/issues/6566, https://github.com/microsoft/vscode-remote-release/issues/6608, and https://github.com/microsoft/vscode-remote-release/issues/6667. The basic situation is that the various Remote-* extensions will look for git/GPG/SSH information (GPG agent and public key database, SSH agent etc) on your local machine, or your local and Remote-SSH machines using certain rules if you're using a container on an SSH server, to import into the container as a convenience for the user. In my opinion this is a serious security problem since this information can be very sensitive yet these extensions are deliberately but quietly injecting them into what the user likely considers a sandboxed environment. I specifically referred to the recent `node-ipc`/`peacenotwar` malware as something a user would want to protect themselves from.

According to https://github.com/microsoft/vscode-remote-release/issues/6608#issuecomment-1112960548 from member @alexdima:

> For VS Code remote, the VS Code server is in the same trust boundary as the VS Code client. That means that you should only connect to VS Code servers that you trust. So you should only connect to SSH machines that you trust and only create dev containers from definitions that you trust (i.e. you should not use dev containers as a sandbox).

I understand him to be saying, in other words, that Microsoft by design considers the VS Code GUI and any remote server or container accessed by the GUI to be in the same security boundary regardless of any workspace trust settings. This seems to contradict what @Tyriar wrote in https://github.com/microsoft/vscode-remote-release/issues/6391#issuecomment-1117644807:

> Feels like we already do this as we encourage the use of the remote - containers extension and Codespaces which uses containers. Containers are great for isolation as well as ease of setup.

so I would be interested in hearing how these two statements can be reconciled.

Regarding extensions generally, from what I can tell in the documentation they have basically total access to do anything the user can do either locally or remotely, and "workspace trust" is mostly a set of opt-in guardrails a conscientious extension author can choose to follow. It's not like SELinux where VS Code default-denies every request for resources an extension makes. There's an item on the [VS Code 2021-2022 roadmap](https://github.com/microsoft/vscode/wiki/Roadmap#security) of "Explore sandboxing of extensions in both local and remote scenarios". It's the last item on the "Security" list. I wouldn't get my hopes up.

I agree with @fulldecent in https://github.com/microsoft/vscode-remote-release/issues/6391#issuecomment-1117844571:

> Maybe we are talking past each other in terms of what is "safe" and what is "not safe".

in the sense that terms like "sandbox" and "trust" are quite vague. In my comment at https://github.com/microsoft/vscode-remote-release/issues/6608#issuecomment-1115276381 I point out that `node-ipc` is installed as a `vue-cli` dependency which is available in both a Vue devcontainer available in VS Code and in a Vue/VS Code tutorial. A user has every reason to "trust" instructions provided by Microsoft yet doing so could have resulted in malware being installed remotely which is, as I wrote above, effectively the same as being installed locally. So asking the user whether they "trust" some remote environment is questionable at best.

My main takeaway from these various issues is that the only way to run VS Code securely is to sandbox the VS Code GUI itself, in a graphical Linux VM or something. Then you can go ahead and trust everything since it's basically theater anyway. Thinking of it as a 1990s web browser like @fulldecent wrote is a pretty good mental model. It's unfortunate that it's only the handful of people reading these GitHub issues who will see this.

**Comment by Tyriar** [comment]
> so I would be interested in hearing how these two statements can be reconciled

@jeremyn Not totally sure what you mean, Microsoft/our team encourages the use of containers which enhance security and ease of setup. Connecting to a remote host you don't trust is a bad idea I agree as they control the vscode server running on it.

> Regarding extensions generally

Workspace trust is different from extension trust; you trust an extension when you install it, you trust a workspace by saying you trust the workspace. Looks like you're already discussing that in https://github.com/microsoft/vscode-remote-release/issues/6608, it's definitely out of scope of this issue.

> "workspace trust" is mostly a set of opt-in guardrails a conscientious extension author can choose to follow

Correct, it unifies the experience and makes it easy for extensions to do the right thing, instead of having 10 notifications from 10 extensions. It also helps makes the extension authors aware of the problem.

> My main takeaway from these various issues is that the only way to run VS Code securely is to sandbox the VS Code GUI itself

My understanding is it's safe provided:

- You install extensions from trusted authors (that don't ship malware and support workspace trust properly)
- Don't trust restricted folders
- And as above don't connect to untrusted remote hosts

But again, this is out of scope of this discussion and not really my area. Looks like https://github.com/microsoft/vscode-remote-release/issues/6608 is the right place for that.

---

I feel like this issue is getting a bit derailed, as for the actual request of allowing a terminal in a trusted workspace I'm going to close this as designed for the reason I outlined above that it's possible to 

> Making opening a terminal as the user configured it to be safe is simply impossible without building a shell that has security built-in and forcing them to use it.

With safe here meaning that a malicious repository could exploit _common_ shell extensions by simply opening a shell within it. We may at some point allow terminals to be opened on restricted workspaces but it's not planned currently.

**Comment by jeremyn** [comment]
@Tyriar The contradiction between what you wrote and what @alexdima wrote seems so obvious to me that I don't know how to make it more clear. I've asked him to clarify at https://github.com/microsoft/vscode-remote-release/issues/6608#issuecomment-1119150020 but maybe you want to go over there and answer too, since it doesn't seem fair to ask him to explain what you wrote.

Workspace trust and extension trust go together, right? Extensions are powerful and can do a lot so the more extensions you have the less likely you will trust a workspace because that would give bad (malicious/badly written/out of date) extensions more chances to do damage.

And, I assume extensions can do something even with just a bare terminal on a remote server (right?), so workspace trust is relevant to restricting those extensions, totally apart from malware triggered entirely in the shell by `__git_ps1` in the prompt or something. So even a security-focused shell would still require workspace trust to restrict extensions. Please correct me if I'm wrong here, and I do think this part is in scope.

I disagree with your bullet list of "it's safe provided..." but respect that it's out of scope for this issue.

**Comment by Tyriar** [comment]
> I assume extensions can do something even with just a bare terminal on a remote serve

@jeremyn the terminal is completely disabled in restricted workspaces, even to extensions. However, an extension could launch a pty not using the integrated terminal if they really wanted, just like they can launch processes. 

> so the more extensions you have the less likely you will trust a workspace

Not workspace, the more extensions you have the less likely your computer is secure?Just like the more programs you have installed the less likely your computer is secure as that's essentially what they are. 

> So even a security-focused shell would still require workspace trust to restrict extensions

Currently workspace trust doesn't restrict extensions, extensions restrict themselves with the help of workspace trust. I found it useful to think about workspace trust as a consolidation of the UX associated with trusting a folder. Before workspace trust existed there were different flows/wording/ui for various components in vscode core and extensions had their own thing as well. Workspace trust solves that by having a single switch and more surfacing of the problem at hand. 

I think you're describing where I would love us to get to eventually. You can't really sandbox a node process though, so we would have to expose a bunch more api like the ability to launch a process via vscode's extension api and then have a permissions model similar to Android. This would of course break backwards compatibility for the majority of extensions. You should stay tuned on the web worker extension host idea which seems quite promising to me. I probably won't be involved in that work though fwiw.

**Comment by jeremyn** [comment]
@Tyriar

> an extension could launch a pty not using the integrated terminal if they really wanted, just like they can launch processes

I hadn't considered that, but yes that makes sense.

> Not workspace, the more extensions you have the less likely your computer is secure?Just like the more programs you have installed the less likely your computer is secure as that's essentially what they are.

Security here involves not only the number of extensions (or programs) installed but the variety of things those extensions are exposed to. A malicious web browser extension might be harmless until you log into your bank's website. For VS Code extensions/workspace etc a threat scenario is that a malicious for example node/npm dependency author identifies a vulnerability in a popular VS Code extension. They write their dependency so that when the vulnerable extension accesses a workspace where the malicious dependency has run code, the extension is "hacked" to do something bad.

> Currently workspace trust doesn't restrict extensions, extensions restrict themselves with the help of workspace trust.

Yes, I should have said something like: workspace trust would still be a relevant consideration even with a security-focused shell. This essentially means that @fulldecent's original request to avoid a workspace trust prompt when opening a bare terminal is impossible or at least not a good idea until/unless extension architecture is reworked as you describe later.

> I think you're describing where I would love us to get to eventually.

Actually yeah it sounds like it, see my comment https://github.com/microsoft/vscode-remote-release/issues/6608#issuecomment-1099298878 where I wrote "The "[Extensions](https://code.visualstudio.com/docs/editor/workspace-trust#_extensions)" section of the workspace trust documentation you linked suggests that the extension author needs to decide if their extension is exploitable instead of, say, VS Code requiring dangerous actions to go through certain key paths and then locking those paths down." I sympathize with your worry that these restrictions will break extensions: it sounds similar to the switch in Firefox 57 in 2017 from the more powerful XUL extensions to the less powerful but safer WebExtensions model. People were upset about that for a long time, and I suppose some still are.

**Comment by Tyriar** [comment]
> They write their dependency so that when the vulnerable extension accesses a workspace where the malicious dependency has run code, the extension is "hacked" to do something bad.

Right, currently it's the extension author's responsibility to consider their dependencies and not ship malware. And your responsibility as a user to install extensions from authors you think will not ship malware and control their dependency count/quality.
