### ISSUE TITLE
Use Remote SSH while keeping the code on local machine

### ISSUE THREAD

**Issue by ahmednrana** [microsoft/vscode-remote-release#662]
Please add a way to use Remote SSH extension while keeping the source code on my local machine.

**_Use Case:_**
1. I want to use it as the remote debugger for Java as remote debugger for Java is very slow for my project. I can debug the Java code using Remote SSH but for this I have to copy the code on remote machine each time(and keep it updated)
2. The remote machine is powerful and I want to keep my code on my machine while running it on remote.

**Comment by underchemist** [comment]
is your code not version controlled? can you not have a the repository cloned on your remote server and edit there directly with the extension?

A typical use case before Remote SSH: 
- edit, commit code locally
- pull changes on remote server
- run code remotely 
- repeat

With Remote SSH:
- Connect to remote server through vs code
- edit/commit directly
- run code remotely

There are no in between steps to keep local files in sync

**Comment by roblourens** [comment]
I think it's out of scope for vscode to deploy your project to a different machine. If the remote machine is very powerful then you should consider keeping your code there for development and backing it up with source control.

**Comment by Chuxel** [comment]
@ahmednrana @underchemist @roblourens We've [documented how `rsync` can be used](https://code.visualstudio.com/docs/remote/troubleshooting#_using-rsync-to-maintain-a-local-copy-of-your-source-code) for this purpose. However, as Rob says, the model here is that your code is primarily on the remote and your local code is a copy for situations where you have to use local tools like Git Kraken or something like that.  You can also use [SSHFS to mount hte remote filesystem](https://code.visualstudio.com/docs/remote/troubleshooting#_using-sshfs-to-access-files-on-your-remote-host).

I might move this to the core SSH article rather than tips and tricks since it seems to come up regularly.
