### ISSUE TITLE
Key bindings not carried over from local extensions

### ISSUE THREAD

**Issue by Keno** [microsoft/vscode-remote-release#698]
I use the "Sublime Text Keymap" extension to provide me with some common keybindings that I use quite regularly (e.g. Cmd-Shift-L to insert multiple cursors at the end of the line). I had installed this package locally, but then mostly forgot about it. However, when connecting to the remote, these key bindings did not carry over, so from my perspective the editor just behaved differently in response to some common key bindings. I ended up figuring out that the extension was missing remotely, but I would have expected UI settings (like keybindings) to carry over from locally installed packages.

**Comment by egamma** [comment]
The sublime keybinding extension is currently treated as a workspace extension since it has a `main` for the settings importer code. The extension must be defined as a UI extension, otherwise the settings importer will not work. Filed https://github.com/microsoft/vscode-sublime-keybindings/issues/113.

The work around is to define the extension as a UI extension in the settings:
```json
"remote.extensionKind": {
    "ms-vscode.sublime-keybindings": "ui"
}
```

For now defined the extension as a UI extension in the VS Code product.

//fyi @Chuxel
