### ISSUE TITLE
Remote container slow.

### ISSUE THREAD

**Issue by ArmandArthur** [microsoft/vscode-remote-release#7063]
Hello,

I had installed ubuntu on Windows 10. 
Vscode, docker desktop, extension remote-container.

My files (about project) are saved in Windows repository.
I have openned the folder with the build extension remote.

And the application turns, but it's slow. I had changed my memory computer for more but it's don't change the speed about execution about my app.

I read i can put my files into the container, but i don't know how do it. (if i rebuild, i lost my copy files?)

Do i miss something?

**Comment by ArmandArthur** [comment]
I tried to clone repository git directly in remote.

**Comment by ArmandArthur** [comment]
I set up the mode "StartType" in Manual, but repo don't want clone. 

Do i need to put the ssh-key inside the container?

**Comment by Chuxel** [comment]
https://code.visualstudio.com/remote/advancedcontainers/improve-performance has some information in it on how to improve disk performance if this is your issue. By far the biggest recommendation on Windows is to use WSL2 and store your source tree there rather than windows (so, not under `/mnt/...`).  There's also a clone repository in container volume command and manual steps described in this doc.

**Comment by ArmandArthur** [comment]
Exactly that i did,  (before your recommandation), it's works perfectly but i needed to apache php/mysql on ubuntu native. ok.

**Comment by ArmandArthur** [comment]
I removed docker and remote-container.

**Comment by Chuxel** [comment]
https://github.com/microsoft/vscode-dev-containers/tree/main/containers/php-mariadb might give you what you need there.    But it may be no longer apply if you've switched to using WSL directly.

**Comment by Chuxel** [comment]
Closing issue since it sounds like you've moved on.
