### ISSUE TITLE
Code-server terminal lag

### ISSUE THREAD

**Issue by xqdoo00o** [microsoft/vscode-remote-release#7085]
I'm using the code-server 1.70.2 in wsl.

Sometimes the terminal lag after I type in command, I tried to debug in chrome, and find that if command no lag, the websocket shows upload binary message immediately. If command lag, after a few ms(up to 1s) the websocket shows the messages , and the terminal shows which I typed in at the same time.

![image](https://user-images.githubusercontent.com/12299238/185368567-2e2f86a2-dae1-4daf-be28-78dec8ce9ca8.png)

I use code-server in local wsl, so the network factor could be excluded.
Would it help if put websocket code in webworker (Found [this old bug](https://bugs.chromium.org/p/chromium/issues/detail?id=456476))? or other code causeing this random terminal & websocket lag?

**Comment by connor4312** [comment]
I think to debug this we should make some "latency measurement" commands that would print diagnostic info that users could share...

**Comment by MiguelRodo** [comment]
I can second the above problem, in that when using code server (albeit not in local mode), there is little lag when editing files but significant lag when editing commands in the terminal (e.g. a word or two could be written before either appears).

**Comment by SuhasHebbar** [comment]
The now removed `code-server serve-local` works way better in this scenario for running code-server locally in WSL or a container.

I am guessing the latency is unavoidable since code tunnel is not P2P and directs all traffic through microsoft's tunnel servers despite running the server locally. VSCode's terminal tries to handle the lag by optimistically displaying keypresses before the server response but it doesn't help much and doesn't work very well with vim keybindings.
