### ISSUE TITLE
${containerEnv:TEST_VAR} does not work with mounts

### ISSUE THREAD

**Issue by tvenhaus** [microsoft/vscode-remote-release#7147]
Environment:

- VSCode Version: 1.71.0-insider (user setup)
- Local OS Version: Windows 11
- Remote OS Version: Ubuntu (though any will work)
- Remote Extension/Connection Type: Containers

Steps to Reproduce:

1. Create a new folder and open in VS Code
2. Add Dev Container configuration files (choosing Ubuntu)
3. Create /.devcontainer/devcontainer.env file:
```
TEST_VAR=/mnt/c/LocalFolder
```
4. Add the following to the devcontainer.json file:
```
"runArgs": ["--env-file",".devcontainer/devcontainer.env"],
"mounts": [
	"source=${containerEnv:TEST_VAR},target=/remotefolder,type=bind,consistency=cached"
]
```
5. Rebuild and Open in Container
6. Observe Error
`docker: Error response from daemon: invalid mount config for type "bind": invalid mount path: '${containerEnv:TEST_VAR}' mount path must be absolute.`

May be related to [this issue](https://github.com/microsoft/vscode-remote-release/issues/7121).

**Comment by chrmarti** [comment]
The mount points are applied when the container is created, but container variables (containerEnv) are only replaced after the container is created. This is because only after the container was created can we inspect the container for its environment variables.

Hope that makes sense. Closing as expected. Thanks.
