### ISSUE TITLE
Install "code-insiders" command in path fails when using TMUX

### ISSUE THREAD

**Issue by ataiya** [microsoft/vscode-remote-release#717]
- VSCode Version: 1.34.0-insider 
- Local OS Version: MacOS 10.14.5
- Remote OS Version: Debian GNU/Linux 9.9 (stretch)
- Remote Extension/Connection Type: SSH

Steps to Reproduce (this works):
1. connect to SSH remote
2. `Shell Command: "install 'code-insiders' command in PATH"`
2. open integrated terminal
4. code-insiders filename.txt 

Steps to Reproduce (**this is the bug**):
1. connect to SSH remote
2. open integrated terminal
3. start a tmux session via `tmux new -A -s main`
4. `Shell Command: "install 'code-insiders' command in PATH"`
5. code-insiders filename.txt results in `code-insiders: command not found`

The reason is that when TMUX is used, the PATH variable is not updated properly.
How can this be resolved?

**Comment by Tyriar** [comment]
Not sure why tmux isn't getting the environment if there's a new session, but I think it's related to either tmux or the install to PATH command.

**Comment by joaomoreno** [comment]
This command has nothing to do with remote. It installs `code-insiders` on the same machine where VS Code is running. It also doesn't mess with the `PATH` variable at all, but rather just creates a symlink in `/usr/local/bin`. Make sure that is in your PATH both in and out of tmux.

**Comment by ataiya** [comment]
A couple of notes; 
Regarding point (2) above, when you connect to a remote machine the path is updated as follows:
```
~: echo $PATH
/home/atagliasacchi/Envs/python3/bin:/home/atagliasacchi/.vscode-remote/bin/693a13cd32c5be798051edc0cb43e1e39fc456d9/bin:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/atagliasacchi/bin
```

Hoever if I start TMUX, and the PATH is:
```
~: echo $PATH
/home/atagliasacchi/Envs/python3/bin:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/atagliasacchi/bin
```

So the issue seems to be: when you do a vscode-remote the PATH variable seems to be updated, but I assume the update is done upon connection, and not stored in a persistent location the remote (such as adding a path update to .bashrc). I still think the **use-case is a bit broken**, as it prevents the use of "vscode remote_file_to_edit.txt" -- not sure this bug should be closed.

The question simply becomes, will his path be persistent? If not, it makes no sense to add it to my .bashrc (which is sourced by tmux/screen upon starting a session)
```
/home/atagliasacchi/.vscode-remote/bin/693a13cd32c5be798051edc0cb43e1e39fc456d9/bin
```

**Comment by joaomoreno** [comment]
Adding @alexandrudima to answer this.

**Comment by alexandrudima** [comment]
Ok, this hurts my brain a little bit and I really don't understand it 100%. But let me write down what I do know:

The command `Shell Command: "install 'code-insiders' command in PATH"` executes on the UI machine. It does not execute on the remote machine and does not do anything to the remote machine at all. Here is [the proof](https://github.com/mflan48/vscode/blob/988a5090d3c9caaeba8726347388757fadddad5c/src/vs/workbench/contrib/cli/node/cli.contribution.ts#L41) -- the command lives on the renderer side and is imported via `workbench.main.ts`... So we can simplify your steps above by removing step 2 which does nothing on the remote machine. 

So the steps become:

**This works**:
1. connect to SSH remote
2. open integrated terminal
3. `code-insiders filename.txt`

**This does not work**:
1. connect to SSH remote
2. open integrated terminal
3. start a tmux session via `tmux new -A -s main`
4. `code-insiders filename.txt` results in code-insiders: command not found

The first thing works because it is a feature that @aeschli implemented. We control the environmental variables for every shell spawned by the integrated terminal. We therefore sneak in something in the `$PATH` variable, specifically, the `bin` folder of the server side installation, which I think you have found above. When executing `code-insiders`, it uses yet another environmental variable (I don't know its name by heart) which helps `code-insiders` to connect back to a socket path and communicate via that socket to the extension host running on the remote machine, which will then forward that communication to the UI machine, which will finally open a new file or do something on the UI machine...

IMHO it is impossible for this to work under `tmux`, because `tmux` is if I understand it correctly a shell which survives for a long time, even after VS Code has disconnected from the machine. So it is not possible from this long-living shell to reach back to any vscode sockets, as there might be no vscode sockets at all... I also have the impression that `tmux` does not inherit the `$PATH` variable and instead reads it fresh from `.bashrc` or something... and that is what you print above.

In any case, this is nothing that I have worked on, and any knowledge of this is just incidental. The feature with `code-insiders` working in the integrated terminal when being connected to a remote machine was implemented by @aeschli and I hope my speculation is correct. 

In any case, I will forward the issue to @aeschli , but I think the resolution should be "can't fix", i.e. cannot support `code-insiders` inside `tmux`...

**Comment by aeschli** [comment]
Thanks @alexandrudima for the great write-up.

Yes, `code-insiders` can only work when run in the environment of an integrated terminal. Besides having `/home/$USER/.vscode-server/bin/$COMMIT/bin` on the path, it needs the env variable `VSCODE_IPC_HOOK_CLI`.

Note that $COMMIT is based on the VSCode version, so will constantly change. So don't put that path in your `.bashrc`

I'm not a TMUX user, but reading https://superuser.com/questions/1423554/how-does-tmux-spawn-multiple-sessions I believe you can tell tmux which variables need to be copied. Maybe give it a try ( no guarantees given)
