### ISSUE TITLE
command 'remote-internal.setActiveFolders' not found

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vscode-remote-release#7178]
```javascript
Error: command 'remote-internal.setActiveFolders' not found
at v._tryExecuteCommand in src/vs/workbench/services/commands/common/commandService.ts:91:26
at v.executeCommand in src/vs/workbench/services/commands/common/commandService.ts:85:15
at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=784b0177c56c607789f9638da7b6bf3230d47a8c&bH=ceb83257-0b5b-57d9-4389-dc5f1f0e3fe4)

**Comment by roblourens** [comment]
@eleanorjboyd this is an error that was reported to vscode's error telemetry. I see that remote-ssh will call this command on the remote-explorer extension whether or not that extension is installed, so we should at least be checking that.

Also I'm not entirely sure why this command exists - I see remote-ssh has a "get" command which looks similar, and it seems like ideally remote-ssh would only expose "getXYZ" commands for the explorer to call whenever it needs data, instead of calling a "set" command on the explorer which forces it to activate, maybe unnecessarily.

**Comment by dokutoshi** [comment]
Any updates on this error. @eleanorjboyd   The error appears in VS Code 1.90 using Remote SSH.
![image](https://github.com/microsoft/vscode-remote-release/assets/10182821/07123412-3160-4031-83bd-92d56b00998b)

**Comment by roblourens** [comment]
You should be able to ignore it

**Comment by dokutoshi** [comment]
i believe it is related to a related issue [kernels reset for dynamic folders ](https://github.com/microsoft/vscode-python/issues/23452#issuecomment-2231272590) @roblourens 

> You should be able to ignore it

**Comment by bob2402** [comment]
After I installed [Remote Explorer](https://marketplace.visualstudio.com/items?itemName=ms-vscode.remote-explorer), this error message disappeared.
