### ISSUE TITLE
devcontainer cli do not open vscode window

### ISSUE THREAD

**Issue by marc-spinozza** [microsoft/vscode-remote-release#7189]
- VSCode Version: 1.71.1
- Local OS Version: 21H2
- Remote OS Version: Ubuntu 22.04 (WSL2) - Docker installed in ubuntu (not using docker desktop)
- Remote Extension/Connection Type: Containers

Steps to Reproduce:

1. Start dockerd in ubuntu
2. cd to project folder
3. devcontainer open .

![imagen](https://user-images.githubusercontent.com/1254546/190146251-447cd249-9d81-4a1a-b1ef-fe6820dcf1c9.png)

VS code windows in never opened

If I try **devcontainer --help** the execution do not finalise (it never returns to the prompt) I have to Ctrl+C to get the prompt back

If I do a **code .** in the folder then a vscode notification appears to reopen the folder in the container. This works fine as expected.

I have uninstall vscode and extensions and do a clean install but i still get the same problem.

**Comment by chrmarti** [comment]
`process.argv0` in the extension host process changed to `/proc/self/exe` on Linux. Not sure when this changed and don't see it discussed elsewhere. @deepak1556 Do you know?

**Comment by deepak1556** [comment]
@chrmarti in Insiders we use the new process API from Electron to launch extension host which is backed by setting `"extensions.experimental.useUtilityProcess"` and this API ensures that the process is forked by chromium instead of VSCode forking it with Node.js `child_process.fork` API. Chromium uses `/proc/self/exe` to be execcd in the forked process and thats what ends up in the `process.argv0`. You should instead rely on `process.execPath` to get the resolved path https://nodejs.org/dist/latest-v16.x/docs/api/process.html#processexecpath, also this will yield consistent results for both `extensions.experimental.useUtilityProcess` enabled and disabled.

**Comment by roblourens** [comment]
Did the cli API change? Or am I looking at the wrong CLI? I installed with npm, and there is no "open" command. So I installed through the extension and that seems to be totally broken.

<img width="736" alt="image" src="https://user-images.githubusercontent.com/323878/193323405-dc8b1d88-5cd7-4f7d-8090-36100def6d9f.png">

**Comment by mjbvz** [comment]
@chrmarti Can you please provides steps to verify this issue

**Comment by rzhao271** [comment]
Reopening issue and setting it to the next milestone.
Even with `@vscode/dev-container-cli`, I don't get the open command anymore.
Instead, I get the following output:
```
devcontainer open .
Unknown arguments: open, .
devcontainer <command>

Commands:
  devcontainer build [path]  Build a dev container image

Options:
  -h, --help               Show help                                                                           [boolean]
      --disable-telemetry  Disable telemetry                                                  [boolean] [default: false]
```

**Comment by chrmarti** [comment]
The fix was to remove `open` from the help text when installed from npm as `@vscode/dev-container-cli`. Closing again for verification and will open a new issue for what @roblourens reports. Thanks!

To verify: Install `@vscode/dev-container-cli` using npm and verify that the help text does not show `open` as an available command.
