### ISSUE TITLE
remote-container does not work

### ISSUE THREAD

**Issue by yushengjiexy** [microsoft/vscode-remote-release#7199]
I can connect the remote service by remote-ssh, but the remote-container dose not work.
![image](https://user-images.githubusercontent.com/63044657/190539231-8ed9ca12-0366-4172-9353-3c7bb522a73d.png)

**Comment by yushengjiexy** [comment]
could you help me？

**Comment by yushengjiexy** [comment]
when i click on the button "", remote-containers show log
![image](https://user-images.githubusercontent.com/63044657/190540813-74037f64-5674-43fd-9f9f-9faee76fd826.png)
![image](https://user-images.githubusercontent.com/63044657/190540883-ff91cb08-1d80-40ba-a9d9-7ce8d72da3a5.png)

**Comment by chrmarti** [comment]
Does `ssh 10.44.171.206 /bin/sh` work when you run it from the command line? Does it require any keyboard input?

**Comment by yushengjiexy** [comment]
No, it dose not work. It require keyboard input, just like the following.
![image](https://user-images.githubusercontent.com/63044657/191161953-45ca5bc4-1b82-4b55-b41c-2dbd0347096e.png)

**Comment by mawanda-jun** [comment]
Hi, I'm having the same issues since the last Win11 22H2 update. I'm working in a Windows 11 PC connected through ssh to a Linux 22.04 LTS machine. In this machine, Docker is installed and I use it to create containers and to attach VSCode to them.
I can connect to my remote machine with the Remote-SSH plugin, however I can't attach a VSCode window to the container anymore. It just hangs with this message
![image](https://user-images.githubusercontent.com/37183651/191679228-387f2d9e-4b93-4634-80b6-224f951c787d.png)

The problem was raised by the recent Win11 update I just installed. Is there anything I can do? Tell me if you need more information!

**Comment by chrmarti** [comment]
You could try using a private/public key-pair for authentication and on you local machine add the private key to the ssh-agent (which you first need to start in Windows' Services settings) using `ssh-add`. That will allow you to connect to the SSH server without additional keyboard input and might avoid the issue you are seeing.

**Comment by martinerk0** [comment]
https://github.com/microsoft/vscode-remote-release/issues/7295#issuecomment-1273195599

Had same problem, already answered here. @chrmarti I think it worked without needing ssh keys just a month ago? Only requiring password just like ssh extension without keys.

**Comment by chrmarti** [comment]
What do you get for `ssh -V`?

**Comment by martinerk0** [comment]
local: OpenSSH_7.6p1 Ubuntu-4ubuntu0.7, OpenSSL 1.0.2n  7 Dec 2017
host: OpenSSH_7.6p1 Ubuntu-4ubuntu0.5, OpenSSL 1.0.2n  7 Dec 2017

both are Ubuntu 18.04.6 LTS

**Comment by chrmarti** [comment]
Related: https://github.com/microsoft/vscode-remote-release/issues/7322

**Comment by chrmarti** [comment]
Is this still an issue in the latest version? (We fixed a similar bug in https://github.com/microsoft/vscode-remote-release/issues/7355.)
