### ISSUE TITLE
Can we open remote container with remote ssh ?

### ISSUE THREAD

**Issue by Yablon** [microsoft/vscode-remote-release#721]
Firstly, I think the remote development extension is awsome !
I work on private servers of my group. I think I have to prepare my environments for every server and cannot share my environment with others.
It would be convenient that if I could open remote docker with remote ssh.
Do you have any advices to help me out or do you have any plans adding that feature ?
Thank you!

**Comment by chrmarti** [comment]
The current workaround is to set up an SSH tunnel to the remote Docker daemon: https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host

There are no immediate plans, we keep thinking about it. :)

**Comment by Chuxel** [comment]
There's also support for passing "ssh://" into "docker.host" that is coming once a downstream dependency updates that will streamline this a bit (see #636), but you'll still need to alter devcontainer.json to not use local bind mounts since Docker cannot do these remotely. See the  https://code.visualstudio.com/docs/remote/containers-advanced#_using-devcontainerjson-to-work-with-a-remote-dev-container sub-section for details on how to set this up.

**Comment by Yablon** [comment]
Thank you all! I will try them.
