### ISSUE TITLE
devcontainer only starts under user vscode 

### ISSUE THREAD

**Issue by jfaleiro** [microsoft/vscode-remote-release#7331]
- VSCode Version: 1.72.1 (Universal)
- Local OS Version: MacOS Monterrey 12.6 M1
- Remote OS Version: mcr.microsoft.com/vscode/devcontainers/java:0-11-bullseye
- Remote Extension/Connection Type: Containers
- Logs:

Steps to Reproduce:

As of this morning `devcontainer` only starts under user `vscode`. It no longer starts under `root`. 

The `runArgs` parameter in `devcontainer.json` and `USER` command in `Dockerfile` are ignored.

Parameters `remoteUser` or `containerUser` in` devcontainer.json` are also ignored.

This is affecting multiple environments.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by ggravlingen** [comment]
I had some user-related issues as well yesterday and it sounds a bit related to this. I haven't seen the errors before so my guess is that there have been some changes in upstream docker images? I'm using the `mcr.microsoft.com/vscode/devcontainers*` images for my containerised environments.

In my `Dockerfile` I had the following lines:
```
ENV LOCAL_USER="vscode"
USER $LOCAL_USER
```

This caused the build to crash. When removing the line `USER $LOCAL_USER` it worked again but led to a lot of workarounds since I actually wanted the subsequent actions to be made by the local user.

So I tried changing that same line to `USER 1000` and that actually solved the issue for me. Now I can build my containerised environments again.

**Comment by jfaleiro** [comment]
> @jfaleiro Try adding `"remoteUser": "root"` to your devcontainer.json.

@chrmarti please see above, that was one of the first fixes we tried, after making changes, `Dev Container: Rebuild Container` ignores the changes and starts under `vscode` user again.

> The `runArgs` parameter in `devcontainer.json` and `USER` command in `Dockerfile` are ignored.
> Parameters `remoteUser` or `containerUser` in` devcontainer.json` are also ignored.
