### ISSUE TITLE
How to modify the "ssh targets recent list"?

### ISSUE THREAD

**Issue by jiuyuan-light** [microsoft/vscode-remote-release#7474]
![image](https://user-images.githubusercontent.com/89025318/200115087-d19aba1d-35b3-4973-a856-0ee4c5a0a826.png)
As shown in the figure, I want to change the host alias 192.168.100.100 to XXX, but the "ssh targets recent list" will be cleared. How can I keep or modify it?

**Comment by eleanorjboyd** [comment]
To confirm is the `ssh targets` list in the remote explorer?

**Comment by eleanorjboyd** [comment]
To clarify I was asking if the panel you are look at on the left side of your screenshot is on the remote explorer extension- you can tell because this icon on the sidebar takes you there:
<img width="70" alt="Screenshot 2022-11-08 at 8 29 31 AM" src="https://user-images.githubusercontent.com/26030610/200621627-465755af-afde-4880-81be-183792d46f59.png">

If this is true can you provide step by step instructions for how you went about changing it and which list gets cleared when? I tried to replicate the issue you are experiencing and on my machine the ssh target name changed and stayed on the list in my remote explorer. Thanks!

**Comment by jiuyuan-light** [comment]
Sorry, I misunderstood. I thought that the remote resource manager you mentioned was a remote host.
Next, I will describe the following problems and expectations in detail:
1、First, I have a list of ssh targets pointed to by the host alias("host" field) 192.168.100.100, as shown in the figure，
![image](https://user-images.githubusercontent.com/89025318/200859036-aa5d2721-4c13-493d-a7cf-23ca80ca6623.png)
2、Second, I want to change 192.168.100.100 to XXX(In addition, I changed the host alias, not the host name ("hostname" field)), but the ssh targets list pointed to by the host alias XXX is empty, as shown in the figure. 
I expect XXX to point to the ssh targets list pointed to by 192.168.100.100.
![image](https://user-images.githubusercontent.com/89025318/200860020-2fd969cb-2832-4507-a94f-ba25eaf6b146.png)
Thanks for your help.

**Comment by eleanorjboyd** [comment]
Hello! Thank you for your clarification. On further analysis it seems that what you are seeing is the written behavior for the SSH targets list. When a remote is renamed it is considered a new remote connection and therefore will not retain any of the recent targets list.
