### ISSUE TITLE
Support for folders with multiple devcontainer.json files

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#7548]
The dev containter spec has update to allow for [multiple devcontainer.json files to exist in a sub-folder of `.devcontainer`](https://containers.dev/implementors/spec/#devcontainerjson) in the root of the workspace.  This has been implemented in Codespaces, but not the Dev Containers extension.  This issue tracks adding that support.

**Comment by eitsupi** [comment]
I think this feature is really great. I would rather use multiple small containers than have one huge one.

**Comment by sterling000** [comment]
Really really need this, my current client has a mono-repo where the src folder is treated like the "root" folder for their django project, and then when they added react components they are within a subfolder of that src folder, and the context needs to be the project root, so i need to have the .devcontainer.json files be separate for team members who work in django or work in node but sharing the same workspace. Need to support multiple devcontainer.json files with different docker images and extensions etc but with the exact same volume mounts and workspaces so that all their existing shell scripts work without rewriting all the references.

**Comment by sterling000** [comment]
I need to be able to open the root folder and select among multiple devcontainer.json files, if i ave to use "Open Folder in Container" and select the subfolder that has the devcontainer.json file in it then even if the container is created and the volume is mapped, the wrong folder is opened because now it's limited to just the subfolder but i want the parent folder to be the one opened in vscode

**Comment by sterling000** [comment]
I would be open to having a docker-compose file in the root of the project, but when i run "Open folder in dev container" or "reopen folder in container" it does not currently detect my .devcontainer/django/devcontainer.json file or my .devcontainer/node/devcontainer.json file and asks me to create a new single devcontainer.json file instead of selecting from the existing ones.

**Comment by chrmarti** [comment]
Implemented for local folders, tracking support for "Clone in Volume" with https://github.com/microsoft/vscode-remote-release/issues/7879.
