### ISSUE TITLE
Can't connect thorugh browser version's remote Explorer

### ISSUE THREAD

**Issue by XgamerTV** [microsoft/vscode-remote-release#7566]
- VSCode Version: Newest (Insiders)
- Local OS Version: Windows 11
- Remote OS Version: Windows 11 and iPadOS 16
- Remote Extension/Connection Type: Server
- Logs:

When connecting to my running server from a local desktop VS Code it works but on web version (Windows or ipadOS) nothing happens when clicking on connect through the remote explorer only when I enter the URL with /tunnel/tunnel_name it connects...

**Comment by eleanorjboyd** [comment]
Does using the command from the command palette `remote-ssh: connect to remote` work? Can you send a screenshot of the remote explorer like where you are clicking and then also check in dev tools to see if there are any error messages?

**Comment by jonathanrdelgado** [comment]
I'm having the same problem. I have a machine running `code-server`, which creates a tunnel. I am able to go directly to https://vscode.dev/tunnel/TUNNEL_NAME and it works perfectly. However, if I go directly to https://vscode.dev and then attempt to connect to a tunnel, it seemingly does nothing. This is mostly notable for me just because I'm trying to get this setup on an iPad, which uses the PWA, starting at the root of the vscode.dev domain.

I've tried this on insiders, as well as Chrome, Firefox, and Safari -- same issue.

Reproduction steps for me:
1. Navigate to https://vscode.dev/
2. Login
3. Click on either the green icon in the bottom left and click connect to tunnel, or click on the remote extension on the sidebar
4. See the tunnel name that I expect to see, and click on it
5. Nothing happens, just is seemingly a no-operation. Same result for clicking start in a new window.

Let me know if there is anything else I can provide to aid in debugging!

**Comment by eleanorjboyd** [comment]
Hello @jonathanrdelgado, are you using the remote tunnels extension? If so could you create a new issue so we can direct it to the person in charge of tunnels. Thanks

**Comment by jonathanrdelgado** [comment]
Found a cross issue at https://github.com/microsoft/vscode-remote-release/issues/7577

**Comment by jonathanrdelgado** [comment]
@eleanorjboyd The [extension page](https://marketplace.visualstudio.com/items?itemName=ms-vscode.remote-server) links back to this repo, where is the best place to post this issue?

**Comment by eleanorjboyd** [comment]
@jonathanrdelgado I will actually let @connor4312 who is in charge of tunnels determine if these two issues are related or if two different issues should be used to provide separate discussion threads. Thanks

**Comment by connor4312** [comment]
I made a PR to fix this, you'll need to use insiders.vscode.dev until the stable release next week
