### ISSUE TITLE
Can the settings editor validate incorrect ranges

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-remote-release#7608]
Testing #7594

If the range is X-Y and X>Y, can we show a warning message similar to 
![image](https://user-images.githubusercontent.com/6561887/204672205-4119988f-9a75-457a-96a9-9af8ca4ff3a4.png)

**Comment by eleanorjboyd** [comment]
Hi! This is a great suggestion but the input for the range parameter is a string. Therefore it seems like the regex expression to check and then produce a warning message would be fairly difficult. I think this would be a great fix if easier but since it does look like a challenging fix I am going to mark this as out of scope. Thanks!
