### ISSUE TITLE
"Create New Integrated Terminal (Local)" fails on MacOS with `"/usr/bin/zsh" does not exist`

### ISSUE THREAD

**Issue by jakub-g** [microsoft/vscode-remote-release#7656]
# Context 

- VSCode Version: 1.74
- Local OS Version: Mac OS 12.6
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: SSH

#### Steps to Reproduce:

1. On MacOS, connect to remote workspace over SSH
2. `cmd-shift-p` > `"Create New Integrated Terminal (Local)"`
3. Observe the error:
> The terminal process failed to launch: Path to shell executable "/usr/bin/zsh" does not exist.

#### More info:

I assume VSCode tries to run `/usr/bin/zsh` from host MacOS, because the guest Ubuntu does have `/usr/bin/zsh`.

When I try on MacOS `which zsh` it prints `/bin/zsh`. I tried `sudo ln -s /usr/bin/zsh /bin/zsh` on my local machine, but I'm getting "Operation not permitted" error.

# Fix

I finally made it work with `cmd-shift-p` > `Open remote settings (JSON) (SSH-...)` > adding this:

```
    "terminal.integrated.shell.osx": "/bin/zsh"
```

Maybe this should be the default value?

**Comment by eleanorjboyd** [comment]
Hello! Thank you for submitting a bug on the remote-SSH extension. We have a new form specifically for SSH bugs so if you could resubmit your issue there that would be extremely helpful since it has some extra debugging steps and information it collects. [Here](https://github.com/microsoft/vscode-remote-release/issues/new?assignees=eleanorjboyd&labels=ssh&template=remote_ssh_bug_form.yml&title=%5BRemote-SSH+Bug%5D%3A+) is the link but it can also be found under `new issue` -> `Remote-SSH bug`. Closing this issue in favor of the SSH bug form. Thanks!
