### ISSUE TITLE
Slow Download option

### ISSUE THREAD

**Issue by patrizok** [microsoft/vscode-remote-release#7798]
Downloading big files is so slow.

While downlonading with python web server  it uses all bandwidth but while downloading vscode download option it is slow.

**Comment by eleanorjboyd** [comment]
Hello! Are you saying that when downloading VS Code it uses less bandwidth on your remote machine then other types of downloads you use? Can you provide an example? Have you tried switching the setting called `LocalServerDownload`, this setting changes `Whether the extension can download the VS Code Server on the client and transfer it to the host with scp, instead of downloading it on the host.` This could help with performance if your local machine is faster than your remote. Thanks
