### ISSUE TITLE
Always offer a "Reopen folder locally" in case of errors

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-remote-release#804]
testing #782 

Whenever there is an error in the dockerfile or docker-compose file and the project cannot be opened in the container, I'm presented with an error dialog that does not offer the option to open the project locally in a prominent place:

![2019-06-25_17-23-05](https://user-images.githubusercontent.com/1898161/60111319-081fa880-976e-11e9-9b46-84120a240cbf.png)

"Close Remote" is rather unhelpful as it throws the user completely out of focus.

There is the action "Open Folder Locally" behind a "More Actions...":

![2019-06-25_17-18-35](https://user-images.githubusercontent.com/1898161/60111078-8cbdf700-976d-11e9-9b8f-21efdaca4a34.png)

but that opens a new window but leaves alone the broken remote window.
In addition the action is called  "Open Folder Locally"  instead of the more intuitive name "Reopen folder locally" 

I suggest to have the "Reopen folder locally" available whenever there is a problem with remote and we actually have a project to where we "can go back".

**Comment by weinand** [comment]
@aeschli the same should be doen for WSL: whenever there is an error that prevents a successful connection to WSL, there should be an easy option to reopen the original project on Windows locally.

**Comment by bamurtaugh** [comment]
I believe our latest Remote - Containers work would apply here: we've been testing options when a user has errors and allow them to open their project/devcontainer.json/logs locally. As for WSL, we have the "Reopen Folder in Windows" command (although I suppose we could add an additional command that would come up if the user experiences an error dialog, although this would hopefully be less frequent than users having issues with Dockerfiles).

Since I believe the original containers issue is being addressed, going to close this issue - but we can also keep in mind an additional WSL use case for the future. If there's anything else here I might've missed or haven't considered, please let me know, and I'm happy to reopen or discuss further!
