### ISSUE TITLE
Lot of apparently dead processes on server side

### ISSUE THREAD

**Issue by krzikalla** [microsoft/vscode-remote-release#8143]
I am not sure, if related to https://github.com/microsoft/vscode/issues/176215

After closing VS Code (or after it crashed (see link above), which happens very frequently) I still see a lot of processes running on the server. `ps` gives me the following lines:
```
sh ~/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level off --connection-token-file ~/.vscode-server/.92da9481c0904c6adfe372c12da3b7748d74bdcb.token
\_ ~/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/node ~/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/server-main.js --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level off --connection-token-file ~/.vscode-server/.92da9481c0904c6adfe372c12da3b7748d74bdcb.token
  \_ ~/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/node ~/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/bootstrap-fork --type=ptyHost --logsPath ~/.vscode-server/data/logs/20230306T082741
  |   \_ /bin/bash --init-file ~/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
  \_ ~/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/node ~/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/bootstrap-fork --type=fileWatcher
...
```
And some more of these fileWatcher processes. `htop` is full of them.

**Comment by chrmarti** [comment]
Is this with Dev Containers? We keep the VS Code Server running in the container, it is only stopped when the container is stopped.

**Comment by krzikalla** [comment]
No, no dev container. Pure client/server connection with Windows on client side and Linux Ubuntu 20.04 on server side.

**Comment by eleanorjboyd** [comment]
What happens when you run the command "kill vscode server on remote"?

**Comment by dehy** [comment]
We had the same problem : a lot of dead `shellIntegration-bash.sh` processes. We had to SIGKILL them (ineffective SIGTERM)

We found out that was because we left the remote connection open on our VSCode, and the VPN disconnected during the night. On the morning, we had to relaunch VPN + remote connection and everything was working well, but the old process was not killed.

OS: Ubuntu 20.04
VSCode: 1.77.3
Plugin version: 0.100.0

**Comment by dehy** [comment]
We had dozens of `/bin/bash --init-file /home/XXXXX/.vscode-server/bin/704ed70d4fd1c6bd6342c436f1ede30d1cff4710/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh` processes whom parent was `systemd`, some started since the beginning of the month.
Thoses processes did not respond to SIGTERM. I had to SIGKILL them.

What I found since: those scripts were parents of long-running `ipython` executables. When the ssh connection drops (VPN disconnects), it seems that because the `ipython` executable is still running, the parent `shellIntegration-bash.sh` does not terminate correctly.

I have not yet reproduced the problem. I'll watch it in the coming days.
