### ISSUE TITLE
Add more authentication providers

### ISSUE THREAD

**Issue by Nevops** [microsoft/vscode-remote-release#8150]
I'm opening this feature request following issue #8041.

The proposed feature is to add more functionality to access the authentication providers such as Google, Bitbucket, and GitLab.

Currently, Visual Studio Code Server offers some authentication options such GitHub(default) and Microsoft, but there is a growing demand for additional authentication providers. By adding these providers, we can enable our users to sign in using their preferred authentication method and eliminate the need for them to create new credentials or sign up for another service.

Adding these authentication providers will enhance the user experience by making the authentication process more streamlined and efficient. Our users will appreciate the flexibility to use their existing accounts with other services, thus saving time and effort. Additionally, by incorporating more authentication providers, we can attract new users who rely on these services.
It will improve the user experience and attract new users. I strongly recommend that we prioritize this feature and work towards implementing it as soon as possible.

`USAGE:
    code tunnel user login --provider <PROVIDER>`

**Comment by connor4312** [comment]
@derekbekoe

**Comment by derekbekoe** [comment]
Hi - We don't have plans to support creation of tunnels using identities other than GitHub and Microsoft/AAD at this time.

However, I'd appreciate some further details on your use-case:
1. You mentioned "Our users..." and "...we can attract new users who rely on these services". Who is "we"? Are there specific users you had in mind here e.g. is this for an enterprise/organization?
2. Other than the user(s) not having a GitHub or Microsoft account, are there other reasons you can't use one of these 2 options?

**Comment by bamurtaugh** [comment]
Adding `info-needed` based on @derekbekoe's questions above.

**Comment by dgitw** [comment]
As a business (many thousands of employees) we would like to use corporate credentials rather than consumer accounts.

Scenario: Currently we are users of DevContainers using remote VM's / SSH which has its downsides (replicating source to remote for one). We are using a self-hosted instance Github Enterprise Server leveraging Azure Active Directory credentials.

Currently tunnelling only allows Github credentials (obviously feature is geared towards Codespaces). What's the plan for alternate tunneling credentials?

Is tunneling using AAD going to be supported in the future? Is tunneling seen as a mechanism for removing some of the friction from the Remote SSH / DevContainer scenario going forward?
