### ISSUE TITLE
Devcontainer rebuild/reload always fails, retry always works

### ISSUE THREAD

**Issue by janhurst** [microsoft/vscode-remote-release#8152]
This has been on and off for a while, with the error captured below appearing perhaps 10-20% of the time. It is now happening almost every single time.

![image](https://user-images.githubusercontent.com/16224889/223331074-e264b125-80d1-486d-a22f-7032a549bd50.png)

When I go to reload or rebuild my container I get dumped out to an error dialog. Hitting retry always works...

- VSCode Version: vscode 1.76.0 Dev Container extension v0.282.0
- Local OS Version: Windows 11 22H2 Build 22624.1391
- Remote OS Version: Debian from mcr.microsoft.com/devcontainers/miniconda:3
- Remote Extension/Connection Type: Containers
- Other Info: Using a Docker Compose based dev container

- Logs:
Not sure how to capture the log for this

Steps to Reproduce:

1. In a running container, Ctrl-Shift-P and run Dev Containers: Rebuild Container or Developer: Reload Window

**Comment by thclark** [comment]
I get this all the time, it's such a pain.

**Comment by aguckenber-chwy** [comment]
I have also had this issue for a year now. Rebuild always pops up an error but a retry always passes. It appears like the rebuild doesn't wait for the container to shut down so it errors, but by the time the retry is pressed, the old container is shutdown and the rebuild works.

**Comment by zifik** [comment]
I get this same error when rebuilding my container locally on Windows with WSL. However, when rebuilding a container running on a remote Linux machine, I never seen the issue.

**Comment by slobentanzer** [comment]
I have the same; retry every time.

**Comment by ryanhiebert** [comment]
My assumption has been that this is a race condition. VSCode sends a message to shut down the docker containers in the docker compose, but they aren't fully turned off before it's trying to rebuild it again, and that causes an error. Retrying allows it the time docker needs to shut it down, then things work.

If there were a check or a wait for the shut down to complete, that could likely solve the issue if my hypothesis about the cause is correct.
