### ISSUE TITLE
Remote Tunnels: Unexpected extension installation behavior when tunneled into a machine from the web

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode-remote-release#8252]
Steps to Reproduce:

1. Enable tunnelling on a machine. 
2. Tunnel into that machine from the web https://insiders.vscode.dev/tunnel/machine-name
3. Open the extensions page and search for Remote-SSH. 
4. Remote SSH shows up as installable locally  
<img width="457" alt="image" src="https://user-images.githubusercontent.com/25044782/227393033-ef213a5e-8b8d-4e36-8c52-c88eb23476b9.png">
5. Click Install

Install fails with: 

<img width="357" alt="image" src="https://user-images.githubusercontent.com/25044782/227393257-dae7c381-e746-4455-ae18-ad5c368aaa8a.png">

**Comment by connor4312** [comment]
This is expected: remote SSH is a UI extension, which does not operate in the browser.

**Comment by bhavyaus** [comment]
> This is expected: remote SSH is a UI extension, which does not operate in the browser.

Then the `Install` button should be disabled on the web? The first screenshot is also on the web.

**Comment by sandy081** [comment]
This is designed, because we cannot know whether an extension is an UI extension or not unless we get the extension manifest (package.json). Getting manifests for all extensions during search is a costly operation. Hence we chose to show install and show the error afterwards. It is different for a non-web extension in vscode.dev serverless mode. We know upfront what are web extensions.
