### ISSUE TITLE
New port forwarding created every few seconds with option `network==host`

### ISSUE THREAD

**Issue by fnobis** [microsoft/vscode-remote-release#8294]
I am running on the latest vscode version, developing in a docker environment.

Opening a folder in docker with the settings in devcontainer.json file works fine.
However, when I specify the option `"runArgs": [ "--network=host"]` in the json file, every few seconds a new port forwarding is created, e.g. in the screenshot over 1k ports.
![Screenshot from 2023-03-29 16-17-22](https://user-images.githubusercontent.com/36134338/228567789-539d182c-df19-43b0-b854-8d02e0f389bb.png)

They all share the same Running Process:
![image](https://user-images.githubusercontent.com/36134338/228567700-9b94edc6-2332-4e94-9141-e63df527d27c.png)

**Comment by bamurtaugh** [comment]
@alexr00 assigning to you for the port forwarding aspect, please feel free to reassign as you see fit though!

**Comment by alexr00** [comment]
@fnobis I don't know what `network==host` is used for, but it seems like it does the following:
- starts a process
- from that process, listens on a port 
- every few seconds it starts listening on an other port

You get lots of forwarded ports very quickly because we:
- watch your proc file system for running processes
- every couple seconds we look in your proc file system for running processes that are listening on a port
- forwarded every port we find this way
- when we no longer see that the process is listening on the port, we unforward it

I would suggest that you change the setting `remote.autoForwardPortsSource` to the new value `hybrid` (not yet released) or `output`. This will stop VS Code from forwarding ports that it finds in your proc filesystem.

**Comment by fnobis** [comment]
Thanks for the suggestion @alexr00.

I use the option for easier development, not needing to distinguish between inside docker or fowarding specific ports for any application communicating over ports (also when not working in vscode).

> The --net=host option is used to make the programs inside the Docker container look like they are running on the host itself, from the perspective of the network. It allows the container greater network access than it can normally get.

https://stackoverflow.com/a/43317607

Your suggestions with setting the `remote.autoForwardPortsSource` to `output` seems to surpress the ports from being generated, so it looks ok. To me, it is not clear which mechanism is responsible for listenining on a new port repeatedly in the first place. It seems to be originating from vscode itself though, if I look that the running process tab in the issue.

**Comment by simpros** [comment]
Hi @fnobis, did you make it work? I am having a tough time to get the devcontainer running in network=host. I tried it with `"runArgs": ["--network=host"]` but no success so far.
