### ISSUE TITLE
install remote SSH extension on a SAW device

### ISSUE THREAD

**Issue by saeedmaleki** [microsoft/vscode-remote-release#8299]
Hi folks,

I am trying to install this extension on VS code after I got the approval for it and unfortunately, VS code reports that 0.98.0 version of the extension is not compatible with my VS code version 1.71.2. Is this really a compatibility issue?

**Comment by eleanorjboyd** [comment]
looking into this now- thanks

**Comment by eleanorjboyd** [comment]
Hi! Yes, we do need version 1.74 since "This was to adopt implicit activation events, which are only supported beginning with 1.74". You could use a previous version of the remote-ssh extension and therefore it wouldn't require a newer version of vscode. How our extension works is it will install the same version on your remote machine that you have on your local machine so your local machine needs to have both earlier versions of vscode and remote-ssh extension. Remote-ssh version "0.86.0" should work since that is compatible "^1.71.0" while "0.88.0" is compatible with "^1.72.0". You can select older version on the remote-ssh extension by going the the extension view and using "install other version.." from the dropdown.
<img width="1079" alt="Screenshot 2023-04-03 at 8 44 24 AM" src="https://user-images.githubusercontent.com/26030610/229560607-eb4a6060-3b93-4f10-94b1-b5eec54f4e77.png">
