### ISSUE TITLE
Devcontainer - wrong java 8 container url

### ISSUE THREAD

**Issue by magnus-m** [microsoft/vscode-remote-release#8316]
When creating a java 8 container by command "Open folder in Container", I get this error:
`"No manifest found" for mcr.microsoft.com/devcontainers/java:0-8`

It can be solved by changing the `devcontainer.json` from:
```json
{
	"name": "Java",
	"image": "mcr.microsoft.com/devcontainers/java:0-8",
}
```

to

```json
{
	"name": "Java",
	"image": "mcr.microsoft.com/devcontainers/java:8",
}
```

**Comment by samruddhikhandale** [comment]
Looking at https://mcr.microsoft.com/v2/devcontainers/java/tags/list and [devcontainers/images/tree/main/src/java-8](https://github.com/devcontainers/images/java-8), the `java:8` image was released with major version `1`. Hence, no image exists with version `0` for path `mcr.microsoft.com/devcontainers/java`.

@bamurtaugh How can we update the `Open folder in Container` command to pin `java:8` to major version `1` instead of `0`?

**Comment by chrmarti** [comment]
This was fixed in the template.
