### ISSUE TITLE
Provide a welcome view for Dev Volumes view in Remote Explorer

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-release#8398]
While looking at https://github.com/microsoft/vscode/issues/178854 I noticed that currently, if Docker is installed but not running, there is welcome text in the Dev Containers view but the Dev Volumes view is empty. Initially, I thought the tree was broken:
<img width="392" alt="image" src="https://user-images.githubusercontent.com/30305945/233460295-be8a863e-d149-4933-9c44-6b4d3e6bfc64.png">

It would be nice to have some explanation of what should appear here and how to create a dev volume if Docker is already running and I happen to not have any dev volumes (which I think is possible).

**Comment by bamurtaugh** [comment]
Looks like this has since evolved and we show some sort of message:

![Image](https://github.com/user-attachments/assets/e0461bbb-dc02-40e7-a815-dfa1194556db)

Closing for now since it at least no longer appears like the view is broken, and we can assess if we get further user feedback that the messages shown are insufficient.
