### ISSUE TITLE
Explorer: on Linux cannot drop file to Desktop from remote

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-remote-release#849]
I suggest to disable it then for remote URLs on Linux.

**Comment by isidorn** [comment]
I have verified that I can not drop files to Desktop on Linux from remote.
Though for me no crash happens, just a weird file gets dropped (with the full uri as the name).
I will disable the writing of download_url on linux and when in remote. 

@bpasero Do you think for this release or next? Since it is not a crash on my machine I would lean towards next release. Though I have a fix ready.

**Comment by bpasero** [comment]
@isidorn next month is fine
