### ISSUE TITLE
VS code server loses all environment variables, have to kill it every day #7290

### ISSUE THREAD

**Issue by SolidusDigital** [microsoft/vscode-remote-release#8505]
I have the same issue just recently started to appear on one of my remote machines when connecting over ssh via public IP, the only way to fix it is to uninstall vs code server on the remote machine then reinstall, this will work ok for approximately 1 day. Another thing to mention is that  I can recreate this issue 100% of the time on machines that do not have this issue by simply ssh over tailscale vpn IP instead of public ip. The first day everything will be ok with the shell variables however by the next day the only solution is to uninstall vs code server.  It would be nice to fix this so that I can use the VPN IP to ssh, however not sure what triggered the recent issue with 1 of my machines where the same thing happens over public IP. The only changes made to the host was some linux updates. 
_Originally posted by @roblourens in https://github.com/microsoft/vscode-remote-release/issues/7290#issuecomment-1374081968_

**Comment by SolidusDigital** [comment]
@roblourens

**Comment by roblourens** [comment]
I gave some suggestions on how to troubleshoot this in the linked issue. Following those would be the best way to help me

**Comment by shekhovt** [comment]
Since some time, I am using a different method to configure the environment, which seems to not have any issues with losing the environment variables. The method is to create a bash script that initializes the environment and calls python:

#!/bin/bash -l
# set up environment (we use LMod)
ml purge
ml matplotlib/3.5.2-foss-2022a
ml torchvision/0.15.0-rc1-foss-2022a-CUDA-11.7.0
python "$@"

In the "Select Interpreter" dialog you specify this script. It can be placed in the local project folder and can be different per project. I do not have to restart VS code server after sleep -- it reloads a window correctly and everything works. If I change the contents of the script, it seem to have immediate effect for running / debugging. For the static analysis to pick up changes a window reload suffice without restarting VS code client or server.

The only thing that does not work with such interpreter is when VS code tries to call pip (to install something like autopep8).

**Comment by SolidusDigital** [comment]
I will test to see see if this is still an issue, it's only reproducible when accessing VS code remote over TS VPN, (although for a time that was not the case)
