### ISSUE TITLE
Reopening multiple projects after wsl shutdown

### ISSUE THREAD

**Issue by ymongo** [microsoft/vscode-remote-release#8630]
- VSCode Version: 1.79.1 (user setup)
- Local OS Version: Windows 11 Professionnel 22000.1936
- Remote OS Version: Ubuntu 22.04
- Remote Extension/Connection Type: WSL

- Logs:

Steps to Reproduce:

1. Start wsl from windows host `wsl`
2. Launch a project in a VSCode window
3. Launch another project  in a VSCode window. So far everything works fine 
4. Close wsl from windows host `wsl --shutdown` while keeping VSCode windows open. They'll show a modal saying thhey're trying to reconnect
5. Start again wsl from windows host `wsl`
6. Witness that the multiples windows weren't able to reconnect to wsl

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Not related to extensions I think

Nothing alarming here, I just spent a few minutes trying to update wsl without success, before I found that I just need to close all windows, shutdown wsl and reopen the windows. 

Total duplicate of https://github.com/microsoft/vscode-remote-release/issues/7831, but it's worth beeing reproduced and resolved by your teams

**Comment by Spongman** [comment]
I see the same thing. `wsl --shutdown` breaks vscode remote-wsl. no amount of 'reconnect' or 'reload window' fixes it. the only solution is to `taskkill /f /im code.exe` and restart.

**Comment by aeschli** [comment]
Yes, that's expected. We do not try to recover from a wsl --shutdown.
No plans for that.

**Comment by jozenstar** [comment]
@aeschli Any chance you could change your mind on this? I've been using WSL for ~7 years now and since then this has been one of the most annoying things. Having to close all vscode windows with all the terminals and the rest of the stuff and open everything from scratch is a pain. And it breaks not just after the `wsl --shutdown`, but also after hibernating the host Windows system for some reason

**Comment by danvy** [comment]
The most annoying problem with vscode to me.
Each time Windows wake up, vscode instances are attempting to reconnect but fail miserably. Obliged to quit all vscode instance and relaunch.
Reload windows is not enough (The editor could not be opened due to an unexpected error. Please consult the log for more details.)

**Comment by al32-rs** [comment]
In my case WSL frequently doesn't wake up properly after standby or hibernation. Going through closing and reopening all the VSCode instances most of the times I have to move the laptop is literally a productivity hog.
@aeschli I don't understand why can't the extension just reinstantiate the missing vscode server on WSL newer sessions. Is it such a deal breaker? With docker containers this approach seems to work seamlessly.
