### ISSUE TITLE
Dev Containers cannot open the container's folder

### ISSUE THREAD

**Issue by ZldCoder** [microsoft/vscode-remote-release#8830]
- VSCode Version:Version: 1.81.1 (system setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
- Local OS Version: Windows 11 22H2
- Remote OS Version: Docker Desktop 4.21.1 (114176) and the container OS is ubuntu20.04
- Remote Extension/Connection Type: Containers

- Logs:
[1752 ms] Dev Containers 0.304.0 in VS Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794).
[1751 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[1919 ms] 1.43
······
[5113 ms] No dev container config found. No repository connection string found.

- Steps to Reproduce:

1. Open a previously opened folder of a Container on the remote explorer screen, click the "Open in Container in Current Window" icon on a folder
2. Wait a while, vscode issues an error message “ Error running command remote-containers.openFolderInContainerInCurrentWindow: A system error occurred (ENOENT: no such file or directory, scandir 'C:\home\xxx'). This is likely caused by the extension that contributes remote-containers.openFolderInContainerInCurrentWindow.” 

According to vscode's error message, it is obvious that the open path is a linux path, so there should not be a "C:" at the beginning of the path

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

![1 复现步骤](https://github.com/microsoft/vscode-remote-release/assets/52848071/31947cd4-f280-4291-b0b6-e6620be010a3)
![错误提示](https://github.com/microsoft/vscode-remote-release/assets/52848071/b8773eac-4f25-4158-90dc-a6225bb31a78)

**Comment by phparkle** [comment]
Facing the same issue here

**Comment by Acathe** [comment]
I encountered the same issue. I'm using Docker Dev Environments on macOS. When I try to open a folder in a Dev Container, it also gives me the same problem.

**Comment by yzliu** [comment]
Facing the same issue here 
docker image is ubuntu

**Comment by yoedgin** [comment]
Definetly an issue with the latest extension version. 
Got "locked out" my dev environment, and the issue dissappear after downgrading to the previous version (v0.299.0) from the extension page -> Uninstall -> Install another version

**Comment by ZldCoder** [comment]
> Definetly an issue with the latest extension version. Got "locked out" of my dev environment, and the issue dissappeared after downgrading to the previous version (v0.299.0) from the extension page -> Uninstall -> Install another version

It does work. Thank you

**Comment by EnderCaster** [comment]
same here.
System: Deepin 20.9
docker: debian version 24.0.5 build ced0996
plugin version: 0.304.0
vscode version: 1.81.0

**Comment by chrmarti** [comment]
Please append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)

**Comment by EnderCaster** [comment]
> Please append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)

I'm not in any container or remote env.
and there is dev container log after I click a folder "Open In container in current folder":

[99349 ms] Start: Run: docker inspect --type container 9e32d202e93668150f79a275a667c94ea79b4b08147ad0a66badc022cfb4c774
[99385 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[99424 ms] 1.43
[99459 ms] No dev container config found. No repository connection string found.

and then a tip pop up 

Error running command remote-containers.openFolderInContainerInCurrentWindow: A system error occurred (ENOENT: no such file or directory, scandir '/workspace/mall'). This is likely caused by the extension that contributes remote-containers.openFolderInContainerInCurrentWindow.

The directory /workspace/mall is  from -v: -v /home/user/workspace:/workspace


I tried the steps in right container, it also report the error.
but I can use "open folder"(ctrl K, ctrl O) to open the folder

**Comment by wutianjie** [comment]
Latest version (v0.309) still has the same issue. I can't open two windows in one container at the same time, but installing previous version could work.

**Comment by cirolosapio-accenture** [comment]
same here
version 0.312.0 not work
installing previous version (0.311.0) work
