### ISSUE TITLE
After Dev Container build execute vscode command, like go.tools.install

### ISSUE THREAD

**Issue by yuan1238y** [microsoft/vscode-remote-release#8981]
I use there config build Dev Container:
```json
{
    "name": "go-1.18.10-lint-1.47.3",
    "image": "internal.registry/golang:1.18.10-lint-1.47.3",
    "mounts": [
        {
            "source": "/root/.netrc",
            "target": "/root/.netrc",
            "type": "bind"
        }
    ],
    "customizations": {
        "vscode": {
            "extensions": [
                "golang.Go"
            ]
        }
    }
}
```

When i rebuild the container, I always need install my go tools.

Can we tell remote extension execute vscode command `go.tools.install`?

**Comment by bamurtaugh** [comment]
I'd expect the Go image you're using to have the necessary tools. If not, I'd definitely welcome checking out our dev container Go template, which you can get by using the command "Dev Containers: Add Dev Container Configuration Files" and selecting "Go."

Let me know if using our Go template works any better. Otherwise, you can check out Features: https://containers.dev/implementors/features/, and lifecycle scripts: https://containers.dev/implementors/json_reference/#lifecycle-scripts for additional installations.

**Comment by yuan1238y** [comment]
OK!
I resolved this issue.
I can use `lifecycle-scripts` install extensions.
Like:
```json
{
  // ...
  "postCreateCommand": {
    "extension": "code --install-extension golang.Go"
  }
  // ...
}
```
