### ISSUE TITLE
Prevent Disconnecting SSH Remote Session when Laptop is Locked

### ISSUE THREAD

**Issue by AlJohri** [microsoft/vscode-remote-release#9087]
Currently whenever I lock my laptop, the VSCode SSH Remote Session disconnects and I need to connect it back again.

I would love if there was a way to leave the session connected while the computer is locked (not asleep) so I can step away for a few moments without disrupting my setup.

**Comment by amityweb** [comment]
This issue is bigger than just this inconvenience.... I just went for lunch, came back and unlicked my Macbook, and had to reconnect the remote session, and all my open files Undo history has gone. I use undo and redo extensively, and just a laptop lock deletes it. I never had this issue on any other editor I used for decades.

**Comment by roblourens** [comment]
Can you share the Remote-SSH log from the output channel from this scenario?

Also you can try setting `"remote.SSH.useExecServer": true` to see if that helps.

One possibility is that your laptop is not connected to the network at first, and so reconnection fails after reopening it.
