### ISSUE TITLE
Warning notification about ssh-agent service being required when connecting to docker container

### ISSUE THREAD

**Issue by smhc** [microsoft/vscode-remote-release#9202]
- VSCode Version: 1.84.2
- Local OS Version: Windows 10 Enterprise 20H2
- Remote OS Version: RHEL8.6
- Remote Extension/Connection Type: Containers
- Dev Containers Ext versions: v0.321.0, v0.322.0

- Logs:

"Could not connect to ssh-agent on local host (\\.\pipe\openssh-ssh-agent). Make sure the service is running."

Terminal within container sets the env var: SH_AUTH_SOCK=/tmp/vscode-ssh-auth-d4d50368-b81b-440d-92be-aac9f5b3c638.sock
this presumably affects SSH within the container.

Steps to Reproduce:

1.  (EDIT - not required) Create a .ssh directory on the Windows PC (can optionally set IdentityAgent=none in the config file
3. Disable Windows ssh-agent service (or have your IT admins force this on you)
4. Connect to docker container in vscode (repro'd using a docker context with TLS creds)
5. Check output logs and vscode popup notifications for the error: "Could not connect to ssh-agent on local host (\\.\pipe\openssh-ssh-agent). Make sure the service is running."

Does this issue occur when you try this locally?: No

The problem presumably doesn't occur if the local ssh-agent service is running, but in my case that is locked down by policy controls. I had tried removing the local '.ssh' directory but that doesn't seem to fix the issue.

**Comment by shadycuz** [comment]
Seeing the same thing since the October release of vscode. At first I thought it was a thing on my work laptop but after I updated my vscode on my personal laptop I started seeing the same popup again. 

I'm on linux but get the same popup:
> Could not connect to ssh-agent on local host (/run/user/1000/keyring/ssh). Make sure the service is running.

When I get this error I am unable to use `git`. I cant push or pull from inside the devcontainer. I have to completely reboot my PC for this error to go away and even then, it only goes away for a little while. It seems to come back if my laptop sleeps or if the screensaver comes on. 

```
Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:50:47.800Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.133.1-microsoft-standard-WSL2 snap
```

**Comment by chrmarti** [comment]
@shadycuz The agent on the local OS. Could you append the Dev Containers log from when this happens? (`F1` > `Dev Containers: Show Container Log`)

**Comment by shadycuz** [comment]
@chrmarti It hasn't happened for a while but it just did. Here is the [gist](https://gist.github.com/shadycuz/bf17fc99542e4bafbcdf99a61faaa938). I wonder if it could have something to do with multiple vscode windows open at the same time?

**Comment by chrmarti** [comment]
It can't find `/run/user/1000/keyring/ssh` on the local machine. Maybe that socket temporarily disappears.

**Comment by shadycuz** [comment]
@chrmarti I have been seeing that error for almost two years. It appears everytime I start WSL:
```
Preparing to enter genie bottle (in 3s); abort?
Starting genie:
Waiting for systemd....!!!!!
Agent pid 898
** Message: 02:53:17.779: couldn't access control socket: /run/user/1000/keyring/control: No such file or directory
```

I don't think that error is related, because my ability to use SSH inside the container to push and pull code will still work. It's only after some time that the `Could not connect to ssh-agent on local host (/run/user/1000/keyring/ssh). Make sure the service is running.` pop up notification appears in vscode and then I lose the ability to use SSH.

**Comment by shadycuz** [comment]
@chrmarti Also I did check and the directory and files are present

```
ls -la /run/user/1000/keyring/
total 0
drwx------ 2 shadycuz shadycuz 100 Dec 15 04:52 .
drwx------ 9 shadycuz shadycuz 340 Dec 15 04:52 ..
srwxrwxr-x 1 shadycuz shadycuz   0 Dec 15 04:52 control
srwxrwxr-x 1 shadycuz shadycuz   0 Dec 15 04:52 pkcs11
srwxrwxr-x 1 shadycuz shadycuz   0 Dec 15 04:52 ssh
```

**Comment by shadycuz** [comment]
@chrmarti So I was able to fix my issue. I'm not sure how it broke because I didn't change anything on my end 🙃, but I was able to change how I do my SSH agent and that did fix the issue.

If anyone else is running WSL2 and has had problems with there loging keyring or there SSH daemon, you can look at my dotfiles for a working setup.
https://github.com/shadycuz/dotfiles

**Comment by chrmarti** [comment]
Thanks for sharing @shadycuz!

Fixing the Windows case with https://github.com/microsoft/vscode-remote-release/issues/6957.
