### ISSUE TITLE
Remote create dev container: ESLint extension added

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode-remote-release#9245]
Testing #9238

When creating a new dev container (python template), the following extensions were added:
- ESLint
- Copilot
- Copilot Chat
- GHPRI
- Pylance
- Python

I don't think the ESLint extension should have been added to this container, right?

**Comment by paulacamargo25** [comment]
I create a python template too, and the ESLint extension was installed too.
<img width="354" alt="Screenshot 2023-11-28 at 3 05 19 PM" src="https://github.com/microsoft/vscode-remote-release/assets/17892325/a9767e0f-f6ad-46fc-9f6a-91869c8c3ced">

**Comment by chrmarti** [comment]
The ESLint, Pylance and Python extensions are configured as part of the python container image.

@paulacamargo25 Was black-formatter installed in the container or are you saying you have it installed locally?

**Comment by benibenj** [comment]
> The ESLint, Pylance and Python extensions are configured as part of the python container image.

In that case, all works well.

**Comment by paulacamargo25** [comment]
Oh i see, i have installed locally, and its not installed in the container.

**Comment by chrmarti** [comment]
@paulacamargo25 That's expected as we don't have a way to know that the black-formatter extension would make sense in this container (maybe something to think about as a feature in the future). We currently only treat the Copilot and Pull Request extensions special (by default) because of those we know that they are useful in all or most projects.

Hope that addresses all issues discussed. Closing this issue, thanks!
