### ISSUE TITLE
VSCode Remote as Git Editor!

### ISSUE THREAD

**Issue by OmriSama** [microsoft/vscode-remote-release#933]
I think it would be cool to have VSCode Remote be also used as Git editor for git on another machine.

I'm sure this has been suggested, but by extension this could also mean invoking `code` from the command line of a remote machine, but have that send a message to the VSC client.

So something like:

```shell
$ code-remote --wait
```
Which checks for and goes through the current VSC remote server daemon.

**Comment by roiderats** [comment]
That --wait already works. And here is a script that allows you to use other than integrated terminal: https://github.com/roiderats/vscode-remote-remote

**Comment by OmriSama** [comment]
> 
> 
> That --wait already works. And here is a script that allows you to use other than integrated terminal: https://github.com/roiderats/vscode-remote-remote

Wait, if you open files while in remote in the integrated terminal, they open in vscode???

**Comment by roiderats** [comment]
Yes, you can say "code somefile.py" inside the integrated terminal connected to remote host and it'll open on the editor running on your local machine. 

The integrated terminal has PATH set so that the command "code" will not run the remote machine's real VSCode(that you might also have installed on that server, as I do) but a program in $HOME/.vscode-server/bin/*/bin/ that commands the remote extension.

That's great, but it's limited to that integrated terminal and I like to use several non-integrated terminals positioned all around my screen, so my little script comes handy there.

**Comment by timothywangdev** [comment]
This feature is quite useful

**Comment by chrmarti** [comment]
Closing as this is already implemented.
