### ISSUE TITLE
[Remote-SSH Bug]: Your user cannot contain \ but it does contain \

### ISSUE THREAD

**Issue by jhudsoncedaron** [microsoft/vscode-remote-release#9444]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

Believe what I type into the box

### Steps To Reproduce

1. Have a domain-joined linux machine (or otherwise have a \ in your username
2. Try to connect to it with VS Code Remote SSH

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[13:48:18.536] Log Level: 2
[13:48:18.546] VS Code version: 1.85.2
[13:48:18.546] Remote-SSH version: remote-ssh@0.107.1
[13:48:18.546] linux x64
[13:49:06.768] Picking SSH host
[13:49:14.225] Selected DOMAIN\jhudson@hostname
```
</p>
</details>

**Comment by roblourens** [comment]
You can create an ssh config that has the username with backslash. Unfortunately since we have to programmatically construct some shell commands that contain the ssh connection string, we don't want to allow backslash here since it's too hard to do safely across shells, OSs, etc... we are also replacing the code that runs commands in the terminal so I hope to allow that in the future. Sorry for the trouble.

**Comment by jhudsoncedaron** [comment]
That ended up working; I found myself guessing it would not work because the logical consequence of that working is the bug can be fixed by "close your eyes and believe" because I tried both DOMAIN\username and DOMAIN\\username before filing the bug.
