### ISSUE TITLE
[Remote SSH] Only reads "Host" from ssh_config

### ISSUE THREAD

**Issue by Dani21** [microsoft/vscode-remote-release#951]
Remote SSH v0.44 is completely ignoring most of my `%userprofile%\.ssh.\config` file. It's only reading the "Host" lines. This means it's ignoring `HostName`, `User`, `Port` and I'm sure everything else you throw in there.

The current workaround I'm using is by entering `username@hostname:port` for the `Host` line.

**Comment by roblourens** [comment]
Can you explain in what way is it being ignored? We just run `ssh <host>` and let ssh read the config file.

**Comment by samk64** [comment]
@roblourens 
For me, somehow my Windows `~/.ssh/config` (which is `C:\users\<my username>\.ssh\config`) is not using the `Port` option. Here is my config:
```
Host centos@127.0.0.1
    HostName 127.0.0.1
    User centos
    Port 3022
    PasswordAuthentication yes
    IdentityFile: C:\users\sakim\.ssh\privatekey
```

Running the `Remote-SSH: Connect to Host...` command gives the following, which is running on port `22` and not `3022`. But strangely, it is using the `Hostname` and `User`, just not the port.
```
remote-ssh@0.44.2
win32 x64
SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a223132372e302e302e31222c2275736572223a2263656e746f73227d", attempt 1
SSH Resolver called for host: centos@127.0.0.1
Setting up SSH remote "127.0.0.1"
Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_5.4p1, OpenSSL 1.0.0 29 Mar 2010
Running script with connection command: "ssh"  -o ClearAllForwardings=true    "centos@127.0.0.1" bash
Install and start server if needed
> 
> ssh: connect to host 127.0.0.1 port 22: Connection refused
> The process tried to write to a nonexistent pipe.
> 
"install" terminal command done
Received install output: The process tried to write to a nonexistent pipe.
The process tried to write to a nonexistent pipe
------

```

my default `ssh` binary is `C:\MinGW\msys\1.0\bin\ssh.exe`, which was installed from Git for Windows.

I can manually connect to my VM using the command directly: `ssh -p 3022 centos@127.0.0.1`

**Comment by Dani21** [comment]
> 
> 
> @roblourens
> For me, somehow my Windows `~/.ssh/config` (which is `C:\users\<my username>\.ssh\config`) is not using the `Port` option. Here is my config:
> 
> ```
> Host centos@127.0.0.1
>     HostName 127.0.0.1
>     User centos
>     Port 3022
>     PasswordAuthentication yes
>     IdentityFile: C:\users\sakim\.ssh\privatekey
> ```
> 
> Running the `Remote-SSH: Connect to Host...` command gives the following, which is running on port `22` and not `3022`. But strangely, it is using the `Hostname` and `User`, just not the port.

It isn't using Hostname and User, it's using Host. If you renamed your host to something else, it would try to connect to that regardless of what's in `User` and `Hostname`. You need to change your config file to the following to work:

```
Host centos@127.0.0.1:3022
```

You can drop everything else because Remote SSH is going to ignore all of that anyways.

**Comment by Dani21** [comment]
> 
> 
> Can you explain in what way is it being ignored? We just run `ssh <host>` and let ssh read the config file.

Based on your explanation, OpenSSH isn't reading the config file at all, including the "Host" entry. The plugin is reading the "Host" entry, and ssh is assuming that's all it needs to know to connect. Perhaps you should point it to read config file.

Here's a basic test I did to show evidence of this:

![image](https://user-images.githubusercontent.com/1804643/61495376-baadea00-a96d-11e9-8c1e-f49259fb12b3.png)

**Comment by roblourens** [comment]
Yeah it seems like git ssh is not seeing your config file. I can't reproduce this.

Can you try `which ssh` to check that ssh on your path is in that dir (or just try with `.\ssh.exe` in that folder) and also try with `-vvv` without -F and share that log?

For me the first line is `debug1: Reading configuration data /c/Users/roblou/.ssh/config`

**Comment by samk64** [comment]
just for reference, i got mine working with the following:
* upgrade to [Git for Windows](https://git-scm.com/download/win) 2.22.0 (previously was around ~v1.8)
* move SSH key to `~/.ssh/id_rsa`
* in VSCode, set `remote.SSH.path` to the location of the newly installed `ssh`, `C:\Program Files\Git\usr\bin\ssh.exe` (i could've added that directory to the `PATH` environment variable instead)
* add write access to `~/.ssh/known_hosts` (by right clicking on the file in windows explorer --> properties --> security tab -->  click edit button --> select users group --> click on write checkbox). this was to allow VSCode to add my VM as a known host without requiring user input to confirm connection.

Using this config, i can now connect over port 3022, since it's reading all of the settings.
```
Host localhost
    User centos
    HostName 127.0.0.1
    Port 3022
    PasswordAuthentication no
    StrictHostKeyChecking no
    ForwardAgent yes
```
I couldn't get the `IdentityFile` setting to work, i just worked around it by using the default location `~/.ssh/id_rsa`.

----

@roblourens, your suggestion of just specifying everything using the `Host` value worked with my **older version of Git for Windows (~1.8)**. The downside to that is that I couldn't pass in options such as `StrictHostKeyChecking=no` and `PasswordAuthentication=no`. 

After I updated to the **newer version of Git for Windows (2.22.0)**, the behavior was different.
* I can't specify `centos@127.0.0.1:3022` for the `Host` value. 
```
remote-ssh@0.44.2
win32 x64
SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a223132372e302e302e313a33303232222c2275736572223a2263656e746f73227d", attempt 1
SSH Resolver called for host: centos@127.0.0.1:3022
Setting up SSH remote "127.0.0.1:3022"
Using commit id "2213894ea0415ee8c85c5eea0d0ff81ecc191529" and quality "stable" for server
Testing ssh with C:\Program Files\Git\usr\bin\ssh.exe -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_8.0p1, OpenSSL 1.1.1c  28 May 2019
Running script with connection command: "C:\Program Files\Git\usr\bin\ssh.exe"  -o ClearAllForwardings=true    "centos@127.0.0.1:3022" bash
Install and start server if needed
> The filename, directory name, or volume label syntax is incorrect.
> 
> ssh: Could not resolve hostname 127.0.0.1:3022: Name or service not known
> 
"install" terminal command done
Received install output: ssh: Could not resolve hostname 127.0.0.1:3022: Name or service not known
Could not resolve hostname
------
```
* On the plus side, instead now I **can** specify the separate values `HostName`, `Port`, and `User`, along with `StrictHostKeyChecking`, `PasswordAuthentication`, etc.

**Comment by roblourens** [comment]
Lots has changed in the extension - please let me know if this is still an issue
