### ISSUE TITLE
能不能为每个连接增加一个别名设置 （Is it possible to add an alias for each connection setting）

### ISSUE THREAD

**Issue by ELISHELL** [microsoft/vscode-remote-release#9574]
Type: <b>Feature Request</b>

每当我连接主机的时候，总会不知道选哪个。
尤其当你的 HOST 是 ip 的时候。

Whenever I connect to a host, I don't know which one to choose.
Especially if your HOST is an IP.

Extension version: 0.108.0
VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 3.10.0-1160.71.1.el7.x86_64
Connection to 'SSH' could not be established

**Comment by ELISHELL** [comment]
<img width="258" alt="屏幕截图 2024-02-21 131739" src="https://github.com/microsoft/vscode-remote-release/assets/40913036/aa006e79-cba0-4afd-8afd-f4e7ee92e2f4">

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

![vscode ssh remote](https://github.com/microsoft/vscode-remote-release/assets/40913036/0d8fefdb-d8ad-47f7-882b-5d902a1cb07a)

**Comment by bamurtaugh** [comment]
Thanks for opening. I believe what'd address your issue is using an alias in your SSH config file:

- Use command **Remote-SSH: Open SSH Configuration File** to open the file in VS Code (or you can edit it from anywhere else you prefer)
- Set a `Host <alias_name_you_choose>` for each machine you'd like to have an alias

If I might've missed anything in your issue/setup, please let me know!
